# 🌱 HydroGrow AI — Phase 1: Data Understanding & Cleaning

---

**Full Title:** HydroGrow AI: An Intelligent Decision Support System for Hydroponic Lettuce Growth Prediction, Disease Prevention and Growth Optimization

**Notebook:** `01_Data_Understanding_and_Cleaning.ipynb`  
**Author:** HydroGrow AI Team  
**Date:** 2026-07-15  
**Version:** 1.0

---

## 1 · Project Introduction

### 1.1 Objective

HydroGrow AI is designed to become a production-grade **AI-powered Hydroponic Assistant** capable of:

| Capability | Status |
|---|---|
| Understanding hydroponic lettuce data | 🔄 Phase 1 (this notebook) |
| Predicting plant growth | 📋 Planned |
| Predicting plant requirements | 📋 Planned |
| Supporting disease prevention | 📋 Planned |
| Providing intelligent recommendations | 📋 Planned |
| Machine Learning integration | 📋 Planned |
| ChatGPT-like web application | 📋 Planned |

**This notebook focuses exclusively on Phase 1**: data understanding, quality assessment, and safe cleaning.

### 1.2 Dataset Overview

Three independent hydroponic lettuce experiments are available, each stored as an Excel workbook containing multiple sheets:

| Dataset | Description |
|---|---|
| **Experiment 1** | Environmental conditions & plant measurements (6 sheets) |
| **Experiment 2** | Environmental conditions & plant measurements (7 sheets) |
| **Experiment 3** | Environmental conditions & plant measurements (5 sheets) |

Each workbook typically contains sheets for:
- **Seedlings measurements** — baseline plant biometrics at transplant
- **Water quality (Sensor)** — continuous pH, EC, TDS, temperature, humidity, CO₂
- **Water quality (Portable)** — manual spot-check measurements across replicates
- **Nutrients & Water consumptions** — nutrient dosing and water usage logs
- **Harvest measurements** — final harvest biometrics per replicate/treatment
- Additional sheets (Head diameter, Taste tests, Survey forms) in some experiments

### 1.3 Expected Workflow

```
Phase 1 (This Notebook)
├── Load all raw datasets
├── Understand structure & semantics
├── Assess data quality comprehensively
├── Apply only safe, reversible cleaning
├── Validate cleaning outcomes
├── Generate data dictionary
└── Save cleaned datasets → data/processed/
```

> ⚠️ **Guiding Principle:** We never delete rows due to outliers, never invent missing values, and never remove suspicious values. If something looks questionable, we **flag it** and document it for expert review.

---

## 2 · Import Libraries

In [9]:
"""
Import only the libraries required for Phase 1.
No ML / DL / visualization-heavy imports at this stage.
"""

import os
import sys
import logging
import warnings
from pathlib import Path
from typing import Dict, List, Tuple, Optional, Any

import numpy as np
import pandas as pd
from IPython.display import display, Markdown, HTML

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
pd.set_option("display.max_columns", 60)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 40)
pd.set_option("display.float_format", "{:.4f}".format)

# ---------------------------------------------------------------------------
# Logging — gives us a persistent audit trail inside the notebook
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("HydroGrow")
logger.info("Libraries imported successfully.")

# ---------------------------------------------------------------------------
# Project paths (relative — never hardcoded absolutes)
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(os.getcwd()).parent  # notebooks/ → project root
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"
PROCESSED_DATA_DIR.mkdir(parents=True, exist_ok=True)

logger.info(f"Project root : {PROJECT_ROOT}")
logger.info(f"Raw data dir : {RAW_DATA_DIR}")
logger.info(f"Processed dir: {PROCESSED_DATA_DIR}")

print(f"\n✅ Python {sys.version}")
print(f"✅ pandas {pd.__version__}  |  numpy {np.__version__}")

2026-07-15 19:47:37,441 | INFO | Libraries imported successfully.
2026-07-15 19:47:37,443 | INFO | Project root : e:\HydroGrow-AI
2026-07-15 19:47:37,445 | INFO | Raw data dir : e:\HydroGrow-AI\data\raw
2026-07-15 19:47:37,445 | INFO | Processed dir: e:\HydroGrow-AI\data\processed

✅ Python 3.14.4 (tags/v3.14.4:23116f9, Apr  7 2026, 14:10:54) [MSC v.1944 64 bit (AMD64)]
✅ pandas 3.0.3  |  numpy 2.4.4

---

## 3 · Load Data

Each experiment workbook contains **multiple sheets** with different structures (multi-row headers, merged cells, sub-tables). We load every sheet of every workbook into a structured dictionary so no information is lost.

In [10]:
import sys

print(sys.executable)
print(sys.version)

c:\Python314\python.exe
3.14.4 (tags/v3.14.4:23116f9, Apr  7 2026, 14:10:54) [MSC v.1944 64 bit (AMD64)]

In [11]:
from pathlib import Path
from typing import Dict, List
import pandas as pd

# -------------------------------
# Project Paths
# -------------------------------
PROJECT_ROOT = Path.cwd().parent

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"

if not RAW_DATA_DIR.exists():
    raise FileNotFoundError(f"Raw data folder not found: {RAW_DATA_DIR}")

# -------------------------------
# Discover Excel Files
# -------------------------------
def discover_excel_files(directory: Path) -> List[Path]:
    """Discover all .xlsx files in the given directory."""
    files = sorted(directory.glob("*.xlsx"))

    if not files:
        raise FileNotFoundError(f"No .xlsx files found in {directory}")

    print(f"\n✅ Found {len(files)} Excel file(s):")

    for f in files:
        print(f"   - {f.name}")

    return files


# -------------------------------
# Load All Sheets
# -------------------------------
def load_all_sheets(filepath: Path) -> Dict[str, pd.DataFrame]:
    """
    Load every sheet from an Excel workbook.
    """

    xl = pd.ExcelFile(filepath, engine="openpyxl")

    sheets = {}

    for name in xl.sheet_names:

        sheets[name] = pd.read_excel(
            filepath,
            sheet_name=name,
            header=None,
            engine="openpyxl"
        )

        print(
            f"      ✓ {name:<40} "
            f"{sheets[name].shape[0]} rows × {sheets[name].shape[1]} cols"
        )

    return sheets


# -------------------------------
# Discover and Load
# -------------------------------
excel_files = discover_excel_files(RAW_DATA_DIR)

experiments_raw = {}

for idx, fpath in enumerate(excel_files, start=1):

    label = f"Experiment {idx}"

    print(f"\n📂 Loading {label}: {fpath.name}")

    experiments_raw[label] = load_all_sheets(fpath)

# -------------------------------
# Summary
# -------------------------------
print("\n" + "=" * 80)
print("LOADING SUMMARY")
print("=" * 80)

for exp_label, sheets in experiments_raw.items():

    total_rows = sum(df.shape[0] for df in sheets.values())

    print(f"\n📁 {exp_label}")
    print(f"   Total Sheets : {len(sheets)}")
    print(f"   Total Rows   : {total_rows:,}")

    for sheet_name, df in sheets.items():
        print(f"   ├── {sheet_name:<40} {df.shape[0]:>6} × {df.shape[1]:>3}")

print("\n✅ All datasets loaded successfully.")

✅ Found 3 Excel file(s):
   - EXP.1. Environmental Conditions and Plant Measurements.xlsx
   - EXP.2. Environmental Conditions and Plant Measurements.xlsx
   - EXP.3. Environmental Conditions and Plant Measurements.xlsx

📂 Loading Experiment 1: EXP.1. Environmental Conditions and Plant Measurements.xlsx
      ✓ Seedlings measurements                   12 rows × 11 cols
      ✓ Water quality measurments Senso          643 rows × 11 cols
      ✓ Water quality parametersPortabl          36 rows × 56 cols
      ✓ Nutrients  Water consumptions            26 rows × 23 cols
      ✓ Head diameter                            73 rows × 10 cols
      ✓ Harvest measurements 842024              117 rows × 11 cols

📂 Loading Experiment 2: EXP.2. Environmental Conditions and Plant Measurements.xlsx
      ✓ Seedlings measurements                   14 rows × 11 cols
      ✓ Water quality measurments Senso          720 rows × 11 cols
      ✓ Water quality parametersPortabl          32 rows × 56 cols
      ✓ Nutrients  Water consumptions            26 rows × 15 cols
      ✓ Harvest measurements                     95 rows × 11 cols
      ✓ Test Taste                               7 rows × 24 cols
      ✓ Form Responses 1                         7 rows × 25 cols

📂 Loading Experiment 3: EXP.3. Environmental Conditions and Plant Measurements.xlsx
      ✓ Seedlings measurements 1952024           12 rows × 10 cols
      ✓ Water quality measurments Senso          714 rows × 11 cols
      ✓ Water quality parametersPortabl          36 rows × 56 cols
      ✓ Nutrients Water Consumptions             13 rows × 23 cols
      ✓ Harvest measurements 1862024             91 rows × 12 cols

================================================================================
LOADING SUMMARY
================================================================================

📁 Experiment 1
   Total Sheets : 6
   Total Rows   : 907
   ├── Seedlings measurements                       12 ×  11
   ├── Water quality measurments Senso             643 ×  11
   ├── Water quality parametersPortabl              36 ×  56
   ├── Nutrients  Water consumptions                26 ×  23
   ├── Head diameter                                73 ×  10
   ├── Harvest measurements 842024                 117 ×  11

📁 Experiment 2
   Total Sheets : 7
   Total Rows   : 901
   ├── Seedlings measurements                       14 ×  11
   ├── Water quality measurments Senso             720 ×  11
   ├── Water quality parametersPortabl              32 ×  56
   ├── Nutrients  Water consumptions                26 ×  15
   ├── Harvest measurements                         95 ×  11
   ├── Test Taste                                    7 ×  24
   ├── Form Responses 1                              7 ×  25

📁 Experiment 3
   Total Sheets : 5
   Total Rows   : 866
   ├── Seedlings measurements 1952024               12 ×  10
   ├── Water quality measurments Senso             714 ×  11
   ├── Water quality parametersPortabl              36 ×  56
   ├── Nutrients Water Consumptions                 13 ×  23
   ├── Harvest measurements 1862024                 91 ×  12

✅ All datasets loaded successfully.

### 3.1 Parse Sheets into Clean DataFrames

The raw Excel sheets use **multi-row headers**, **merged cells**, and **sub-tables** side-by-side. Below we parse each sheet type into properly-headed DataFrames using dedicated parser functions.

> We apply **minimal parsing only** — setting correct headers and stripping structural artifacts. No data values are modified.

In [12]:
# ==========================================================================
# Sheet Parsers — one per sheet type
# ==========================================================================

def safe_str_row(series: pd.Series) -> list:
    """
    Convert a pandas Series (row) into a list of clean Python strings.
    Handles pandas 3.x nullable string dtype where .astype(str)
    preserves NaN as float('nan') instead of the string 'nan'.
    Returns '' for any missing/NaN/NaT values.
    """
    return [str(v).strip() if pd.notna(v) else "" for v in series]


def parse_seedlings(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:
    """
    Parse the Seedlings measurements sheet.
    Row 0 is a title row; Row 1 contains column headers; Data starts at Row 2.
    """
    headers = safe_str_row(df_raw.iloc[1])
    data = df_raw.iloc[2:].copy()
    data.columns = headers
    data = data.reset_index(drop=True)
    data.insert(0, "experiment", exp_label)
    return data


def parse_sensor_water_quality(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:
    """
    Parse the Water quality measurements (Sensor) sheet.
    Row 0: replicate label; Row 1: column headers.
    Columns 0-5: Water quality; Columns 6-10: Air parameters.
    Data starts at Row 2.
    """
    # Extract replicate label from row 0 (e.g., 'Replicate 1 T1')
    replicate_label = str(df_raw.iloc[0, 2]).strip() if pd.notna(df_raw.iloc[0, 2]) else "Unknown"

    headers = safe_str_row(df_raw.iloc[1])
    data = df_raw.iloc[2:].copy()
    data.columns = headers
    data = data.reset_index(drop=True)
    data.insert(0, "replicate", replicate_label)
    data.insert(0, "experiment", exp_label)

    # The sheet has two Date/Time column pairs (water + air)
    # Rename to disambiguate
    cols = list(data.columns)
    seen = {}
    new_cols = []
    for c in cols:
        if c in seen:
            seen[c] += 1
            new_cols.append(f"{c}_{seen[c]}")
        else:
            seen[c] = 0
            new_cols.append(c)
    data.columns = new_cols
    return data


def parse_portable_water_quality(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:
    """
    Parse the Water quality parameters (Portable) sheet.
    This has a complex 3-row header: Row 0 = time slots & air params,
    Row 1 = replicate labels, Row 2 = measurement names.
    Data starts at Row 3.
    """
    row0 = safe_str_row(df_raw.iloc[0])
    row1 = safe_str_row(df_raw.iloc[1])
    row2 = safe_str_row(df_raw.iloc[2])

    # Build composite column names: {time}_{replicate}_{measurement}
    composite_cols = []
    current_time = "unknown"
    current_replicate = "unknown"

    for i in range(len(row0)):
        r0 = row0[i]
        r1 = row1[i]
        r2 = row2[i]

        if r0 and r0 not in ("nan", "NaT") and "Air" not in r0 and "Date" not in r0:
            current_time = r0.replace(":", "")
        if r0 in ("Date", "Date "):
            current_time = "date"
        if r0 and "Air" in r0:
            current_replicate = "Air"

        if r1 and r1 not in ("nan", "NaT") and (not r0 or "Air" not in r0):
            current_replicate = r1.replace(" ", "_")

        if r2 and r2 not in ("nan", "NaT"):
            measurement = r2
        else:
            measurement = r0 if (r0 and r0 not in ("nan", "NaT")) else f"col_{i}"

        if current_time == "date":
            col_name = "date"
        elif current_replicate == "Air":
            col_name = f"{current_time}_air_{measurement}"
        else:
            col_name = f"{current_time}_{current_replicate}_{measurement}"

        composite_cols.append(col_name)

    # Ensure uniqueness
    seen = {}
    unique_cols = []
    for c in composite_cols:
        c_clean = c.replace(" ", "_").replace(".", "").lower()
        if c_clean in seen:
            seen[c_clean] += 1
            unique_cols.append(f"{c_clean}_{seen[c_clean]}")
        else:
            seen[c_clean] = 0
            unique_cols.append(c_clean)

    data = df_raw.iloc[3:].copy()
    data.columns = unique_cols
    data = data.reset_index(drop=True)
    data.insert(0, "experiment", exp_label)
    return data


def parse_nutrients_water(df_raw: pd.DataFrame, exp_label: str) -> Dict[str, pd.DataFrame]:
    """
    Parse the Nutrients & Water consumptions sheet.
    Contains 2 or 3 side-by-side sub-tables separated by blank columns.
    Returns a dict of parsed sub-tables.
    """
    row0 = df_raw.iloc[0]

    # Find sub-table boundaries from row 0 headers
    sub_tables = {}
    current_label = None
    start_col = None

    for i, val in enumerate(row0):
        val_str = str(val).strip() if pd.notna(val) else ""
        if val_str and val_str not in ("nan", "NaT"):
            # Close previous sub-table
            if current_label is not None:
                sub_tables[current_label] = (start_col, i - 1)
            current_label = val_str
            start_col = i
    # Close last sub-table
    if current_label is not None:
        sub_tables[current_label] = (start_col, len(row0) - 1)

    result = {}
    for label, (sc, ec) in sub_tables.items():
        cols_range = list(range(sc, ec + 1))
        sub_df = df_raw.iloc[1:, cols_range].copy()

        # Drop fully empty columns
        sub_df = sub_df.dropna(axis=1, how="all")

        if sub_df.empty or sub_df.shape[1] == 0:
            continue

        # Row 0 of sub_df has replicate headers
        header_vals = safe_str_row(sub_df.iloc[0])
        sub_data = sub_df.iloc[1:].copy()

        # Build column names
        new_cols = []
        for j, h in enumerate(header_vals):
            if j == 0 and ("date" in label.lower() or not h or h in ("nan", "NaT")):
                new_cols.append("date")
            elif not h or h in ("nan", "NaT"):
                new_cols.append(f"col_{j}")
            else:
                new_cols.append(h.replace(" ", "_"))

        sub_data.columns = new_cols
        sub_data = sub_data.reset_index(drop=True)
        sub_data.insert(0, "experiment", exp_label)

        # Clean label for dict key
        clean_label = label.replace(" ", "_").replace(".", "").lower()
        result[clean_label] = sub_data

    return result


def parse_harvest(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:
    """
    Parse the Harvest measurements sheet.
    These sheets contain multiple replicate/treatment sub-tables stacked vertically.
    Row pattern: [Replicate-Treatment label], [Column headers], [Data rows], [blank], repeat.
    """
    all_records = []
    current_system = None
    header_row = None

    # Determine if this is EXP3 format (has 'System' column)
    has_system_col = False
    for i in range(min(5, len(df_raw))):
        row_vals = [str(v).strip() if pd.notna(v) else "" for v in df_raw.iloc[i]]
        if "System" in row_vals or "System " in row_vals:
            has_system_col = True
            break

    if has_system_col:
        # EXP3 format: single table with a 'System' column
        for i in range(len(df_raw)):
            row_vals = [str(v).strip() if pd.notna(v) else "" for v in df_raw.iloc[i]]
            if "Plant No." in row_vals or "Plant No" in row_vals:
                header_row = i
                break

        if header_row is not None:
            headers = safe_str_row(df_raw.iloc[header_row])
            data = df_raw.iloc[header_row + 1:].copy()
            data.columns = headers
            data = data.dropna(how="all").reset_index(drop=True)

            # Forward-fill the System column
            if "System " in data.columns:
                data = data.rename(columns={"System ": "system"})
            elif "System" in data.columns:
                data = data.rename(columns={"System": "system"})
            if "system" in data.columns:
                data["system"] = data["system"].replace("", np.nan).ffill()
            data.insert(0, "experiment", exp_label)
            return data

    # EXP1/EXP2 format: multiple sub-tables separated by replicate headers
    i = 0
    while i < len(df_raw):
        row_vals = [str(v).strip() if pd.notna(v) else "" for v in df_raw.iloc[i]]
        first_val = row_vals[0]

        # Detect replicate/treatment label rows (e.g., 'R1-T1', 'R2-T2')
        if first_val and first_val.startswith("R") and "T" in first_val and "Plant" not in first_val:
            current_system = first_val
            i += 1
            continue

        # Detect header row
        if "Plant No" in first_val or first_val == "Plant No.":
            header_row = [str(v).strip() if pd.notna(v) else "" for v in df_raw.iloc[i]]
            i += 1
            continue

        # Skip completely empty rows
        if all(v == "" or v == "nan" for v in row_vals):
            i += 1
            continue

        # Data row
        if header_row is not None and current_system is not None:
            record = dict(zip(header_row, df_raw.iloc[i].tolist()))
            record["system"] = current_system
            all_records.append(record)

        i += 1

    if all_records:
        result = pd.DataFrame(all_records)
        result.insert(0, "experiment", exp_label)
        return result

    # Fallback: return raw with experiment label
    df_raw.insert(0, "experiment", exp_label)
    return df_raw


def parse_head_diameter(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:
    """
    Parse the Head diameter sheet (EXP1 only).
    Row 0: day labels; Row 1: replicate label; Row 2: column headers.
    Data starts at Row 3. Structure: pairs of (Plant no, Head diameter) per day.
    """
    # Extract day labels from row 0
    day_labels = []
    for val in df_raw.iloc[0]:
        s = str(val).strip() if pd.notna(val) else ""
        if s and s not in ("nan", "NaT"):
            day_labels.append(s)

    # Identify replicate boundaries from row 1
    replicate_rows = []
    i = 1
    while i < len(df_raw):
        first_val = str(df_raw.iloc[i, 0]).strip() if pd.notna(df_raw.iloc[i, 0]) else ""
        if first_val.startswith("Replicate") or first_val.startswith("replicate"):
            replicate_rows.append((first_val, i))
        i += 1

    all_records = []

    for rep_idx, (rep_label, rep_row) in enumerate(replicate_rows):
        data_start = rep_row + 2
        if rep_idx + 1 < len(replicate_rows):
            data_end = replicate_rows[rep_idx + 1][1]
        else:
            data_end = len(df_raw)

        for row_i in range(data_start, data_end):
            row = df_raw.iloc[row_i]
            if pd.isna(row.iloc[0]):
                continue
            for day_idx, day_label in enumerate(day_labels):
                col_start = day_idx * 2
                if col_start + 1 < len(row):
                    record = {
                        "experiment": exp_label,
                        "replicate": rep_label,
                        "day": day_label,
                        "plant_no": row.iloc[col_start],
                        "head_diameter": row.iloc[col_start + 1],
                    }
                    all_records.append(record)

    return pd.DataFrame(all_records) if all_records else pd.DataFrame()


def parse_taste_test(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:
    """Parse Taste Test sheet — preserve as-is with experiment label."""
    df = df_raw.copy()
    df.insert(0, "experiment", exp_label)
    return df


def parse_form_responses(df_raw: pd.DataFrame, exp_label: str) -> pd.DataFrame:
    """Parse Form Responses sheet — preserve as-is with experiment label."""
    df = df_raw.copy()
    df.insert(0, "experiment", exp_label)
    return df

# ==========================================================
# Parser Registration Complete
# ==========================================================

import logging

# Create logger only if it doesn't already exist
try:
    logger
except NameError:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s"
    )
    logger = logging.getLogger("HydroGrowAI")

logger.info("✅ Sheet parser functions loaded successfully.")

print("=" * 70)
print("✅ All sheet parser functions have been defined successfully.")
print("=" * 70)

2026-07-15 19:47:52,321 | INFO | ✅ Sheet parser functions loaded successfully.

======================================================================
✅ All sheet parser functions have been defined successfully.
======================================================================

In [13]:
# ==========================================================================
# Route each sheet to its parser based on sheet name patterns
# ==========================================================================

def classify_and_parse_sheet(
    sheet_name: str, df_raw: pd.DataFrame, exp_label: str
) -> Tuple[str, Any]:
    """
    Classify a sheet by its name and dispatch to the appropriate parser.
    Returns (category, parsed_result) where parsed_result is a DataFrame
    or dict of DataFrames.
    """
    sn = sheet_name.lower().strip()

    if "seedling" in sn:
        return "seedlings", parse_seedlings(df_raw, exp_label)
    elif "senso" in sn or "sensor" in sn:
        return "sensor_water_quality", parse_sensor_water_quality(df_raw, exp_label)
    elif "portabl" in sn:
        return "portable_water_quality", parse_portable_water_quality(df_raw, exp_label)
    elif "nutrient" in sn:
        return "nutrients", parse_nutrients_water(df_raw, exp_label)
    elif "harvest" in sn:
        return "harvest", parse_harvest(df_raw, exp_label)
    elif "head" in sn and "diameter" in sn:
        return "head_diameter", parse_head_diameter(df_raw, exp_label)
    elif "taste" in sn or "test taste" in sn:
        return "taste_test", parse_taste_test(df_raw, exp_label)
    elif "form" in sn or "response" in sn:
        return "form_responses", parse_form_responses(df_raw, exp_label)
    else:
        logger.warning(f"Unknown sheet type: '{sheet_name}' — preserving raw.")
        df_raw.insert(0, "experiment", exp_label)
        return "unknown", df_raw


# ==========================================================================
# Parse all experiments
# ==========================================================================
parsed_data: Dict[str, Dict[str, Any]] = {}

for exp_label, sheets in experiments_raw.items():
    logger.info(f"Parsing {exp_label}...")
    parsed_data[exp_label] = {}
    for sheet_name, df_raw in sheets.items():
        category, result = classify_and_parse_sheet(sheet_name, df_raw.copy(), exp_label)

        # Nutrients parser returns a dict of sub-tables
        if isinstance(result, dict):
            for sub_key, sub_df in result.items():
                full_key = f"{category}_{sub_key}"
                parsed_data[exp_label][full_key] = sub_df
                logger.info(f"  ✓ {full_key}: {sub_df.shape}")
        else:
            parsed_data[exp_label][category] = result
            if isinstance(result, pd.DataFrame):
                logger.info(f"  ✓ {category}: {result.shape}")

print("\n✅ All sheets parsed successfully.")

2026-07-15 19:48:02,755 | INFO | Parsing Experiment 1...
2026-07-15 19:48:02,757 | INFO |   ✓ seedlings: (10, 12)
2026-07-15 19:48:02,761 | INFO |   ✓ sensor_water_quality: (641, 13)
2026-07-15 19:48:02,763 | INFO |   ✓ portable_water_quality: (33, 57)
2026-07-15 19:48:02,769 | INFO |   ✓ nutrients_date: (24, 2)
2026-07-15 19:48:02,770 | INFO |   ✓ nutrients_nutrient_solution_addition_(a+b)_ml: (24, 7)
2026-07-15 19:48:02,771 | INFO |   ✓ nutrients_acid_consumption_(ml): (24, 7)
2026-07-15 19:48:02,771 | INFO |   ✓ nutrients_water_consumption_l: (24, 7)
2026-07-15 19:48:02,783 | INFO |   ✓ head_diameter: (300, 5)
2026-07-15 19:48:02,794 | INFO |   ✓ harvest: (73, 13)
2026-07-15 19:48:02,795 | INFO | Parsing Experiment 2...
2026-07-15 19:48:02,796 | INFO |   ✓ seedlings: (12, 12)
2026-07-15 19:48:02,799 | INFO |   ✓ sensor_water_quality: (718, 13)
2026-07-15 19:48:02,802 | INFO |   ✓ portable_water_quality: (29, 57)
2026-07-15 19:48:02,805 | INFO |   ✓ nutrients_date: (24, 2)
2026-07-15 19:48:02,806 | INFO |   ✓ nutrients_nutrient_solution_addition_(a+b)_ml: (24, 7)
2026-07-15 19:48:02,806 | INFO |   ✓ nutrients_water_consumption_l: (24, 7)
2026-07-15 19:48:02,814 | INFO |   ✓ harvest: (78, 13)
2026-07-15 19:48:02,815 | INFO |   ✓ taste_test: (7, 25)
2026-07-15 19:48:02,816 | INFO |   ✓ form_responses: (7, 26)
2026-07-15 19:48:02,817 | INFO | Parsing Experiment 3...
2026-07-15 19:48:02,819 | INFO |   ✓ seedlings: (10, 11)
2026-07-15 19:48:02,822 | INFO |   ✓ sensor_water_quality: (712, 13)
2026-07-15 19:48:02,823 | INFO |   ✓ portable_water_quality: (33, 57)
2026-07-15 19:48:02,828 | INFO |   ✓ nutrients_date: (11, 2)
2026-07-15 19:48:02,829 | INFO |   ✓ nutrients_nutrient_solution_addition_(a+b)_ml: (11, 7)
2026-07-15 19:48:02,829 | INFO |   ✓ nutrients_water_consumption_l: (11, 7)
2026-07-15 19:48:02,830 | INFO |   ✓ nutrients_acid_consumption_ml: (11, 7)
2026-07-15 19:48:02,836 | INFO |   ✓ harvest: (83, 13)

✅ All sheets parsed successfully.

In [14]:
# ==========================================================================
# Display parsed data summary per experiment
# ==========================================================================

def display_shape_summary(label: str, df: pd.DataFrame) -> None:
    """Display a formatted shape summary for a DataFrame."""
    print(f"  {label:<35s}  →  {df.shape[0]:>6,} rows × {df.shape[1]:>3} cols")


print("=" * 70)
print("PARSED DATA SUMMARY PER EXPERIMENT")
print("=" * 70)

for exp_label, tables in parsed_data.items():
    print(f"\n📂 {exp_label}")
    for tname, tdata in tables.items():
        if isinstance(tdata, pd.DataFrame):
            display_shape_summary(tname, tdata)
        else:
            print(f"  {tname:<35s}  →  (non-DataFrame: {type(tdata).__name__})")

======================================================================
PARSED DATA SUMMARY PER EXPERIMENT
======================================================================

📂 Experiment 1
  seedlings                            →      10 rows ×  12 cols
  sensor_water_quality                 →     641 rows ×  13 cols
  portable_water_quality               →      33 rows ×  57 cols
  nutrients_date                       →      24 rows ×   2 cols
  nutrients_nutrient_solution_addition_(a+b)_ml  →      24 rows ×   7 cols
  nutrients_acid_consumption_(ml)      →      24 rows ×   7 cols
  nutrients_water_consumption_l        →      24 rows ×   7 cols
  head_diameter                        →     300 rows ×   5 cols
  harvest                              →      73 rows ×  13 cols

📂 Experiment 2
  seedlings                            →      12 rows ×  12 cols
  sensor_water_quality                 →     718 rows ×  13 cols
  portable_water_quality               →      29 rows ×  57 cols
  nutrients_date                       →      24 rows ×   2 cols
  nutrients_nutrient_solution_addition_(a+b)_ml  →      24 rows ×   7 cols
  nutrients_water_consumption_l        →      24 rows ×   7 cols
  harvest                              →      78 rows ×  13 cols
  taste_test                           →       7 rows ×  25 cols
  form_responses                       →       7 rows ×  26 cols

📂 Experiment 3
  seedlings                            →      10 rows ×  11 cols
  sensor_water_quality                 →     712 rows ×  13 cols
  portable_water_quality               →      33 rows ×  57 cols
  nutrients_date                       →      11 rows ×   2 cols
  nutrients_nutrient_solution_addition_(a+b)_ml  →      11 rows ×   7 cols
  nutrients_water_consumption_l        →      11 rows ×   7 cols
  nutrients_acid_consumption_ml        →      11 rows ×   7 cols
  harvest                              →      83 rows ×  13 cols

---

## 4 · Dataset Overview

For each experiment we display shape, head/tail rows, column names, data types, memory usage, and summary statistics.

In [15]:
def dataset_overview(df: pd.DataFrame, title: str) -> None:
    """
    Display a comprehensive overview of a DataFrame:
    shape, head, tail, columns, dtypes, memory, summary stats.
    """
    display(Markdown(f"### {title}"))

    # Shape
    display(Markdown(f"**Shape:** `{df.shape[0]:,}` rows × `{df.shape[1]}` columns"))

    # First 5 rows
    display(Markdown("**First 5 rows:**"))
    display(df.head())

    # Last 5 rows
    display(Markdown("**Last 5 rows:**"))
    display(df.tail())

    # Column names and types
    col_info = pd.DataFrame({
        "Column": df.columns,
        "Dtype": df.dtypes.values,
        "Non-Null Count": df.notna().sum().values,
        "Null Count": df.isna().sum().values,
    })
    display(Markdown("**Column Names & Data Types:**"))
    display(col_info)

    # Memory usage
    mem_bytes = df.memory_usage(deep=True).sum()
    display(Markdown(
        f"**Memory Usage:** `{mem_bytes / 1024:.1f}` KB "
        f"(`{mem_bytes / (1024**2):.3f}` MB)"
    ))

    # Summary statistics
    numeric_df = df.select_dtypes(include=[np.number])
    if not numeric_df.empty:
        display(Markdown("**Summary Statistics (numeric columns):**"))
        display(numeric_df.describe())
    else:
        display(Markdown("*No numeric columns to summarize.*"))

    print("\n" + "─" * 70 + "\n")

In [16]:
# Display overview for each parsed table across all experiments
for exp_label, tables in parsed_data.items():
    display(Markdown(f"## 📂 {exp_label}"))
    display(Markdown("---"))
    for tname, tdata in tables.items():
        if isinstance(tdata, pd.DataFrame) and not tdata.empty:
            dataset_overview(tdata, f"{exp_label} — {tname}")

## 📂 Experiment 1

---

### Experiment 1 — seedlings

**Shape:** `10` rows × `12` columns

**First 5 rows:**

,experiment,Date,plant NO.,plant height (cm),shoot length (cm),root length (cm),head diameter (cm),stem diameter (cm),total weight (g),shoot weight (g),root weight (g),no. of leaves
0,Experiment 1,2024-09-03 00:00:00,1,9,2,7,4*2,0.1000,1.3000,0.5000,0.8000,5
1,Experiment 1,NaN,2,10,3,7,3.5*3,0.1000,1.2000,0.5500,0.6500,5
2,Experiment 1,NaN,3,10,3,7,3.5*2.5,0.1000,1.1000,0.5300,0.5700,5
3,Experiment 1,NaN,4,9,2.5000,6.5000,3*3,0.1000,1.1400,0.4500,0.6900,4
4,Experiment 1,NaN,5,10,3,7,3.5*2.5,0.1000,1,0.4000,0.6000,5

**Last 5 rows:**

,experiment,Date,plant NO.,plant height (cm),shoot length (cm),root length (cm),head diameter (cm),stem diameter (cm),total weight (g),shoot weight (g),root weight (g),no. of leaves
5,Experiment 1,NaN,6,10,3,7,3.5*3,0.1000,1.1000,0.4400,0.6600,5
6,Experiment 1,NaN,7,9,2,7,2*3.5,0.1000,1,0.4000,0.6000,5
7,Experiment 1,NaN,8,9,2,7,4*3.5,0.1000,1.5000,0.6000,0.9000,5
8,Experiment 1,NaN,9,9.5000,3,6.5000,3.5*2,0.1000,1.4000,0.5400,0.8600,4
9,Experiment 1,NaN,10,12,3,9,4*2,0.1000,1.5000,0.5700,0.9300,4

**Column Names & Data Types:**

                 Column   Dtype  Non-Null Count  Null Count
0            experiment     str              10           0
1                  Date  object               1           9
2             plant NO.  object              10           0
3    plant height  (cm)  object              10           0
4     shoot length (cm)  object              10           0
5      root length (cm)  object              10           0
6    head diameter (cm)     str              10           0
7   stem diameter  (cm)  object              10           0
8      total weight (g)  object              10           0
9      shoot weight (g)  object              10           0
10      root weight (g)  object              10           0
11        no. of leaves  object              10           0

**Memory Usage:** `4.6` KB (`0.004` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 1 — sensor_water_quality

**Shape:** `641` rows × `13` columns

**First 5 rows:**

,experiment,replicate,Date,Tme,pH,EC,TDS,Water temp.,Date_1,Tme_1,RH %,Air temp. C,CO2 PPM
0,Experiment 1,Replicate 1 T1,,NaN,NaN,NaN,NaN,NaN,2024-03-10 00:00:00,NaN,NaN,NaN,406.9600
1,Experiment 1,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-10 00:00:00,10:00:00,49.0800,24.1800,406.5500
2,Experiment 1,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-10 00:00:00,11:00:00,47.5100,23.5500,413.3800
3,Experiment 1,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-10 00:00:00,12:00:00,46.8000,23.8100,412.5000
4,Experiment 1,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-10 00:00:00,13:00:00,47.1200,24.4800,408.9400

**Last 5 rows:**

,experiment,replicate,Date,Tme,pH,EC,TDS,Water temp.,Date_1,Tme_1,RH %,Air temp. C,CO2 PPM
636,Experiment 1,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-08 00:00:00,09:00:00,55.7100,24.3100,432.2700
637,Experiment 1,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-08 00:00:00,10:00:00,53.1100,25.0600,424.6300
638,Experiment 1,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-08 00:00:00,11:00:00,51.3200,25.5500,419.6700
639,Experiment 1,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-08 00:00:00,12:00:00,50.9400,25.4300,420.0100
640,Experiment 1,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13:00:00,52.6900,26.2500,NaN

**Column Names & Data Types:**

         Column   Dtype  Non-Null Count  Null Count
0    experiment     str             641           0
1     replicate     str             641           0
2          Date     str               1         640
3           Tme     str               0         641
4            pH     str               0         641
5            EC     str               0         641
6           TDS     str               0         641
7   Water temp.     str               0         641
8        Date_1  object             640           1
9         Tme_1  object             640           1
10         RH %  object             640           1
11  Air temp. C  object             640           1
12      CO2 PPM  object             640           1

**Memory Usage:** `323.2` KB (`0.316` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 1 — portable_water_quality

**Shape:** `33` rows × `57` columns

**First 5 rows:**

,experiment,date,100000_replicate_1_t1_ph,100000_replicate_1_t1_ec,100000_replicate_1_t1_tds,100000_replicate_1_t1_water_temp,100000_replicate_2_t1_ph,100000_replicate_2_t1_ec,100000_replicate_2_t1_tds,100000_replicate_2_t1_water_temp,100000_replicate_3_t1_ph,100000_replicate_3_t1_ec,100000_replicate_3_t1_tds,100000_replicate_3_t1_water_temp,100000_replicate_1_t2_ph,100000_replicate_1_t2_ec,100000_replicate_1_t2_tds,100000_replicate_1_t2_water_temp,100000_replicate_2_t2_ph,100000_replicate_2_t2_ec,100000_replicate_2_t2_tds,100000_replicate_2_t2_water_temp,100000_replicate_3_t2_ph,100000_replicate_3_t2_ec,100000_replicate_3_t2_tds,100000_replicate_3_t2_water_temp,100000_air_air_parameters,100000_rh%_col_26,100000_air_temp_col_27,100000_air_temp_col_28,140000_replicate_1_t1_ph,140000_replicate_1_t1_ec,140000_replicate_1_t1_tds,140000_replicate_1_t1_water_temp,140000_replicate_2_t1_ph,140000_replicate_2_t1_ec,140000_replicate_2_t1_tds,140000_replicate_2_t1_water_temp,140000_replicate_3_t1_ph,140000_replicate_3_t1_ec,140000_replicate_3_t1_tds,140000_replicate_3_t1_water_temp,140000_replicate_1_t2_ph,140000_replicate_1_t2_ec,140000_replicate_1_t2_tds,140000_replicate_1_t2_water_temp,140000_replicate_2_t2_ph,140000_replicate_2_t2_ec,140000_replicate_2_t2_tds,140000_replicate_2_t2_water_temp,140000_replicate_3_t2_ph,140000_replicate_3_t2_ec,140000_replicate_3_t2_tds,140000_replicate_3_t2_water_temp,140000_air_air_parameters,140000_rh%_col_54,140000_air_temp_col_55
0,Experiment 1,2024-10-03 00:00:00,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,6.9000,1.6100,0.8000,22.5000,6.9000,1.5700,0.7800,22.5000,6.9000,1.5600,0.7800,22.3000,6.8000,1.5700,0.7800,22.7000,7,1.5600,0.7700,22.9000,6.9000,1.5600,0.7600,23,48300,60.8000,22.1000
1,Experiment 1,2024-11-03 00:00:00,5.3000,2,1,19.3000,5.8000,2.0200,1.0100,19.1000,5.6000,2.0200,1.0100,18.9000,5.6000,1.9400,0.9700,18.6000,5.8000,2.0100,1.0050,19.7000,5.6000,2.1600,1.0800,22.9000,50330,64,20.4000,NaN,5.2000,2,1,23.9000,5.8000,2.0200,1.0100,22.1000,5.7000,2.0100,1.0050,22.3000,5.4000,1.9400,0.9700,22.5000,5.8000,2.0200,1.0100,22.3000,5.6000,2.1600,1.0800,22.9000,61270,59.5000,21.8000
2,Experiment 1,2024-12-03 00:00:00,5.7000,1.9500,0.9750,22,5.8000,2.0200,1.0100,21.2000,5.7000,2.0100,1.0050,20.6000,5.4000,1.9800,0.9900,21.4000,5.9000,2.0200,1.0100,22,6.9000,1.5400,0.7700,22.6000,60540,45,29.5000,NaN,5.7000,1.9400,0.9700,25.7000,5.8000,2.0100,1.0050,25.7000,5.7000,2.0100,1.0050,26,5.4000,1.9800,0.9900,25.4000,5.9000,2.0200,1.0100,25.5000,6.3000,1.8600,0.9300,26,45190,55,26.7000
3,Experiment 1,13/3/2024,5.9000,1.9700,0.9850,22,6,2.0200,1.0100,22,5.8000,2.0200,1.0100,22,5.5000,1.9600,0.9800,22,5.9000,2.0300,1.0150,22.4000,6.5000,1.8700,0.9350,23,NaN,NaN,NaN,NaN,6,2.0200,1.0100,22,5.8000,2.0100,1.0050,25.4000,5.7000,2,1,26,5.5000,1.9500,0.9750,25.3000,5.9000,2.0100,1.0050,25.4000,6.5000,1.8700,0.9350,26,NaN,NaN,NaN
4,Experiment 1,14/3/2024,6,1.9200,0.9600,26.6000,6,2,1,25.1000,5.8000,1.9900,0.9950,24,5.5000,1.9500,0.9750,25,5.9000,2,1,22.9000,6.4000,1.8200,0.9100,26.2000,NaN,NaN,NaN,NaN,6,1.9300,0.9650,26,6,2.0100,1.0050,24.8000,5.9000,1.9800,0.9900,25,5.6000,1.9500,0.9750,26,5.9000,2.0200,1.0100,25.6000,6.4000,1.8200,0.9100,28,NaN,NaN,NaN

**Last 5 rows:**

,experiment,date,100000_replicate_1_t1_ph,100000_replicate_1_t1_ec,100000_replicate_1_t1_tds,100000_replicate_1_t1_water_temp,100000_replicate_2_t1_ph,100000_replicate_2_t1_ec,100000_replicate_2_t1_tds,100000_replicate_2_t1_water_temp,100000_replicate_3_t1_ph,100000_replicate_3_t1_ec,100000_replicate_3_t1_tds,100000_replicate_3_t1_water_temp,100000_replicate_1_t2_ph,100000_replicate_1_t2_ec,100000_replicate_1_t2_tds,100000_replicate_1_t2_water_temp,100000_replicate_2_t2_ph,100000_replicate_2_t2_ec,100000_replicate_2_t2_tds,100000_replicate_2_t2_water_temp,100000_replicate_3_t2_ph,100000_replicate_3_t2_ec,100000_replicate_3_t2_tds,100000_replicate_3_t2_water_temp,100000_air_air_parameters,100000_rh%_col_26,100000_air_temp_col_27,100000_air_temp_col_28,140000_replicate_1_t1_ph,140000_replicate_1_t1_ec,140000_replicate_1_t1_tds,140000_replicate_1_t1_water_temp,140000_replicate_2_t1_ph,140000_replicate_2_t1_ec,140000_replicate_2_t1_tds,140000_replicate_2_t1_water_temp,140000_replicate_3_t1_ph,140000_replicate_3_t1_ec,140000_replicate_3_t1_tds,140000_replicate_3_t1_water_temp,140000_replicate_1_t2_ph,140000_replicate_1_t2_ec,140000_replicate_1_t2_tds,140000_replicate_1_t2_water_temp,140000_replicate_2_t2_ph,140000_replicate_2_t2_ec,140000_replicate_2_t2_tds,140000_replicate_2_t2_water_temp,140000_replicate_3_t2_ph,140000_replicate_3_t2_ec,140000_replicate_3_t2_tds,140000_replicate_3_t2_water_temp,140000_air_air_parameters,140000_rh%_col_54,140000_air_temp_col_55
28,Experiment 1,2024-07-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Experiment 1,2024-08-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54448.3333,57.1667,25.2167
32,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52900.7692,58.1000,24.3923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Column Names & Data Types:**

                              Column    Dtype  Non-Null Count  Null Count
0                         experiment      str              33           0
1                               date   object              30           3
2           100000_replicate_1_t1_ph   object              25           8
3           100000_replicate_1_t1_ec   object              25           8
4          100000_replicate_1_t1_tds   object              26           7
5   100000_replicate_1_t1_water_temp   object              25           8
6           100000_replicate_2_t1_ph   object              25           8
7           100000_replicate_2_t1_ec   object              25           8
8          100000_replicate_2_t1_tds   object              26           7
9   100000_replicate_2_t1_water_temp   object              25           8
10          100000_replicate_3_t1_ph   object              25           8
11          100000_replicate_3_t1_ec   object              25           8
12         100000_replicate_3_t1_tds   object              26           7
13  100000_replicate_3_t1_water_temp   object              25           8
14          100000_replicate_1_t2_ph   object              25           8
15          100000_replicate_1_t2_ec   object              25           8
16         100000_replicate_1_t2_tds   object              26           7
17  100000_replicate_1_t2_water_temp   object              25           8
18          100000_replicate_2_t2_ph   object              25           8
19          100000_replicate_2_t2_ec   object              25           8
20         100000_replicate_2_t2_tds   object              25           8
21  100000_replicate_2_t2_water_temp   object              25           8
22          100000_replicate_3_t2_ph   object              25           8
23          100000_replicate_3_t2_ec   object              25           8
24         100000_replicate_3_t2_tds   object              26           7
25  100000_replicate_3_t2_water_temp   object              25           8
26         100000_air_air_parameters   object              15          18
27                 100000_rh%_col_26   object              15          18
28            100000_air_temp_col_27   object              15          18
29            100000_air_temp_col_28  float64               0          33
30          140000_replicate_1_t1_ph   object              22          11
31          140000_replicate_1_t1_ec   object              22          11
32         140000_replicate_1_t1_tds   object              24           9
33  140000_replicate_1_t1_water_temp   object              22          11
34          140000_replicate_2_t1_ph   object              22          11
35          140000_replicate_2_t1_ec   object              22          11
36         140000_replicate_2_t1_tds   object              24           9
37  140000_replicate_2_t1_water_temp   object              22          11
38          140000_replicate_3_t1_ph   object              22          11
39          140000_replicate_3_t1_ec   object              22          11
40         140000_replicate_3_t1_tds   object              24           9
41  140000_replicate_3_t1_water_temp   object              22          11
42          140000_replicate_1_t2_ph   object              22          11
43          140000_replicate_1_t2_ec   object              22          11
44         140000_replicate_1_t2_tds   object              24           9
45  140000_replicate_1_t2_water_temp   object              22          11
46          140000_replicate_2_t2_ph   object              22          11
47          140000_replicate_2_t2_ec   object              22          11
48         140000_replicate_2_t2_tds   object              24           9
49  140000_replicate_2_t2_water_temp   object              22          11
50          140000_replicate_3_t2_ph   object              22          11
51          140000_replicate_3_t2_ec   object              22          11
52         140000_replicate_3_t2_tds   object              24           9
53  140000_replicate_3_t2_water_temp   object              22          11
54         140000_air_air_parameters   object               7          26
55                 140000_rh%_col_54   object               7          26
56            140000_air_temp_col_55   object               7          26

**Memory Usage:** `64.1` KB (`0.063` MB)

**Summary Statistics (numeric columns):**

       100000_air_temp_col_28
count                  0.0000
mean                      NaN
std                       NaN
min                       NaN
25%                       NaN
50%                       NaN
75%                       NaN
max                       NaN

──────────────────────────────────────────────────────────────────────

### Experiment 1 — nutrients_date

**Shape:** `24` rows × `2` columns

**First 5 rows:**

     experiment                 date
0  Experiment 1  2024-11-03 00:00:00
1  Experiment 1            20/3/2024
2  Experiment 1            29/3/2024
3  Experiment 1  2024-01-04 00:00:00
4  Experiment 1                  NaN

**Last 5 rows:**

      experiment    date
19  Experiment 1     NaN
20  Experiment 1     NaN
21  Experiment 1     NaN
22  Experiment 1     NaN
23  Experiment 1  Total

**Column Names & Data Types:**

       Column   Dtype  Non-Null Count  Null Count
0  experiment     str              24           0
1        date  object               5          19

**Memory Usage:** `2.4` KB (`0.002` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 1 — nutrients_nutrient_solution_addition_(a+b)_ml

**Shape:** `24` rows × `7` columns

**First 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
0,Experiment 1,115,136,136,136,136,136
1,Experiment 1,30,30,30,30,30,30
2,Experiment 1,0,0,0,0,0,136
3,Experiment 1,12,9,9,21,21,27
4,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN

**Last 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
19,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
20,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
21,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
22,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
23,Experiment 1,157,175,175,187,187,329

**Column Names & Data Types:**

           Column   Dtype  Non-Null Count  Null Count
0      experiment     str              24           0
1  Replicate_1_T1  object               5          19
2  Replicate_2_T1  object               5          19
3  Replicate_3_T1  object               5          19
4  Replicate_1_T2  object               5          19
5  Replicate_2_T2  object               5          19
6  Replicate_3_T2  object               5          19

**Memory Usage:** `6.2` KB (`0.006` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 1 — nutrients_acid_consumption_(ml)

**Shape:** `24` rows × `7` columns

**First 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
0,Experiment 1,20,20,20,20,20,20
1,Experiment 1,14,10,10,10,10,10
2,Experiment 1,5,5,5,5,5,5
3,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
4,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN

**Last 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
19,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
20,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
21,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
22,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
23,Experiment 1,39,35,35,35,35,35

**Column Names & Data Types:**

           Column   Dtype  Non-Null Count  Null Count
0      experiment     str              24           0
1  Replicate_1_T1  object               4          20
2  Replicate_2_T1  object               4          20
3  Replicate_3_T1  object               4          20
4  Replicate_1_T2  object               4          20
5  Replicate_2_T2  object               4          20
6  Replicate_3_T2  object               4          20

**Memory Usage:** `6.2` KB (`0.006` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 1 — nutrients_water_consumption_l

**Shape:** `24` rows × `7` columns

**First 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
0,Experiment 1,10,0,0,0,0,100
1,Experiment 1,10,10,10,10,15,10
2,Experiment 1,0,0,0,0,0,16
3,Experiment 1,15,15,15,15,15,15
4,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN

**Last 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
19,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
20,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
21,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
22,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN
23,Experiment 1,35,25,25,25,30,141

**Column Names & Data Types:**

           Column   Dtype  Non-Null Count  Null Count
0      experiment     str              24           0
1  Replicate_1_T1  object               5          19
2  Replicate_2_T1  object               5          19
3  Replicate_3_T1  object               5          19
4  Replicate_1_T2  object               5          19
5  Replicate_2_T2  object               5          19
6  Replicate_3_T2  object               5          19

**Memory Usage:** `6.2` KB (`0.006` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 1 — head_diameter

**Shape:** `300` rows × `5` columns

**First 5 rows:**

     experiment    replicate     day  plant_no head_diameter
0  Experiment 1  Replicate 1   day 3    1.0000           4*4
1  Experiment 1  Replicate 1   day 6    1.0000           5*5
2  Experiment 1  Replicate 1   Day 9    1.0000          9*12
3  Experiment 1  Replicate 1  Day 12    1.0000         11*12
4  Experiment 1  Replicate 1  Day 13    1.0000         16*17

**Last 5 rows:**

       experiment    replicate     day  plant_no head_diameter
295  Experiment 1  Replicate 6   day 3   10.0000         4*4.5
296  Experiment 1  Replicate 6   day 6       NaN           NaN
297  Experiment 1  Replicate 6   Day 9       NaN           NaN
298  Experiment 1  Replicate 6  Day 12       NaN           NaN
299  Experiment 1  Replicate 6  Day 13       NaN           NaN

**Column Names & Data Types:**

          Column    Dtype  Non-Null Count  Null Count
0     experiment      str             300           0
1      replicate      str             300           0
2            day      str             300           0
3       plant_no  float64             180         120
4  head_diameter   object             180         120

**Memory Usage:** `67.0` KB (`0.065` MB)

**Summary Statistics (numeric columns):**

       plant_no
count  180.0000
mean     3.8333
std      2.3458
min      1.0000
25%      2.0000
50%      3.5000
75%      5.0000
max     10.0000

──────────────────────────────────────────────────────────────────────

### Experiment 1 — harvest

**Shape:** `73` rows × `13` columns

**First 5 rows:**

,experiment,Plant No.,Total weight (g),Plant height (cm),Shoot length (cm),Root length (cm),Head diameter (cm),Stem diameter (cm),Shoot weight before removing wilted leaves (g),shoot weight after removing wilted leaves(g),Root weight (g),No. of leaves,system
0,Experiment 1,1.0000,243.0000,42.0000,13.5000,28.5000,24*27,1.7000,210.0000,208,33.0000,30.0000,R1-T1
1,Experiment 1,2.0000,241.0000,54.0000,10.5000,43.5000,27*27,2.0000,200.0000,189,41.0000,34.0000,R1-T1
2,Experiment 1,3.0000,251.0000,62.0000,13.5000,48.5000,26*26.5,2.0000,212.0000,208,39.0000,34.0000,R1-T1
3,Experiment 1,4.0000,200.0000,55.0000,13.5000,41.5000,26*26,2.0000,185.0000,183,15.0000,26.0000,R1-T1
4,Experiment 1,5.0000,200.0000,66.0000,14.0000,52.0000,29*26,2.0000,178.0000,174,22.0000,25.0000,R1-T1

**Last 5 rows:**

,experiment,Plant No.,Total weight (g),Plant height (cm),Shoot length (cm),Root length (cm),Head diameter (cm),Stem diameter (cm),Shoot weight before removing wilted leaves (g),shoot weight after removing wilted leaves(g),Root weight (g),No. of leaves,system
68,Experiment 1,9.0000,255.0000,49.0000,12.0000,37.0000,27*25,2.0000,221.0000,211,34.0000,40.0000,R2-T3
69,Experiment 1,10.0000,258.0000,53.0000,14.0000,39.0000,28*28,2.0000,225.0000,219,33.0000,34.0000,R2-T3
70,Experiment 1,11.0000,214.0000,58.0000,12.0000,46.0000,28*26,2.0000,209.0000,204,5.0000,32.0000,R2-T3
71,Experiment 1,12.0000,276.0000,57.0000,13.0000,44.0000,28*30,2.0000,246.0000,234,30.0000,32.0000,R2-T3
72,Experiment 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,R2-T3

**Column Names & Data Types:**

,Column,Dtype,Non-Null Count,Null Count
0,experiment,str,73,0
1,Plant No.,float64,72,1
2,Total weight (g),float64,72,1
3,Plant height (cm),float64,72,1
4,Shoot length (cm),float64,72,1
5,Root length (cm),float64,72,1
6,Head diameter (cm),str,72,1
7,Stem diameter (cm),float64,72,1
8,Shoot weight before removing wilted ...,float64,72,1
9,shoot weight after removing wilted l...,int64,73,0
10,Root weight (g),float64,72,1
11,No. of leaves,float64,72,1
12,system,str,73,0

**Memory Usage:** `17.9` KB (`0.017` MB)

**Summary Statistics (numeric columns):**

,Plant No.,Total weight (g),Plant height (cm),Shoot length (cm),Root length (cm),Stem diameter (cm),Shoot weight before removing wilted leaves (g),shoot weight after removing wilted leaves(g),Root weight (g),No. of leaves
count,72.0000,72.0000,72.0000,72.0000,72.0000,72.0000,72.0000,73.0000,72.0000,72.0000
mean,6.5000,239.4167,56.8333,13.2500,43.5833,1.9111,201.8889,191.9178,37.5278,28.0278
std,3.4763,31.1357,7.3580,1.6186,6.8010,0.2011,29.1888,36.8728,22.6181,6.4807
min,1.0000,150.0000,23.0000,10.0000,13.0000,1.4000,111.0000,4.0000,5.0000,18.0000
25%,3.7500,217.7500,54.0000,12.0000,40.0000,2.0000,181.5000,173.0000,24.0000,23.0000
50%,6.5000,241.0000,57.0000,13.0000,43.5000,2.0000,206.5000,200.0000,33.0000,26.0000
75%,9.2500,259.0000,61.2500,14.0000,48.1250,2.0000,220.2500,212.0000,41.0000,32.5000
max,12.0000,305.0000,71.0000,19.0000,58.5000,2.3000,265.0000,260.0000,129.0000,46.0000

──────────────────────────────────────────────────────────────────────

## 📂 Experiment 2

---

### Experiment 2 — seedlings

**Shape:** `12` rows × `12` columns

**First 5 rows:**

,experiment,Date,plant NO.,plant height (cm),shoot length (cm),root length (cm),head diameter (cm),stem diameter (cm),total weight (g),shoot weight (g),root weight (g),no. of leaves
0,Experiment 2,NaN,1,11,5,6,7*8,0.3000,5.1300,2.4100,2.7200,7
1,Experiment 2,NaN,2,13,7,6,6*7,0.3000,5,2.1400,2.8600,7
2,Experiment 2,NaN,3,12.5000,5,7.5000,5*6,0.3000,5.2500,1.5800,3.6700,5
3,Experiment 2,NaN,4,13,7,6,7*8,0.3000,4.8500,2.4500,2.4000,7
4,Experiment 2,NaN,5,12,6,6,6*4,0.2000,5.3600,1.9300,3.4300,7

**Last 5 rows:**

,experiment,Date,plant NO.,plant height (cm),shoot length (cm),root length (cm),head diameter (cm),stem diameter (cm),total weight (g),shoot weight (g),root weight (g),no. of leaves
7,Experiment 2,NaN,8,13,7,6,6.5*5,0.2000,3.6700,1.8800,1.7900,6
8,Experiment 2,NaN,9,12,6,6,6*5,0.3000,4.9200,1.8900,3.0300,8
9,Experiment 2,NaN,10,14,6,8,7*5,0.3000,4.5300,2.2100,2.3200,6
10,Experiment 2,NaN,11,14,8,6,7*6,0.3000,4.9800,2.3600,2.6200,6
11,Experiment 2,NaN,12,13,6,7,6.5*4,0.3000,5.3300,2.1300,3.2000,7

**Column Names & Data Types:**

                 Column   Dtype  Non-Null Count  Null Count
0            experiment     str              12           0
1                  Date     str               0          12
2             plant NO.  object              12           0
3    plant height  (cm)  object              12           0
4     shoot length (cm)  object              12           0
5      root length (cm)  object              12           0
6    head diameter (cm)     str              12           0
7   stem diameter  (cm)  object              12           0
8      total weight (g)  object              12           0
9      shoot weight (g)  object              12           0
10      root weight (g)  object              12           0
11        no. of leaves  object              12           0

**Memory Usage:** `5.4` KB (`0.005` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 2 — sensor_water_quality

**Shape:** `718` rows × `13` columns

**First 5 rows:**

,experiment,replicate,Date,Tme,pH.,EC.,TDS.,Water temp.,Date_1,Tme_1,RH%,Air temp.,CO2
0,Experiment 2,Replicate 1 T1,,NaN,NaN,NaN,NaN,NaN,2024-04-16 00:00:00,10:00:00,57.7700,28.2800,485.7000
1,Experiment 2,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-16 00:00:00,11:00:00,54,28.5700,463.9200
2,Experiment 2,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-16 00:00:00,12:00:00,52.8900,27.6800,450.5100
3,Experiment 2,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-16 00:00:00,13:00:00,52.0100,28.2900,444.8800
4,Experiment 2,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-16 00:00:00,14:00:00,52.4600,27.3200,440.1300

**Last 5 rows:**

,experiment,replicate,Date,Tme,pH.,EC.,TDS.,Water temp.,Date_1,Tme_1,RH%,Air temp.,CO2
713,Experiment 2,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-17 00:00:00,10:00:00,55.7400,27.2800,445.1100
714,Experiment 2,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-17 00:00:00,11:00:00,54.2400,25.3500,436.0900
715,Experiment 2,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-17 00:00:00,12:00:00,53.7600,25.2000,433.1800
716,Experiment 2,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-17 00:00:00,13:00:00,53.2800,25.2700,434.1800
717,Experiment 2,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-17 00:00:00,14:00:00,53.3300,25.4500,431.4100

**Column Names & Data Types:**

         Column   Dtype  Non-Null Count  Null Count
0    experiment     str             718           0
1     replicate     str             718           0
2          Date     str               1         717
3           Tme     str               0         718
4           pH.     str               0         718
5           EC.     str               0         718
6          TDS.     str               0         718
7   Water temp.     str               0         718
8        Date_1  object             718           0
9         Tme_1  object             718           0
10          RH%  object             718           0
11    Air temp.  object             718           0
12          CO2  object             718           0

**Memory Usage:** `362.0` KB (`0.354` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 2 — portable_water_quality

**Shape:** `29` rows × `57` columns

**First 5 rows:**

,experiment,date,100000_replicate_1_t1_ph,100000_replicate_1_t1_ec,100000_replicate_1_t1_tds,100000_replicate_1_t1_water_temp,100000_replicate_2_t1_ph,100000_replicate_2_t1_ec,100000_replicate_2_t1_tds,100000_replicate_2_t1_water_temp,100000_replicate_3_t1_ph,100000_replicate_3_t1_ec,100000_replicate_3_t1_tds,100000_replicate_3_t1_water_temp,100000_replicate_1_t2_ph,100000_replicate_1_t2_ec,100000_replicate_1_t2_tds,100000_replicate_1_t2_water_temp,100000_replicate_2_t2_ph,100000_replicate_2_t2_ec,100000_replicate_2_t2_tds,100000_replicate_2_t2_water_temp,100000_replicate_3_t2_ph,100000_replicate_3_t2_ec,100000_replicate_3_t2_tds,100000_replicate_3_t2_water_temp,100000_air_air_parameters,100000_air_temp_col_26,100000_rh_%_col_27,100000_rh_%_col_28,140000_replicate_1_t1_ph,140000_replicate_1_t1_ec,140000_replicate_1_t1_tds,140000_replicate_1_t1_water_temp,140000_replicate_2_t1_ph,140000_replicate_2_t1_ec,140000_replicate_2_t1_tds,140000_replicate_2_t1_water_temp,140000_replicate_3_t1_ph,140000_replicate_3_t1_ec,140000_replicate_3_t1_tds,140000_replicate_3_t1_water_temp,140000_replicate_1_t2_ph,140000_replicate_1_t2_ec,140000_replicate_1_t2_tds,140000_replicate_1_t2_water_temp,140000_replicate_2_t2_ph,140000_replicate_2_t2_ec,140000_replicate_2_t2_tds,140000_replicate_2_t2_water_temp,140000_replicate_3_t2_ph,140000_replicate_3_t2_ec,140000_replicate_3_t2_tds,140000_replicate_3_t2_water_temp,140000_air_air_parameters,140000_rh%_col_54,140000_air_temp_col_55
0,Experiment 2,16/4/2024,6.8000,1.4400,0.7200,25,7,1.3300,0.6650,25.2000,7,1.3300,0.6650,24.3000,6.9000,1.8900,0.9450,25,7,1.9500,0.9750,26,6.9000,1.8000,0.9000,25.3000,7750,26.9000,63.5000,NaN,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
1,Experiment 2,17/4/2024,6.3000,1.4800,0.7400,28.3000,6.7000,1.3700,0.6850,27.4000,6.3000,1.3700,0.6850,26.4000,6.2000,1.9100,0.9550,26.9000,6,1.9100,0.9550,26.9000,6.1000,1.9000,0.9500,28.4000,-,-,-,NaN,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
2,Experiment 2,18/4/2024,6.6000,1.7200,0.8600,25.3000,6.7000,1.7100,0.8550,25.8000,6.8000,1.7300,0.8650,24.8000,6.7000,2.1700,1.0850,25,6.5000,2.2700,1.1350,24.9000,6.3000,2.2200,1.1100,25.6000,-,-,-,NaN,6.8000,1.7500,0.8750,25.8000,6.7000,1.7500,0.8750,25.8000,6.8000,1.7200,0.8600,25.8000,6.7000,2.1700,1.0850,26,6.5000,2.2700,1.1350,25.8000,6.3000,2.2000,1.1000,26.6000,-,-,-
3,Experiment 2,19/4/2024,6.3000,1.7800,0.8900,24.7000,6.2000,1.7900,0.8950,25,6.3000,1.7500,0.8750,24.3000,6.1000,2.2200,1.1100,24.6000,6,2.3000,1.1500,24.9000,5.8000,2.2700,1.1350,25.8000,-,-,-,NaN,6.1000,1.8000,0.9000,27.8000,5.9000,1.7600,0.8800,27.6000,6.3000,1.7500,0.8750,28.2000,6.2000,2.2100,1.1050,28.3000,6.1000,2.2300,1.1150,28.6000,6.9000,2.2500,1.1250,27.6000,-,-,-
4,Experiment 2,20/4/2024,5.9000,1.7900,0.8950,22.8000,5.8000,1.7500,0.8750,24,5.6000,1.7800,0.8900,24.6000,5.8000,2.2200,1.1100,25.2000,6.5000,2.2400,1.1200,24,6.7000,2.2500,1.1250,24.7000,-,-,-,NaN,6.1000,1.7900,0.8950,28.3000,5.9000,1.7400,0.8700,27.8000,5.8000,1.7800,0.8900,27.6000,5.7000,2.3000,1.1500,25.8000,6,2.2300,1.1150,27,5.7000,2.2600,1.1300,27.8000,-,-,-

**Last 5 rows:**

,experiment,date,100000_replicate_1_t1_ph,100000_replicate_1_t1_ec,100000_replicate_1_t1_tds,100000_replicate_1_t1_water_temp,100000_replicate_2_t1_ph,100000_replicate_2_t1_ec,100000_replicate_2_t1_tds,100000_replicate_2_t1_water_temp,100000_replicate_3_t1_ph,100000_replicate_3_t1_ec,100000_replicate_3_t1_tds,100000_replicate_3_t1_water_temp,100000_replicate_1_t2_ph,100000_replicate_1_t2_ec,100000_replicate_1_t2_tds,100000_replicate_1_t2_water_temp,100000_replicate_2_t2_ph,100000_replicate_2_t2_ec,100000_replicate_2_t2_tds,100000_replicate_2_t2_water_temp,100000_replicate_3_t2_ph,100000_replicate_3_t2_ec,100000_replicate_3_t2_tds,100000_replicate_3_t2_water_temp,100000_air_air_parameters,100000_air_temp_col_26,100000_rh_%_col_27,100000_rh_%_col_28,140000_replicate_1_t1_ph,140000_replicate_1_t1_ec,140000_replicate_1_t1_tds,140000_replicate_1_t1_water_temp,140000_replicate_2_t1_ph,140000_replicate_2_t1_ec,140000_replicate_2_t1_tds,140000_replicate_2_t1_water_temp,140000_replicate_3_t1_ph,140000_replicate_3_t1_ec,140000_replicate_3_t1_tds,140000_replicate_3_t1_water_temp,140000_replicate_1_t2_ph,140000_replicate_1_t2_ec,140000_replicate_1_t2_tds,140000_replicate_1_t2_water_temp,140000_replicate_2_t2_ph,140000_replicate_2_t2_ec,140000_replicate_2_t2_tds,140000_replicate_2_t2_water_temp,140000_replicate_3_t2_ph,140000_replicate_3_t2_ec,140000_replicate_3_t2_tds,140000_replicate_3_t2_water_temp,140000_air_air_parameters,140000_rh%_col_54,140000_air_temp_col_55
24,Experiment 2,2024-10-05 00:00:00,6.5000,1.7800,0.8900,18.9000,6.4000,1.7800,0.8900,18.6000,6.4000,1.9200,0.9600,18.1000,6.4000,2.3600,1.1800,18.1000,6.5000,2.4000,1.2000,17.8000,6.5000,2.1800,1.0900,19,23500,23.6000,59.3000,NaN,6.6000,1.7400,0.8700,21.5000,6.6000,1.6500,0.8250,20.8000,6.5000,1.8700,0.9350,20.5000,6.6000,26.7000,13.3500,20.6000,6.6000,2.3100,1.1550,20.2000,6.7000,1.9800,0.9900,21.5000,22800,27.3000,60.1000
25,Experiment 2,2024-11-05 00:00:00,6.5000,1.7900,0.8950,18.8000,6.5000,1.7800,0.8900,18.5000,6.5000,1.9000,0.9500,18.3000,6.5000,2.3000,1.1500,18,6.6000,2.4200,1.2100,17.6000,6.4000,2.1400,1.0700,18.6000,25030,24.8000,70.5000,NaN,6.5000,1.7400,0.8700,23.1000,6.4000,1.7600,0.8800,22.9000,6.4000,1.8600,0.9300,21.6000,6.5000,2.2000,1.1000,21.1000,6.5000,2.2100,1.1050,21.5000,6.6000,1.9800,0.9900,22,37870,30.9000,49.2000
26,Experiment 2,2024-12-05 00:00:00,7.1000,1.7500,0.8750,19.8000,7,1.6400,0.8200,19.4000,6.9000,1.7700,0.8850,19,6.9000,2.1900,1.0950,19.3000,6.8000,2.2300,1.1150,18.9000,6.9000,1.9300,0.9650,20.4000,33100,29.9000,56.6000,NaN,7.1000,1.7600,0.8800,22.5000,6.9000,1.6600,0.8300,25,6.7000,1.7500,0.8750,20.8000,6.9000,2.2200,1.1100,20.5000,6.8000,2.2500,1.1250,20.4000,6.9000,1.9500,0.9750,21.2000,3090,28.5000,59.7000
27,Experiment 2,13/4/2024,6.8000,1.8600,0.9300,18.5000,6.7000,1.6600,0.8300,18.8000,6.7000,1.9300,0.9650,18,6.6000,2.4600,1.2300,18.3000,7.1000,2.5600,1.2800,18.5000,7,2.1000,1.0500,19,26660,24.6000,69,NaN,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN
28,Experiment 2,14/4/2024,7,1.8700,0.9350,18.6000,7,1.6700,0.8350,18.3000,6.8000,1.9000,0.9500,18.1000,6.8000,1.9000,0.9500,18.1000,6.7000,2.2600,1.1300,17.9000,6.9000,2.1300,1.0650,19.2000,2554,30,59.4000,NaN,6.9000,1.8800,0.9400,21.7000,7,1.7400,0.8700,21,7.1000,1.9500,0.9750,20.6000,7.1000,2.2000,1.1000,20.7000,7.2000,2.5000,1.2500,20,7.1000,2.2000,1.1000,21.2000,12720,25.3000,64.2000

**Column Names & Data Types:**

                              Column    Dtype  Non-Null Count  Null Count
0                         experiment      str              29           0
1                               date   object              29           0
2           100000_replicate_1_t1_ph   object              29           0
3           100000_replicate_1_t1_ec   object              29           0
4          100000_replicate_1_t1_tds   object              29           0
5   100000_replicate_1_t1_water_temp   object              29           0
6           100000_replicate_2_t1_ph   object              29           0
7           100000_replicate_2_t1_ec   object              29           0
8          100000_replicate_2_t1_tds   object              29           0
9   100000_replicate_2_t1_water_temp   object              29           0
10          100000_replicate_3_t1_ph   object              29           0
11          100000_replicate_3_t1_ec   object              29           0
12         100000_replicate_3_t1_tds   object              29           0
13  100000_replicate_3_t1_water_temp   object              29           0
14          100000_replicate_1_t2_ph   object              29           0
15          100000_replicate_1_t2_ec   object              29           0
16         100000_replicate_1_t2_tds   object              29           0
17  100000_replicate_1_t2_water_temp   object              29           0
18          100000_replicate_2_t2_ph   object              29           0
19          100000_replicate_2_t2_ec   object              29           0
20         100000_replicate_2_t2_tds   object              29           0
21  100000_replicate_2_t2_water_temp   object              29           0
22          100000_replicate_3_t2_ph   object              29           0
23          100000_replicate_3_t2_ec   object              29           0
24         100000_replicate_3_t2_tds   object              29           0
25  100000_replicate_3_t2_water_temp   object              29           0
26         100000_air_air_parameters   object              29           0
27            100000_air_temp_col_26   object              29           0
28                100000_rh_%_col_27   object              29           0
29                100000_rh_%_col_28  float64               0          29
30          140000_replicate_1_t1_ph   object              29           0
31          140000_replicate_1_t1_ec   object              29           0
32         140000_replicate_1_t1_tds   object              29           0
33  140000_replicate_1_t1_water_temp   object              29           0
34          140000_replicate_2_t1_ph   object              29           0
35          140000_replicate_2_t1_ec   object              29           0
36         140000_replicate_2_t1_tds   object              29           0
37  140000_replicate_2_t1_water_temp   object              29           0
38          140000_replicate_3_t1_ph   object              29           0
39          140000_replicate_3_t1_ec   object              29           0
40         140000_replicate_3_t1_tds   object              29           0
41  140000_replicate_3_t1_water_temp   object              29           0
42          140000_replicate_1_t2_ph   object              29           0
43          140000_replicate_1_t2_ec   object              29           0
44         140000_replicate_1_t2_tds   object              29           0
45  140000_replicate_1_t2_water_temp   object              29           0
46          140000_replicate_2_t2_ph   object              29           0
47          140000_replicate_2_t2_ec   object              29           0
48         140000_replicate_2_t2_tds   object              29           0
49  140000_replicate_2_t2_water_temp   object              29           0
50          140000_replicate_3_t2_ph   object              29           0
51          140000_replicate_3_t2_ec   object              29           0
52         140000_replicate_3_t2_tds   object              29           0
53  140000_replicate_3_t2_water_temp   object              29           0
54         140000_air_air_parameters   object              28           1
55                 140000_rh%_col_54   object              28           1
56            140000_air_temp_col_55   object              28           1

**Memory Usage:** `55.6` KB (`0.054` MB)

**Summary Statistics (numeric columns):**

       100000_rh_%_col_28
count              0.0000
mean                  NaN
std                   NaN
min                   NaN
25%                   NaN
50%                   NaN
75%                   NaN
max                   NaN

──────────────────────────────────────────────────────────────────────

### Experiment 2 — nutrients_date

**Shape:** `24` rows × `2` columns

**First 5 rows:**

     experiment                 date
0  Experiment 2  2024-02-05 00:00:00
1  Experiment 2                  NaN
2  Experiment 2                  NaN
3  Experiment 2                  NaN
4  Experiment 2                  NaN

**Last 5 rows:**

      experiment    date
19  Experiment 2     NaN
20  Experiment 2     NaN
21  Experiment 2     NaN
22  Experiment 2     NaN
23  Experiment 2  Total

**Column Names & Data Types:**

       Column   Dtype  Non-Null Count  Null Count
0  experiment     str              24           0
1        date  object               2          22

**Memory Usage:** `2.4` KB (`0.002` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 2 — nutrients_nutrient_solution_addition_(a+b)_ml

**Shape:** `24` rows × `7` columns

**First 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
0,Experiment 2,22,22,22,22,22,22
1,Experiment 2,15,10,10,10,10,25
2,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
3,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
4,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN

**Last 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
19,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
20,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
21,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
22,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
23,Experiment 2,37,32,32,32,32,47

**Column Names & Data Types:**

           Column   Dtype  Non-Null Count  Null Count
0      experiment     str              24           0
1  Replicate_1_T1  object               3          21
2  Replicate_2_T1  object               3          21
3  Replicate_3_T1  object               3          21
4  Replicate_1_T2  object               3          21
5  Replicate_2_T2  object               3          21
6  Replicate_3_T2  object               3          21

**Memory Usage:** `6.1` KB (`0.006` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 2 — nutrients_water_consumption_l

**Shape:** `24` rows × `7` columns

**First 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
0,Experiment 2,40,40,35,40,40,30
1,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
2,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
3,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
4,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN

**Last 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
19,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
20,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
21,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
22,Experiment 2,NaN,NaN,NaN,NaN,NaN,NaN
23,Experiment 2,40,40,35,40,40,30

**Column Names & Data Types:**

           Column   Dtype  Non-Null Count  Null Count
0      experiment     str              24           0
1  Replicate_1_T1  object               2          22
2  Replicate_2_T1  object               2          22
3  Replicate_3_T1  object               2          22
4  Replicate_1_T2  object               2          22
5  Replicate_2_T2  object               2          22
6  Replicate_3_T2  object               2          22

**Memory Usage:** `6.1` KB (`0.006` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 2 — harvest

**Shape:** `78` rows × `13` columns

**First 5 rows:**

,experiment,Plant No.,Total weight (g),Plant height (cm),Shoot length (cm),Root length (cm),Head diameter (cm),Stem diameter (cm),Shoot weight before removing wilted leaves (g),shoot weight after removing wilted leaves(g),Root weight (g),No. of leaves,system
0,Experiment 2,1.0000,317.0000,55.0000,15.0000,40.0000,25*26,2.0000,272.0000,264.0000,45.0000,37.0000,R1-T1
1,Experiment 2,2.0000,270.0000,50.0000,16.0000,34.0000,30*25,2.0000,248.0000,239.0000,22.0000,29.0000,R1-T1
2,Experiment 2,3.0000,311.0000,52.0000,14.0000,38.0000,29*30,2.0000,292.0000,283.0000,19.0000,38.0000,R1-T1
3,Experiment 2,4.0000,360.0000,70.0000,17.0000,53.0000,30*31,2.5000,300.0000,293.0000,60.0000,37.0000,R1-T1
4,Experiment 2,5.0000,326.0000,67.0000,19.0000,48.0000,27*30,2.1000,300.0000,300.0000,26.0000,34.0000,R1-T1

**Last 5 rows:**

,experiment,Plant No.,Total weight (g),Plant height (cm),Shoot length (cm),Root length (cm),Head diameter (cm),Stem diameter (cm),Shoot weight before removing wilted leaves (g),shoot weight after removing wilted leaves(g),Root weight (g),No. of leaves,system
73,Experiment 2,9.0000,313.0000,62.0000,18.0000,44.0000,30*30,2.0000,271.0000,270.0000,42.0000,42.0000,R3-T2
74,Experiment 2,10.0000,348.0000,64.0000,19.0000,45.0000,28*28,2.0000,312.0000,312.0000,36.0000,38.0000,R3-T2
75,Experiment 2,11.0000,321.0000,52.0000,17.0000,35.0000,29*26,2.0000,281.0000,281.0000,40.0000,43.0000,R3-T2
76,Experiment 2,12.0000,300.0000,70.0000,16.0000,54.0000,27*25,2.0000,264.0000,264.0000,36.0000,43.0000,R3-T2
77,Experiment 2,NaN,339.5833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R3-T2

**Column Names & Data Types:**

,Column,Dtype,Non-Null Count,Null Count
0,experiment,str,78,0
1,Plant No.,float64,72,6
2,Total weight (g),float64,78,0
3,Plant height (cm),float64,72,6
4,Shoot length (cm),float64,72,6
5,Root length (cm),float64,72,6
6,Head diameter (cm),str,72,6
7,Stem diameter (cm),float64,72,6
8,Shoot weight before removing wilted ...,float64,72,6
9,shoot weight after removing wilted l...,float64,72,6
10,Root weight (g),float64,72,6
11,No. of leaves,float64,72,6
12,system,str,78,0

**Memory Usage:** `19.0` KB (`0.019` MB)

**Summary Statistics (numeric columns):**

,Plant No.,Total weight (g),Plant height (cm),Shoot length (cm),Root length (cm),Stem diameter (cm),Shoot weight before removing wilted leaves (g),shoot weight after removing wilted leaves(g),Root weight (g),No. of leaves
count,72.0000,78.0000,72.0000,72.0000,72.0000,72.0000,72.0000,72.0000,72.0000,72.0000
mean,6.5000,327.7917,61.9167,18.5347,43.3819,2.0097,290.7500,288.0556,37.0417,41.5833
std,3.4763,42.1966,7.8986,1.7428,7.4812,0.1235,40.6825,40.8315,9.2955,4.5710
min,1.0000,218.0000,43.0000,14.0000,25.0000,1.5000,184.0000,180.0000,18.0000,29.0000
25%,3.7500,300.5000,56.0000,17.3750,38.3750,2.0000,265.7500,264.0000,30.0000,38.7500
50%,6.5000,327.0000,63.0000,19.0000,44.2500,2.0000,290.0000,284.0000,38.0000,42.0000
75%,9.2500,362.5000,67.0000,20.0000,48.0000,2.0000,318.5000,319.2500,43.0000,44.2500
max,12.0000,412.0000,80.0000,22.0000,61.0000,2.5000,368.0000,364.0000,70.0000,52.0000

──────────────────────────────────────────────────────────────────────

### Experiment 2 — taste_test

**Shape:** `7` rows × `25` columns

**First 5 rows:**

,experiment,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
0,Experiment 2,NaN,R1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Experiment 2,Timestamp,Age,Gender,Smell (الرائحة),Appearance (المظهر),Flavor (الطعم),Crunchy (مقرمش),Sweetness (الحلاوة ),Bitter (المرارة),Color (اللون),After taste (المذاق الأخير),Acceptance,Overall evaluation (The best),Comments,Smell (الرائحة),Appearance (المظهر),Flavor (الطعم),Crunchy (مقرمش),Sweetness (الحلاوة ),Bitter (المرارة),Color (اللون),After taste (المذاق الأخير),Acceptance,Overall evaluation (The best)
2,Experiment 2,2024-05-15 16:28:34.895000,22,Male,Fresh,9,8,9,5 (Extremely sweet ),5 (Extremely Bitter ),5,9,9,10 (like extremely ),NaN,Fresh,9,9,9,5 (Extremely sweet ),5 (Extremely Bitter ),5,10 (like extremely ),10 (like extremely ),9
3,Experiment 2,2024-05-15 16:30:37.820000,26,Male,Normal,6,8,8,4,2,4,8,8,8,NaN,Normal,9,9,9,5 (Extremely sweet ),1 (Not at all bitter),4,10 (like extremely ),10 (like extremely ),10 (like extremely )
4,Experiment 2,2024-05-15 16:33:12.614000,31,Female,Normal,7,6,7,4,1 (Not at all bitter),4,8,8,8,NaN,Normal,7,7,7,3,1 (Not at all bitter),4,7,7,7

**Last 5 rows:**

,experiment,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
2,Experiment 2,2024-05-15 16:28:34.895000,22,Male,Fresh,9,8,9,5 (Extremely sweet ),5 (Extremely Bitter ),5,9,9,10 (like extremely ),NaN,Fresh,9,9,9,5 (Extremely sweet ),5 (Extremely Bitter ),5,10 (like extremely ),10 (like extremely ),9
3,Experiment 2,2024-05-15 16:30:37.820000,26,Male,Normal,6,8,8,4,2,4,8,8,8,NaN,Normal,9,9,9,5 (Extremely sweet ),1 (Not at all bitter),4,10 (like extremely ),10 (like extremely ),10 (like extremely )
4,Experiment 2,2024-05-15 16:33:12.614000,31,Female,Normal,7,6,7,4,1 (Not at all bitter),4,8,8,8,NaN,Normal,7,7,7,3,1 (Not at all bitter),4,7,7,7
5,Experiment 2,2024-05-15 16:33:33.060000,28,Male,Normal,6,6,5,3,3,3,5,6,6,NaN,Normal,8,8,7,4,1 (Not at all bitter),4,7,8,8
6,Experiment 2,2024-05-15 17:12:17.188000,30,Male,Fresh,10 (like extremely ),9,8,4,1 (Not at all bitter),5,9,10 (like extremely ),10 (like extremely ),NaN,Fresh,10 (like extremely ),7,9,3,2,5,8,9,8

**Column Names & Data Types:**

        Column   Dtype  Non-Null Count  Null Count
0   experiment     str               7           0
1            0  object               6           1
2            1  object               7           0
3            2     str               6           1
4            3     str               6           1
5            4  object               6           1
6            5  object               6           1
7            6  object               6           1
8            7  object               6           1
9            8  object               6           1
10           9  object               6           1
11          10  object               6           1
12          11  object               6           1
13          12  object               6           1
14          13     str               1           6
15          14     str               7           0
16          15  object               6           1
17          16  object               6           1
18          17  object               6           1
19          18  object               6           1
20          19  object               6           1
21          20  object               6           1
22          21  object               6           1
23          22  object               6           1
24          23  object               6           1

**Memory Usage:** `8.6` KB (`0.008` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 2 — form_responses

**Shape:** `7` rows × `26` columns

**First 5 rows:**

,experiment,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24
0,Experiment 2,NaN,R1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Experiment 2,Timestamp,Age,Gender,Smell (الرائحة),Appearance (المظهر),Flavor (الطعم),Crunchy (مقرمش),Sweetness (الحلاوة ),Bitter (المرارة),Color (اللون),After taste (المذاق الأخير),Acceptance,Overall evaluation (The best),Comments,Smell (الرائحة),Appearance (المظهر),Flavor (الطعم),Crunchy (مقرمش),Sweetness (الحلاوة ),Bitter (المرارة),Color (اللون),After taste (المذاق الأخير),Acceptance,Overall evaluation (The best),Comments
2,Experiment 2,2024-05-15 16:28:34.895000,22,Male,Fresh,9,8,9,5 (Extremely sweet ),5 (Extremely Bitter ),5,9,9,10 (like extremely ),NaN,Fresh,9,9,9,5 (Extremely sweet ),5 (Extremely Bitter ),5,10 (like extremely ),10 (like extremely ),9,NaN
3,Experiment 2,2024-05-15 16:30:37.820000,26,Male,Normal,6,8,8,4,2,4,8,8,8,NaN,Normal,9,9,9,5 (Extremely sweet ),1 (Not at all bitter),4,10 (like extremely ),10 (like extremely ),10 (like extremely ),NaN
4,Experiment 2,2024-05-15 16:33:12.614000,31,Female,Normal,7,6,7,4,1 (Not at all bitter),4,8,8,8,NaN,Normal,7,7,7,3,1 (Not at all bitter),4,7,7,7,NaN

**Last 5 rows:**

,experiment,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24
2,Experiment 2,2024-05-15 16:28:34.895000,22,Male,Fresh,9,8,9,5 (Extremely sweet ),5 (Extremely Bitter ),5,9,9,10 (like extremely ),NaN,Fresh,9,9,9,5 (Extremely sweet ),5 (Extremely Bitter ),5,10 (like extremely ),10 (like extremely ),9,NaN
3,Experiment 2,2024-05-15 16:30:37.820000,26,Male,Normal,6,8,8,4,2,4,8,8,8,NaN,Normal,9,9,9,5 (Extremely sweet ),1 (Not at all bitter),4,10 (like extremely ),10 (like extremely ),10 (like extremely ),NaN
4,Experiment 2,2024-05-15 16:33:12.614000,31,Female,Normal,7,6,7,4,1 (Not at all bitter),4,8,8,8,NaN,Normal,7,7,7,3,1 (Not at all bitter),4,7,7,7,NaN
5,Experiment 2,2024-05-15 16:33:33.060000,28,Male,Normal,6,6,5,3,3,3,5,6,6,NaN,Normal,8,8,7,4,1 (Not at all bitter),4,7,8,8,NaN
6,Experiment 2,2024-05-15 17:12:17.188000,30,Male,Fresh,10 (like extremely ),9,8,4,1 (Not at all bitter),5,9,10 (like extremely ),10 (like extremely ),NaN,Fresh,10 (like extremely ),7,9,3,2,5,8,9,8,NaN

**Column Names & Data Types:**

        Column   Dtype  Non-Null Count  Null Count
0   experiment     str               7           0
1            0  object               6           1
2            1  object               7           0
3            2     str               6           1
4            3     str               6           1
5            4  object               6           1
6            5  object               6           1
7            6  object               6           1
8            7  object               6           1
9            8  object               6           1
10           9  object               6           1
11          10  object               6           1
12          11  object               6           1
13          12  object               6           1
14          13     str               1           6
15          14     str               7           0
16          15  object               6           1
17          16  object               6           1
18          17  object               6           1
19          18  object               6           1
20          19  object               6           1
21          20  object               6           1
22          21  object               6           1
23          22  object               6           1
24          23  object               6           1
25          24     str               1           6

**Memory Usage:** `8.9` KB (`0.009` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

## 📂 Experiment 3

---

### Experiment 3 — seedlings

**Shape:** `10` rows × `11` columns

**First 5 rows:**

,experiment,Plant NO.,Plant height (cm),Shoot length (cm),Root length (cm),Head diameter (cm),Stem diameter (cm),Total weight (g),Shoot weight (g),Root weight (g),No. of leaves
0,Experiment 3,1,16.5000,8,8.5000,9*5,0.3000,6,4,2,12
1,Experiment 3,2,15,7,8,8*5,0.3000,5,3,2,12
2,Experiment 3,3,16,8,8,10*9,0.4000,6,3,3,12
3,Experiment 3,4,12.5000,6,6.5000,6.5*6,0.4000,5,4,1,10
4,Experiment 3,5,13.5000,6,7.5000,6.5*6.5,0.3000,4,3,1,11

**Last 5 rows:**

,experiment,Plant NO.,Plant height (cm),Shoot length (cm),Root length (cm),Head diameter (cm),Stem diameter (cm),Total weight (g),Shoot weight (g),Root weight (g),No. of leaves
5,Experiment 3,6,14.5000,5.5000,9,6.5*5.5,0.3000,5,3,2,11
6,Experiment 3,7,13,5.5000,7.5000,5.5*5,0.4000,5,3,2,10
7,Experiment 3,8,14.5000,5.5000,9,6.5*4.5,0.3000,4,2,2,10
8,Experiment 3,9,16,6,10,6*7,0.3000,4,3,1,12
9,Experiment 3,10,13,5.5000,7.5000,7*5.5,0.4000,4,2,2,13

**Column Names & Data Types:**

                 Column   Dtype  Non-Null Count  Null Count
0            experiment     str              10           0
1             Plant NO.  object              10           0
2    Plant height  (cm)  object              10           0
3     Shoot length (cm)  object              10           0
4      Root length (cm)  object              10           0
5    Head diameter (cm)     str              10           0
6   Stem diameter  (cm)  object              10           0
7      Total weight (g)  object              10           0
8      Shoot weight (g)  object              10           0
9       Root weight (g)  object              10           0
10        No. of leaves  object              10           0

**Memory Usage:** `4.3` KB (`0.004` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 3 — sensor_water_quality

**Shape:** `712` rows × `13` columns

**First 5 rows:**

,experiment,replicate,Date,Tme,pH,EC,TDS,Water temp.,Date_1,Tme_1,RH%,Air temp.,CO2
0,Experiment 3,Replicate 1 T1,,NaN,NaN,NaN,NaN,NaN,2024-05-19 00:00:00,17:00:00,51.6200,24.8100,415.2500
1,Experiment 3,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-19 00:00:00,18:00:00,53.1800,23.4500,415.7600
2,Experiment 3,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-19 00:00:00,19:00:00,54.3800,24.8700,424.6800
3,Experiment 3,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-19 00:00:00,20:00:00,55.1900,25.2900,432.4700
4,Experiment 3,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-05-19 00:00:00,21:00:00,57.2000,25.2800,435.4200

**Last 5 rows:**

,experiment,replicate,Date,Tme,pH,EC,TDS,Water temp.,Date_1,Tme_1,RH%,Air temp.,CO2
707,Experiment 3,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-19 00:00:00,12:00:00,61.4400,28.9100,458.0100
708,Experiment 3,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-19 00:00:00,13:00:00,60.3600,29.1900,456.5400
709,Experiment 3,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-19 00:00:00,14:00:00,59.8100,28.3400,451.1700
710,Experiment 3,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-19 00:00:00,15:00:00,60.6200,27.2700,439.1600
711,Experiment 3,Replicate 1 T1,NaN,NaN,NaN,NaN,NaN,NaN,2024-06-19 00:00:00,16:00:00,61.2700,26.2300,433.7100

**Column Names & Data Types:**

         Column   Dtype  Non-Null Count  Null Count
0    experiment     str             712           0
1     replicate     str             712           0
2          Date     str               1         711
3           Tme     str               0         712
4            pH     str               0         712
5            EC     str               0         712
6           TDS     str               0         712
7   Water temp.     str               0         712
8        Date_1  object             712           0
9         Tme_1  object             712           0
10          RH%  object             712           0
11    Air temp.  object             712           0
12          CO2  object             712           0

**Memory Usage:** `359.0` KB (`0.351` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 3 — portable_water_quality

**Shape:** `33` rows × `57` columns

**First 5 rows:**

,experiment,date,100000_replicate_1_t1_ph,100000_replicate_1_t1_ec,100000_replicate_1_t1_tds,100000_replicate_1_t1_water_temp,100000_replicate_2_t1_ph,100000_replicate_2_t1_ec,100000_replicate_2_t1_tds,100000_replicate_2_t1_water_temp,100000_replicate_3_t1_ph,100000_replicate_3_t1_ec,100000_replicate_3_t1_tds,100000_replicate_3_t1_water_temp,100000_replicate_1_t2_ph,100000_replicate_1_t2_ec,100000_replicate_1_t2_tds,100000_replicate_1_t2_water_temp,100000_replicate_2_t2_ph,100000_replicate_2_t2_ec,100000_replicate_2_t2_tds,100000_replicate_2_t2_water_temp,100000_replicate_3_t2_ph,100000_replicate_3_t2_ec,100000_replicate_3_t2_tds,100000_replicate_3_t2_water_temp,100000_air_air_parameters,100000_air_temp_col_26,100000_rh%_col_27,100000_rh%_col_28,140000_replicate_1_t1_ph,140000_replicate_1_t1_ec,140000_replicate_1_t1_tds,140000_replicate_1_t1_water_temp,140000_replicate_2_t1_ph,140000_replicate_2_t1_ec,140000_replicate_2_t1_tds,140000_replicate_2_t1_water_temp,140000_replicate_3_t1_ph,140000_replicate_3_t1_ec,140000_replicate_3_t1_tds,140000_replicate_3_t1_water_temp,140000_replicate_1_t2_ph,140000_replicate_1_t2_ec,140000_replicate_1_t2_tds,140000_replicate_1_t2_water_temp,140000_replicate_2_t2_ph,140000_replicate_2_t2_ec,140000_replicate_2_t2_tds,140000_replicate_2_t2_water_temp,140000_replicate_3_t2_ph,140000_replicate_3_t2_ec,140000_replicate_3_t2_tds,140000_replicate_3_t2_water_temp,140000_air_air_parameters,140000_air_temp_col_54,140000_rh%_col_55
0,Experiment 3,19/5/2024,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
1,Experiment 3,20/5/2024,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,NaN,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
2,Experiment 3,21/5/2024,6.9000,2.1700,1.0850,21.4000,7.2000,2.6200,1.3100,21.3000,7.6000,2.6000,1.3000,21.3000,7.6000,2.4000,1.2000,21.3000,7.8000,2.8000,1.4000,21.3000,7.7000,2.7000,1.3500,21.7000,-,-,-,NaN,6.8000,2.6000,1.3000,22.5000,7.1000,2.6200,1.3100,22.8000,7.5000,2.1300,1.0650,22.3000,7.4000,2.8000,1.4000,23.2000,7.6000,2.5000,1.2500,23.2000,7.5000,2.7000,1.3500,23.7000,-,-,-
3,Experiment 3,22/5/2024,7,2.6000,1.3000,21.7000,7.2000,2.6300,1.3150,21.7000,7.1000,2.5500,1.2750,21.5000,7.5000,2.8000,1.4000,21.3000,7.7000,2.5000,1.2500,21.2000,7.6000,2.8000,1.4000,22,1944,22.5000,74.6000,NaN,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,20190,25.3000,67.9000
4,Experiment 3,23/5/2024,7.2000,1.7400,0.8700,22.3000,6.9000,2.3200,1.1600,22.2000,7.2000,1.7500,0.8750,22.5000,7.6000,1.7300,0.8650,22.1000,7.6000,1.7600,0.8800,22.5000,7.7000,1.7500,0.8750,22.8000,1664,25,73.9000,NaN,7,1.9700,0.9850,23.9000,7,2.5400,1.2700,23.9000,7.3000,2,1,23.8000,7.6000,1.7900,0.8950,24,7.7000,2.2000,1.1000,24.1000,7.6000,2.7300,1.3650,24.5000,33360,24.9000,70.3000

**Last 5 rows:**

,experiment,date,100000_replicate_1_t1_ph,100000_replicate_1_t1_ec,100000_replicate_1_t1_tds,100000_replicate_1_t1_water_temp,100000_replicate_2_t1_ph,100000_replicate_2_t1_ec,100000_replicate_2_t1_tds,100000_replicate_2_t1_water_temp,100000_replicate_3_t1_ph,100000_replicate_3_t1_ec,100000_replicate_3_t1_tds,100000_replicate_3_t1_water_temp,100000_replicate_1_t2_ph,100000_replicate_1_t2_ec,100000_replicate_1_t2_tds,100000_replicate_1_t2_water_temp,100000_replicate_2_t2_ph,100000_replicate_2_t2_ec,100000_replicate_2_t2_tds,100000_replicate_2_t2_water_temp,100000_replicate_3_t2_ph,100000_replicate_3_t2_ec,100000_replicate_3_t2_tds,100000_replicate_3_t2_water_temp,100000_air_air_parameters,100000_air_temp_col_26,100000_rh%_col_27,100000_rh%_col_28,140000_replicate_1_t1_ph,140000_replicate_1_t1_ec,140000_replicate_1_t1_tds,140000_replicate_1_t1_water_temp,140000_replicate_2_t1_ph,140000_replicate_2_t1_ec,140000_replicate_2_t1_tds,140000_replicate_2_t1_water_temp,140000_replicate_3_t1_ph,140000_replicate_3_t1_ec,140000_replicate_3_t1_tds,140000_replicate_3_t1_water_temp,140000_replicate_1_t2_ph,140000_replicate_1_t2_ec,140000_replicate_1_t2_tds,140000_replicate_1_t2_water_temp,140000_replicate_2_t2_ph,140000_replicate_2_t2_ec,140000_replicate_2_t2_tds,140000_replicate_2_t2_water_temp,140000_replicate_3_t2_ph,140000_replicate_3_t2_ec,140000_replicate_3_t2_tds,140000_replicate_3_t2_water_temp,140000_air_air_parameters,140000_air_temp_col_54,140000_rh%_col_55
28,Experiment 3,16/6/2024,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,13890,27.7000,74.7000,NaN,7.1000,3.2500,1.6250,24.1000,7.3000,3.3200,1.6600,23.5000,7.4000,3.6100,1.8050,23.1000,7.5000,2.7300,1.3650,23.2000,7.6000,2.8300,1.4150,23.4000,7.5000,3.1500,1.5750,24.3000,-,-,-
29,Experiment 3,17/6/2024,7.3000,3.3100,1.6550,21.8000,7.4000,3.3900,1.6950,21.1000,7.5000,2.9900,1.4950,21.1000,7.5000,2.7000,1.3500,22.3000,7.6000,2.8600,1.4300,21.2000,7.5000,3.1300,1.5650,22.2000,NaN,NaN,NaN,NaN,7.3000,3.4100,1.7050,23.4000,7.4000,3.5300,1.7650,22.6000,7.5000,3.0600,1.5300,22.1000,7.5000,2.7200,1.3600,22.3000,7.6000,2.8200,1.4100,22.5000,7.5000,3.1600,1.5800,23.6000,-,-,-
30,Experiment 3,18/6/2024,7.4000,3.3200,1.6600,22.5000,7.7000,3.4600,1.7300,22.2000,7.5000,2.9900,1.4950,21.1000,7.5000,2.7000,1.3500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Experiment 3,19/6/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Experiment 3,NaN,6.6385,2.3411,1.1706,21.7926,6.7077,2.7207,1.3604,21.6519,6.8154,2.3800,1.1900,21.3481,7.0963,2.2800,1.1400,21.2923,7.3960,2.3212,1.1606,21.8731,7.4280,2.4008,1.2004,21.7083,17514.0952,26.2143,69.1571,NaN,6.6577,2.3485,1.1742,23.9654,6.7385,2.7223,1.3612,23.6731,6.8423,2.3623,1.1812,23.3840,7.2720,2.2132,1.1066,23.3600,7.3840,2.2640,1.1320,23.6880,7.4120,2.3400,1.1700,24.0760,24330.6191,29.3524,61.5333

**Column Names & Data Types:**

                              Column    Dtype  Non-Null Count  Null Count
0                         experiment      str              33           0
1                               date   object              32           1
2           100000_replicate_1_t1_ph   object              32           1
3           100000_replicate_1_t1_ec   object              32           1
4          100000_replicate_1_t1_tds   object              32           1
5   100000_replicate_1_t1_water_temp   object              32           1
6           100000_replicate_2_t1_ph   object              31           2
7           100000_replicate_2_t1_ec   object              32           1
8          100000_replicate_2_t1_tds   object              32           1
9   100000_replicate_2_t1_water_temp   object              32           1
10          100000_replicate_3_t1_ph   object              31           2
11          100000_replicate_3_t1_ec   object              32           1
12         100000_replicate_3_t1_tds   object              32           1
13  100000_replicate_3_t1_water_temp   object              32           1
14          100000_replicate_1_t2_ph   object              32           1
15          100000_replicate_1_t2_ec   object              32           1
16         100000_replicate_1_t2_tds   object              32           1
17  100000_replicate_1_t2_water_temp   object              31           2
18          100000_replicate_2_t2_ph   object              30           3
19          100000_replicate_2_t2_ec   object              31           2
20         100000_replicate_2_t2_tds   object              31           2
21  100000_replicate_2_t2_water_temp   object              31           2
22          100000_replicate_3_t2_ph   object              30           3
23          100000_replicate_3_t2_ec   object              31           2
24         100000_replicate_3_t2_tds   object              31           2
25  100000_replicate_3_t2_water_temp   object              31           2
26         100000_air_air_parameters   object              30           3
27            100000_air_temp_col_26   object              30           3
28                 100000_rh%_col_27   object              30           3
29                 100000_rh%_col_28  float64               0          33
30          140000_replicate_1_t1_ph   object              31           2
31          140000_replicate_1_t1_ec   object              31           2
32         140000_replicate_1_t1_tds   object              31           2
33  140000_replicate_1_t1_water_temp   object              31           2
34          140000_replicate_2_t1_ph   object              31           2
35          140000_replicate_2_t1_ec   object              31           2
36         140000_replicate_2_t1_tds   object              31           2
37  140000_replicate_2_t1_water_temp   object              31           2
38          140000_replicate_3_t1_ph   object              31           2
39          140000_replicate_3_t1_ec   object              31           2
40         140000_replicate_3_t1_tds   object              31           2
41  140000_replicate_3_t1_water_temp   object              31           2
42          140000_replicate_1_t2_ph   object              31           2
43          140000_replicate_1_t2_ec   object              31           2
44         140000_replicate_1_t2_tds   object              31           2
45  140000_replicate_1_t2_water_temp   object              31           2
46          140000_replicate_2_t2_ph   object              31           2
47          140000_replicate_2_t2_ec   object              31           2
48         140000_replicate_2_t2_tds   object              31           2
49  140000_replicate_2_t2_water_temp   object              31           2
50          140000_replicate_3_t2_ph   object              31           2
51          140000_replicate_3_t2_ec   object              31           2
52         140000_replicate_3_t2_tds   object              31           2
53  140000_replicate_3_t2_water_temp   object              31           2
54         140000_air_air_parameters   object              31           2
55            140000_air_temp_col_54   object              31           2
56                 140000_rh%_col_55   object              31           2

**Memory Usage:** `64.9` KB (`0.063` MB)

**Summary Statistics (numeric columns):**

       100000_rh%_col_28
count             0.0000
mean                 NaN
std                  NaN
min                  NaN
25%                  NaN
50%                  NaN
75%                  NaN
max                  NaN

──────────────────────────────────────────────────────────────────────

### Experiment 3 — nutrients_date

**Shape:** `11` rows × `2` columns

**First 5 rows:**

     experiment                 date
0  Experiment 3            24/5/2024
1  Experiment 3  2024-05-06 00:00:00
2  Experiment 3                  NaN
3  Experiment 3                  NaN
4  Experiment 3                  NaN

**Last 5 rows:**

      experiment    date
6   Experiment 3     NaN
7   Experiment 3     NaN
8   Experiment 3     NaN
9   Experiment 3     NaN
10  Experiment 3  Total

**Column Names & Data Types:**

       Column   Dtype  Non-Null Count  Null Count
0  experiment     str              11           0
1        date  object               3           8

**Memory Usage:** `1.2` KB (`0.001` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 3 — nutrients_nutrient_solution_addition_(a+b)_ml

**Shape:** `11` rows × `7` columns

**First 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
0,Experiment 3,180,180,180,180,180,180
1,Experiment 3,197,173,187,188,187,190
2,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
3,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
4,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN

**Last 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
6,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
7,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
8,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
9,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
10,Experiment 3,377,353,367,368,367,370

**Column Names & Data Types:**

           Column   Dtype  Non-Null Count  Null Count
0      experiment     str              11           0
1  Replicate_1_T1  object               3           8
2  Replicate_2_T1  object               3           8
3  Replicate_3_T1  object               3           8
4  Replicate_1_T2  object               3           8
5  Replicate_2_T2  object               3           8
6  Replicate_3_T2  object               3           8

**Memory Usage:** `2.9` KB (`0.003` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 3 — nutrients_water_consumption_l

**Shape:** `11` rows × `7` columns

**First 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
0,Experiment 3,100,100,100,100,100,100
1,Experiment 3,45,40,30,30,35,40
2,Experiment 3,50,50,50,50,50,50
3,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
4,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN

**Last 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
6,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
7,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
8,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
9,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
10,Experiment 3,195,190,180,180,185,190

**Column Names & Data Types:**

           Column   Dtype  Non-Null Count  Null Count
0      experiment     str              11           0
1  Replicate_1_T1  object               4           7
2  Replicate_2_T1  object               4           7
3  Replicate_3_T1  object               4           7
4  Replicate_1_T2  object               4           7
5  Replicate_2_T2  object               4           7
6  Replicate_3_T2  object               4           7

**Memory Usage:** `2.9` KB (`0.003` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 3 — nutrients_acid_consumption_ml

**Shape:** `11` rows × `7` columns

**First 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
0,Experiment 3,15,15,15,15,15,15
1,Experiment 3,15,15,15,15,15,15
2,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
3,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
4,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN

**Last 5 rows:**

,experiment,Replicate_1_T1,Replicate_2_T1,Replicate_3_T1,Replicate_1_T2,Replicate_2_T2,Replicate_3_T2
6,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
7,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
8,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
9,Experiment 3,NaN,NaN,NaN,NaN,NaN,NaN
10,Experiment 3,30,30,30,30,30,30

**Column Names & Data Types:**

           Column   Dtype  Non-Null Count  Null Count
0      experiment     str              11           0
1  Replicate_1_T1  object               3           8
2  Replicate_2_T1  object               3           8
3  Replicate_3_T1  object               3           8
4  Replicate_1_T2  object               3           8
5  Replicate_2_T2  object               3           8
6  Replicate_3_T2  object               3           8

**Memory Usage:** `2.9` KB (`0.003` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

### Experiment 3 — harvest

**Shape:** `83` rows × `13` columns

**First 5 rows:**

,experiment,system,Plant No.,Plant height (cm),Shoot length (cm),Root length (cm),H.D (cm),Total weight (g),Stem diameter (cm),Shoot weight before removing wilted leaves (g),Shoot weight after removing wilted leaves (g),Root weight (g),No.of leaves
0,Experiment 3,R1T1,1,60,20,40,30*31,328,1,271,269,57,42
1,Experiment 3,R1T1,2,60,19,41,29*31,252,1.5000,244,243,8,46
2,Experiment 3,R1T1,3,75,17,58,28*30,294,1,239,237,55,43
3,Experiment 3,R1T1,4,100,17,83,29*29,331,1.5000,295,292,36,40
4,Experiment 3,R1T1,5,72,15,57,30*31,357,1,317,317,40,46

**Last 5 rows:**

,experiment,system,Plant No.,Plant height (cm),Shoot length (cm),Root length (cm),H.D (cm),Total weight (g),Stem diameter (cm),Shoot weight before removing wilted leaves (g),Shoot weight after removing wilted leaves (g),Root weight (g),No.of leaves
78,Experiment 3,R3T2,9,62,17,45,25*25,224,1,190,187,34,35
79,Experiment 3,R3T2,10,55,16,39,23*21,200,1,166,162,34,36
80,Experiment 3,R3T2,11,56,16,40,23*24,282,1.2000,238,236,44,44
81,Experiment 3,R3T2,12,57,15,42,23*29,223,1,191,191,32,36
82,Experiment 3,R3T2,NaN,61.5000,17.1667,44.3333,NaN,241.5833,1.0583,206.7500,202.7500,34.8333,38.6667

**Column Names & Data Types:**

,Column,Dtype,Non-Null Count,Null Count
0,experiment,str,83,0
1,system,str,83,0
2,Plant No.,object,77,6
3,Plant height (cm),object,83,0
4,Shoot length (cm),object,83,0
5,Root length (cm),object,83,0
6,H.D (cm),str,77,6
7,Total weight (g),object,83,0
8,Stem diameter (cm),object,83,0
9,Shoot weight before removing wilted ...,object,83,0
10,Shoot weight after removing wilted l...,object,83,0
11,Root weight (g),object,83,0
12,No.of leaves,object,83,0

**Memory Usage:** `44.2` KB (`0.043` MB)

*No numeric columns to summarize.*

──────────────────────────────────────────────────────────────────────

---

## 5 · Data Quality Assessment

We perform a thorough quality audit across **every** parsed table. This section checks for:

| Check | Purpose |
|---|---|
| Missing values | Identify nulls and their distribution |
| Duplicate rows | Detect exact row duplicates |
| Constant columns | Find zero-variance columns |
| Unique value counts | Understand cardinality |
| Invalid datatypes | Detect string values in expected numeric columns |
| Negative values | Flag suspicious negatives in measurement columns |
| Impossible values | Flag physically impossible measurements |
| Outliers | Detect statistical outliers (IQR method) — **flag only, never remove** |
| Null percentages | Rank columns by missing data severity |

In [17]:
# ==========================================================================
# Quality assessment utility functions
# ==========================================================================

def check_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    """Return a DataFrame summarizing missing values per column."""
    missing = df.isnull().sum()
    pct = (missing / len(df) * 100).round(2)
    result = pd.DataFrame({
        "missing_count": missing,
        "missing_pct": pct,
        "dtype": df.dtypes,
    })
    return result[result["missing_count"] > 0].sort_values("missing_pct", ascending=False)


def check_duplicates(df: pd.DataFrame) -> int:
    """Return count of exact duplicate rows."""
    return int(df.duplicated().sum())


def check_constant_columns(df: pd.DataFrame) -> List[str]:
    """Identify columns with only one unique value (excluding NaN)."""
    constant_cols = []
    for col in df.columns:
        n_unique = df[col].dropna().nunique()
        if n_unique <= 1:
            constant_cols.append(col)
    return constant_cols


def check_unique_values(df: pd.DataFrame) -> pd.DataFrame:
    """Return a summary of unique value counts per column."""
    return pd.DataFrame({
        "unique_count": df.nunique(),
        "total_rows": len(df),
        "unique_pct": (df.nunique() / len(df) * 100).round(2),
        "sample_values": [
            str(df[col].dropna().unique()[:5].tolist()) for col in df.columns
        ],
    })


def check_invalid_numeric(
    df: pd.DataFrame, expected_numeric_cols: Optional[List[str]] = None
) -> Dict[str, List]:
    """
    Detect non-numeric values in columns that should be numeric.
    If expected_numeric_cols is None, checks all object-type columns
    for values that look partially numeric.
    """
    issues = {}
    cols_to_check = expected_numeric_cols or [
        c for c in df.columns if df[c].dtype == object
    ]

    for col in cols_to_check:
        if col not in df.columns:
            continue
        non_null = df[col].dropna()
        if non_null.empty:
            continue
        converted = pd.to_numeric(non_null, errors="coerce")
        failed_mask = converted.isna() & non_null.notna()
        if failed_mask.any():
            bad_vals = non_null[failed_mask].unique().tolist()
            if len(bad_vals) > 0:
                issues[col] = bad_vals[:10]

    return issues


def check_negative_values(df: pd.DataFrame) -> Dict[str, int]:
    """Flag columns with negative values (suspicious for physical measurements)."""
    negatives = {}
    for col in df.select_dtypes(include=[np.number]).columns:
        neg_count = int((df[col] < 0).sum())
        if neg_count > 0:
            negatives[col] = neg_count
    return negatives


def check_outliers_iqr(df: pd.DataFrame, factor: float = 1.5) -> pd.DataFrame:
    """
    Detect outliers using the IQR method.
    Returns a summary of outlier counts per numeric column.
    NOTE: Outliers are flagged only — never removed.
    """
    records = []
    for col in df.select_dtypes(include=[np.number]).columns:
        q1 = df[col].quantile(0.25)
        q3 = df[col].quantile(0.75)
        iqr = q3 - q1
        lower = q1 - factor * iqr
        upper = q3 + factor * iqr
        outlier_mask = (df[col] < lower) | (df[col] > upper)
        n_outliers = int(outlier_mask.sum())
        if n_outliers > 0:
            records.append({
                "column": col,
                "q1": round(q1, 4),
                "q3": round(q3, 4),
                "iqr": round(iqr, 4),
                "lower_bound": round(lower, 4),
                "upper_bound": round(upper, 4),
                "n_outliers": n_outliers,
                "pct_outliers": round(n_outliers / len(df) * 100, 2),
            })
    return pd.DataFrame(records) if records else pd.DataFrame()


logger.info("Quality assessment functions defined.")

2026-07-15 19:48:59,093 | INFO | Quality assessment functions defined.

In [18]:
def run_quality_assessment(
    df: pd.DataFrame, title: str, show_details: bool = True
) -> Dict[str, Any]:
    """
    Run the complete quality assessment suite on a DataFrame.
    Returns a dict of all findings for downstream use.
    """
    results = {}

    if show_details:
        display(Markdown(f"### 🔍 {title}"))

    # 1. Missing values
    missing_df = check_missing_values(df)
    results["missing"] = missing_df
    if show_details:
        if not missing_df.empty:
            display(Markdown("**Missing Values:**"))
            display(missing_df)
        else:
            display(Markdown("**Missing Values:** ✅ None detected."))

    # 2. Duplicates
    dup_count = check_duplicates(df)
    results["duplicates"] = dup_count
    if show_details:
        if dup_count > 0:
            display(Markdown(f"**Duplicate Rows:** ⚠️ **{dup_count}** exact duplicates found."))
        else:
            display(Markdown("**Duplicate Rows:** ✅ None detected."))

    # 3. Constant columns
    const_cols = check_constant_columns(df)
    results["constant_columns"] = const_cols
    if show_details:
        if const_cols:
            display(Markdown(
                f"**Constant Columns:** ⚠️ {len(const_cols)} column(s) with ≤1 unique value: "
                f"`{'`, `'.join(map(str, const_cols))}`"
            ))
        else:
            display(Markdown("**Constant Columns:** ✅ None detected."))

    # 4. Unique values
    unique_df = check_unique_values(df)
    results["unique_values"] = unique_df
    if show_details:
        display(Markdown("**Unique Value Counts:**"))
        display(unique_df)

    # 5. Invalid numeric values
    invalid_numeric = check_invalid_numeric(df)
    results["invalid_numeric"] = invalid_numeric
    if show_details:
        if invalid_numeric:
            display(Markdown("**Invalid Numeric Values (non-numeric in expected numeric columns):**"))
            for col, vals in invalid_numeric.items():
                display(Markdown(f"- `{col}`: `{vals}` ({len(vals)} unique invalid value(s))"))
        else:
            display(Markdown("**Invalid Numeric Values:** ✅ None detected."))

    # 6. Negative values
    negatives = check_negative_values(df)
    results["negatives"] = negatives
    if show_details:
        if negatives:
            display(Markdown("**Negative Values (suspicious for physical measurements):**"))
            for col, count in negatives.items():
                display(Markdown(f"- `{col}`: {count} negative value(s)"))
        else:
            display(Markdown("**Negative Values:** ✅ None detected in numeric columns."))

    # 7. Outliers (IQR)
    outlier_df = check_outliers_iqr(df)
    results["outliers"] = outlier_df
    if show_details:
        if not outlier_df.empty:
            display(Markdown(
                "**Outliers (IQR Method, factor=1.5):**  \\n"
                "> ⚠️ Flagged for review only — **not removed**."
            ))
            display(outlier_df)
        else:
            display(Markdown("**Outliers (IQR):** ✅ None detected."))

    if show_details:
        print("\n" + "─" * 70 + "\n")

    return results

In [19]:
# ==========================================================================
# Run quality assessment on ALL parsed tables
# ==========================================================================
quality_reports: Dict[str, Dict[str, Dict]] = {}

for exp_label, tables in parsed_data.items():
    display(Markdown(f"## 📂 {exp_label} — Quality Assessment"))
    display(Markdown("---"))
    quality_reports[exp_label] = {}

    for tname, tdata in tables.items():
        if isinstance(tdata, pd.DataFrame) and not tdata.empty:
            quality_reports[exp_label][tname] = run_quality_assessment(
                tdata, f"{exp_label} — {tname}"
            )

logger.info("Quality assessment complete for all datasets.")

## 📂 Experiment 1 — Quality Assessment

---

### 🔍 Experiment 1 — seedlings

**Missing Values:**

      missing_count  missing_pct   dtype
Date              9      90.0000  object

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 3 column(s) with ≤1 unique value: `experiment`, `Date`, `stem diameter  (cm)`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,10,10.0000,['Experiment 1']
Date,1,10,10.0000,"[datetime.datetime(2024, 9, 3, 0, 0)]"
plant NO.,10,10,100.0000,"[1, 2, 3, 4, 5]"
plant height (cm),4,10,40.0000,"[9, 10, 9.5, 12]"
shoot length (cm),3,10,30.0000,"[2, 3, 2.5]"
root length (cm),3,10,30.0000,"[7, 6.5, 9]"
head diameter (cm),7,10,70.0000,"['4*2', '3.5*3', '3.5*2.5', '3*3', '..."
stem diameter (cm),1,10,10.0000,[0.1]
total weight (g),7,10,70.0000,"[1.3, 1.2, 1.1, 1.14, 1]"
shoot weight (g),9,10,90.0000,"[0.5, 0.55, 0.53, 0.45, 0.4]"
root weight (g),9,10,90.0000,"[0.8, 0.6499999999999999, 0.57000000..."
no. of leaves,2,10,20.0000,"[5, 4]"

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `Date`: `[datetime.datetime(2024, 9, 3, 0, 0)]` (1 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — sensor_water_quality

**Missing Values:**

             missing_count  missing_pct   dtype
Tme                    641     100.0000     str
pH                     641     100.0000     str
EC                     641     100.0000     str
Water temp.            641     100.0000     str
TDS                    641     100.0000     str
Date                   640      99.8400     str
Date_1                   1       0.1600  object
Tme_1                    1       0.1600  object
RH %                     1       0.1600  object
Air temp. C              1       0.1600  object
CO2 PPM                  1       0.1600  object

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 8 column(s) with ≤1 unique value: `experiment`, `replicate`, `Date`, `Tme`, `pH`, `EC`, `TDS`, `Water temp.`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,641,0.1600,['Experiment 1']
replicate,1,641,0.1600,['Replicate 1 T1']
Date,1,641,0.1600,[' ']
Tme,0,641,0.0000,[]
pH,0,641,0.0000,[]
EC,0,641,0.0000,[]
TDS,0,641,0.0000,[]
Water temp.,0,641,0.0000,[]
Date_1,29,641,4.5200,"[datetime.datetime(2024, 3, 10, 0, 0..."
Tme_1,24,641,3.7400,"[datetime.time(10, 0), datetime.time..."
RH %,554,641,86.4300,"[49.08, 47.51, 46.8, 47.12, 47.64]"
Air temp. C,512,641,79.8800,"[24.18, 23.55, 23.81, 24.48, 24.74]"
CO2 PPM,620,641,96.7200,"[406.96, 406.55, 413.38, 412.5, 408.94]"

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `Date_1`: `[datetime.datetime(2024, 3, 10, 0, 0), datetime.datetime(2024, 3, 11, 0, 0), datetime.datetime(2024, 3, 12, 0, 0), datetime.datetime(2024, 3, 13, 0, 0), datetime.datetime(2024, 3, 14, 0, 0), datetime.datetime(2024, 3, 15, 0, 0), datetime.datetime(2024, 3, 16, 0, 0), datetime.datetime(2024, 3, 17, 0, 0), datetime.datetime(2024, 3, 18, 0, 0), datetime.datetime(2024, 3, 19, 0, 0)]` (10 unique invalid value(s))

- `Tme_1`: `[datetime.time(10, 0), datetime.time(11, 0), datetime.time(12, 0), datetime.time(13, 0), datetime.time(14, 0), datetime.time(15, 0), datetime.time(16, 0), datetime.time(17, 0), datetime.time(18, 0), datetime.time(19, 0)]` (10 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — portable_water_quality

**Missing Values:**

                                  missing_count  missing_pct    dtype
100000_air_temp_col_28                       33     100.0000  float64
140000_air_temp_col_55                       26      78.7900   object
140000_rh%_col_54                            26      78.7900   object
140000_air_air_parameters                    26      78.7900   object
100000_air_air_parameters                    18      54.5500   object
100000_rh%_col_26                            18      54.5500   object
100000_air_temp_col_27                       18      54.5500   object
140000_replicate_1_t2_water_temp             11      33.3300   object
140000_replicate_1_t1_water_temp             11      33.3300   object
140000_replicate_2_t1_ph                     11      33.3300   object
140000_replicate_1_t1_ph                     11      33.3300   object
140000_replicate_3_t1_water_temp             11      33.3300   object
140000_replicate_2_t1_water_temp             11      33.3300   object
140000_replicate_2_t1_ec                     11      33.3300   object
140000_replicate_3_t1_ph                     11      33.3300   object
140000_replicate_3_t1_ec                     11      33.3300   object
140000_replicate_1_t1_ec                     11      33.3300   object
140000_replicate_1_t2_ec                     11      33.3300   object
140000_replicate_1_t2_ph                     11      33.3300   object
140000_replicate_2_t2_ec                     11      33.3300   object
140000_replicate_2_t2_water_temp             11      33.3300   object
140000_replicate_2_t2_ph                     11      33.3300   object
140000_replicate_3_t2_ec                     11      33.3300   object
140000_replicate_3_t2_ph                     11      33.3300   object
140000_replicate_3_t2_water_temp             11      33.3300   object
140000_replicate_3_t1_tds                     9      27.2700   object
140000_replicate_1_t1_tds                     9      27.2700   object
140000_replicate_2_t1_tds                     9      27.2700   object
140000_replicate_2_t2_tds                     9      27.2700   object
140000_replicate_1_t2_tds                     9      27.2700   object
140000_replicate_3_t2_tds                     9      27.2700   object
100000_replicate_3_t2_ec                      8      24.2400   object
100000_replicate_2_t1_water_temp              8      24.2400   object
100000_replicate_3_t1_ph                      8      24.2400   object
100000_replicate_3_t1_ec                      8      24.2400   object
100000_replicate_2_t1_ec                      8      24.2400   object
100000_replicate_1_t1_water_temp              8      24.2400   object
100000_replicate_2_t1_ph                      8      24.2400   object
100000_replicate_2_t2_tds                     8      24.2400   object
100000_replicate_2_t2_water_temp              8      24.2400   object
100000_replicate_1_t2_water_temp              8      24.2400   object
100000_replicate_2_t2_ph                      8      24.2400   object
100000_replicate_1_t2_ph                      8      24.2400   object
100000_replicate_1_t2_ec                      8      24.2400   object
100000_replicate_3_t1_water_temp              8      24.2400   object
100000_replicate_2_t2_ec                      8      24.2400   object
100000_replicate_1_t1_ec                      8      24.2400   object
100000_replicate_1_t1_ph                      8      24.2400   object
100000_replicate_3_t2_ph                      8      24.2400   object
100000_replicate_3_t2_water_temp              8      24.2400   object
100000_replicate_2_t1_tds                     7      21.2100   object
100000_replicate_3_t2_tds                     7      21.2100   object
100000_replicate_3_t1_tds                     7      21.2100   object
100000_replicate_1_t1_tds                     7      21.2100   object
100000_replicate_1_t2_tds                     7      21.2100   object
date                                          3       9.0900   object

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 2 column(s) with ≤1 unique value: `experiment`, `100000_air_temp_col_28`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,33,3.0300,['Experiment 1']
date,30,33,90.9100,"[datetime.datetime(2024, 10, 3, 0, 0..."
100000_replicate_1_t1_ph,14,33,42.4200,"['-', 5.3, 5.7, 5.9, 6]"
100000_replicate_1_t1_ec,19,33,57.5800,"['-', 2, 1.95, 1.97, 1.92]"
100000_replicate_1_t1_tds,20,33,60.6100,"['-', 1, 0.975, 0.985, 0.96]"
100000_replicate_1_t1_water_temp,18,33,54.5500,"['-', 19.3, 22, 26.6, 24.3]"
100000_replicate_2_t1_ph,10,33,30.3000,"['-', 5.8, 6, 5.9, 5.7]"
100000_replicate_2_t1_ec,18,33,54.5500,"['-', 2.02, 2, 2.03, 2.01]"
100000_replicate_2_t1_tds,19,33,57.5800,"['-', 1.01, 1, 1.015, 1.005]"
100000_replicate_2_t1_water_temp,16,33,48.4800,"['-', 19.1, 21.2, 22, 25.1]"
100000_replicate_3_t1_ph,13,33,39.3900,"['-', 5.6, 5.7, 5.8, 5.4]"
100000_replicate_3_t1_ec,17,33,51.5200,"['-', 2.02, 2.01, 1.99, 2.03]"
100000_replicate_3_t1_tds,18,33,54.5500,"['-', 1.01, 1.005, 0.995, 1.015]"
100000_replicate_3_t1_water_temp,20,33,60.6100,"['-', 18.9, 20.6, 22, 24]"
100000_replicate_1_t2_ph,13,33,39.3900,"['-', 5.6, 5.4, 5.5, 5.1]"
100000_replicate_1_t2_ec,16,33,48.4800,"['-', 1.94, 1.98, 1.96, 1.95]"
100000_replicate_1_t2_tds,17,33,51.5200,"['-', 0.97, 0.99, 0.98, 0.975]"
100000_replicate_1_t2_water_temp,18,33,54.5500,"['-', 18.6, 21.4, 22, 25]"
100000_replicate_2_t2_ph,12,33,36.3600,"['-', 5.8, 5.9, 5.5, 5.7]"
100000_replicate_2_t2_ec,18,33,54.5500,"['-', 2.01, 2.02, 2.03, 2]"
100000_replicate_2_t2_tds,19,33,57.5800,"['-', 1.005, 1.01, 1.015, 1]"
100000_replicate_2_t2_water_temp,18,33,54.5500,"['-', 19.7, 22, 22.4, 22.9]"
100000_replicate_3_t2_ph,12,33,36.3600,"['-', 5.6, 6.9, 6.5, 6.4]"
100000_replicate_3_t2_ec,15,33,45.4500,"['-', 2.16, 1.54, 1.87, 1.82]"
100000_replicate_3_t2_tds,16,33,48.4800,"['-', 1.08, 0.77, 0.935, 0.91]"
100000_replicate_3_t2_water_temp,19,33,57.5800,"['-', 22.9, 22.6, 23, 26.2]"
100000_air_air_parameters,15,33,45.4500,"['-', 50330, 60540, 22050, 38880]"
100000_rh%_col_26,15,33,45.4500,"['-', 64, 45, 60, 68.1]"
100000_air_temp_col_27,15,33,45.4500,"['-', 20.4, 29.5, 23.5, 22.3]"
100000_air_temp_col_28,0,33,0.0000,[]
140000_replicate_1_t1_ph,13,33,39.3900,"[6.9, 5.2, 5.7, 6, '-']"
140000_replicate_1_t1_ec,16,33,48.4800,"[1.61, 2, 1.94, 2.02, 1.93]"
140000_replicate_1_t1_tds,15,33,45.4500,"[0.8, 1, 0.97, 1.01, 0.965]"
140000_replicate_1_t1_water_temp,16,33,48.4800,"[22.5, 23.9, 25.7, 22, 26]"
140000_replicate_2_t1_ph,8,33,24.2400,"[6.9, 5.8, 6, '-', 6.1]"
140000_replicate_2_t1_ec,14,33,42.4200,"[1.57, 2.02, 2.01, '-', 1.89]"
140000_replicate_2_t1_tds,14,33,42.4200,"[0.78, 1.01, 1.005, '-', 0.945]"
140000_replicate_2_t1_water_temp,18,33,54.5500,"[22.5, 22.1, 25.7, 25.4, 24.8]"
140000_replicate_3_t1_ph,9,33,27.2700,"[6.9, 5.7, 5.9, '-', 5.8]"
140000_replicate_3_t1_ec,17,33,51.5200,"[1.56, 2.01, 2, 1.98, '-']"
140000_replicate_3_t1_tds,16,33,48.4800,"[0.78, 1.005, 1, 0.99, '-']"
140000_replicate_3_t1_water_temp,16,33,48.4800,"[22.3, 26, 25, '-', 24.1]"
140000_replicate_1_t2_ph,11,33,33.3300,"[6.8, 5.4, 5.5, 5.6, '-']"
140000_replicate_1_t2_ec,16,33,48.4800,"[1.57, 1.94, 1.98, 1.95, '-']"
140000_replicate_1_t2_tds,15,33,45.4500,"[0.78, 0.97, 0.99, 0.975, '-']"
140000_replicate_1_t2_water_temp,17,33,51.5200,"[22.7, 22.5, 25.4, 25.3, 26]"
140000_replicate_2_t2_ph,10,33,30.3000,"[7, 5.8, 5.9, '-', 6]"
140000_replicate_2_t2_ec,15,33,45.4500,"[1.56, 2.02, 2.01, '-', 1.78]"
140000_replicate_2_t2_tds,14,33,42.4200,"[0.77, 1.01, 1.005, '-', 0.89]"
140000_replicate_2_t2_water_temp,17,33,51.5200,"[22.9, 22.3, 25.5, 25.4, 25.6]"
140000_replicate_3_t2_ph,13,33,39.3900,"[6.9, 5.6, 6.3, 6.5, 6.4]"
140000_replicate_3_t2_ec,16,33,48.4800,"[1.56, 2.16, 1.86, 1.87, 1.82]"
140000_replicate_3_t2_tds,15,33,45.4500,"[0.76, 1.08, 0.93, 0.935, 0.91]"
140000_replicate_3_t2_water_temp,17,33,51.5200,"[23, 22.9, 26, 28, '-']"
140000_air_air_parameters,7,33,21.2100,"[48300, 61270, 45190, 36530, 65870]"
140000_rh%_col_54,7,33,21.2100,"[60.8, 59.5, 55, 54.8, 61.7]"
140000_air_temp_col_55,7,33,21.2100,"[22.1, 21.8, 26.7, 25.1, 26.3]"

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `date`: `[datetime.datetime(2024, 10, 3, 0, 0), datetime.datetime(2024, 11, 3, 0, 0), datetime.datetime(2024, 12, 3, 0, 0), '13/3/2024', '14/3/2024', '15/3/2024', '16/3/2024', '17/3/2024', '18/3/2024', '19/3/2024']` (10 unique invalid value(s))

- `100000_replicate_1_t1_ph`: `['-', ' -']` (2 unique invalid value(s))

- `100000_replicate_1_t1_ec`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t1_tds`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t1_ph`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t1_ec`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t1_tds`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t1_ph`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t1_ec`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t1_tds`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t2_ph`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t2_ec`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t2_tds`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t2_ph`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t2_ec`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t2_tds`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t2_ph`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t2_ec`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t2_tds`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `100000_air_air_parameters`: `['-']` (1 unique invalid value(s))

- `100000_rh%_col_26`: `['-']` (1 unique invalid value(s))

- `100000_air_temp_col_27`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t1_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t1_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t1_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t1_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t1_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t1_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t1_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t1_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t1_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t2_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t2_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t2_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t2_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t2_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t2_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t2_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t2_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t2_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t2_water_temp`: `['-']` (1 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — nutrients_date

**Missing Values:**

      missing_count  missing_pct   dtype
date             19      79.1700  object

**Duplicate Rows:** ⚠️ **18** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,24,4.1700,['Experiment 1']
date,5,24,20.8300,"[datetime.datetime(2024, 11, 3, 0, 0..."

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `date`: `[datetime.datetime(2024, 11, 3, 0, 0), '20/3/2024', '29/3/2024', datetime.datetime(2024, 1, 4, 0, 0), 'Total ']` (5 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — nutrients_nutrient_solution_addition_(a+b)_ml

**Missing Values:**

                missing_count  missing_pct   dtype
Replicate_1_T1             19      79.1700  object
Replicate_2_T1             19      79.1700  object
Replicate_3_T1             19      79.1700  object
Replicate_1_T2             19      79.1700  object
Replicate_2_T2             19      79.1700  object
Replicate_3_T2             19      79.1700  object

**Duplicate Rows:** ⚠️ **18** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct          sample_values
experiment                 1          24      4.1700       ['Experiment 1']
Replicate_1_T1             5          24     20.8300  [115, 30, 0, 12, 157]
Replicate_2_T1             5          24     20.8300   [136, 30, 0, 9, 175]
Replicate_3_T1             5          24     20.8300   [136, 30, 0, 9, 175]
Replicate_1_T2             5          24     20.8300  [136, 30, 0, 21, 187]
Replicate_2_T2             5          24     20.8300  [136, 30, 0, 21, 187]
Replicate_3_T2             4          24     16.6700     [136, 30, 27, 329]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — nutrients_acid_consumption_(ml)

**Missing Values:**

                missing_count  missing_pct   dtype
Replicate_1_T1             20      83.3300  object
Replicate_2_T1             20      83.3300  object
Replicate_3_T1             20      83.3300  object
Replicate_1_T2             20      83.3300  object
Replicate_2_T2             20      83.3300  object
Replicate_3_T2             20      83.3300  object

**Duplicate Rows:** ⚠️ **19** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct     sample_values
experiment                 1          24      4.1700  ['Experiment 1']
Replicate_1_T1             4          24     16.6700   [20, 14, 5, 39]
Replicate_2_T1             4          24     16.6700   [20, 10, 5, 35]
Replicate_3_T1             4          24     16.6700   [20, 10, 5, 35]
Replicate_1_T2             4          24     16.6700   [20, 10, 5, 35]
Replicate_2_T2             4          24     16.6700   [20, 10, 5, 35]
Replicate_3_T2             4          24     16.6700   [20, 10, 5, 35]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — nutrients_water_consumption_l

**Missing Values:**

                missing_count  missing_pct   dtype
Replicate_1_T1             19      79.1700  object
Replicate_2_T1             19      79.1700  object
Replicate_3_T1             19      79.1700  object
Replicate_1_T2             19      79.1700  object
Replicate_2_T2             19      79.1700  object
Replicate_3_T2             19      79.1700  object

**Duplicate Rows:** ⚠️ **18** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct           sample_values
experiment                 1          24      4.1700        ['Experiment 1']
Replicate_1_T1             4          24     16.6700         [10, 0, 15, 35]
Replicate_2_T1             4          24     16.6700         [0, 10, 15, 25]
Replicate_3_T1             4          24     16.6700         [0, 10, 15, 25]
Replicate_1_T2             4          24     16.6700         [0, 10, 15, 25]
Replicate_2_T2             3          24     12.5000             [0, 15, 30]
Replicate_3_T2             5          24     20.8300  [100, 10, 16, 15, 141]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — head_diameter

**Missing Values:**

               missing_count  missing_pct    dtype
plant_no                 120      40.0000  float64
head_diameter            120      40.0000   object

**Duplicate Rows:** ⚠️ **96** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,300,0.3300,['Experiment 1']
replicate,6,300,2.0000,"['Replicate 1', 'Replicate 2', 'Repl..."
day,5,300,1.6700,"['day 3', 'day 6', 'Day 9', 'Day 12'..."
plant_no,10,300,3.3300,"[1.0, 2.0, 3.0, 4.0, 5.0]"
head_diameter,86,300,28.6700,"['4*4', '5*5', '9*12', '11*12', '16*..."

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `head_diameter`: `['4*4', '5*5', '9*12', '11*12', '16*17', '5*4', '12*10', '13*12.5', '15*16', '3*3.5']` (10 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,plant_no,2.0000,5.0000,3.0000,-2.5000,9.5000,6,2.0000

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — harvest

**Missing Values:**

                                          missing_count  missing_pct    dtype
Plant No.                                             1       1.3700  float64
Total weight (g)                                      1       1.3700  float64
Plant height (cm)                                     1       1.3700  float64
Shoot length (cm)                                     1       1.3700  float64
Root length (cm)                                      1       1.3700  float64
Head diameter (cm)                                    1       1.3700      str
Stem diameter (cm)                                    1       1.3700  float64
Shoot weight before removing wilted l...              1       1.3700  float64
Root weight (g)                                       1       1.3700  float64
No. of leaves                                         1       1.3700  float64

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,73,1.3700,['Experiment 1']
Plant No.,12,73,16.4400,"[1.0, 2.0, 3.0, 4.0, 5.0]"
Total weight (g),54,73,73.9700,"[243.0, 241.0, 251.0, 200.0, 209.0]"
Plant height (cm),26,73,35.6200,"[42.0, 54.0, 62.0, 55.0, 66.0]"
Shoot length (cm),13,73,17.8100,"[13.5, 10.5, 14.0, 13.0, 16.0]"
Root length (cm),33,73,45.2100,"[28.5, 43.5, 48.5, 41.5, 52.0]"
Head diameter (cm),35,73,47.9500,"['24*27', '27*27', '26*26.5', '26*26..."
Stem diameter (cm),6,73,8.2200,"[1.7, 2.0, 1.5, 1.4, 1.8]"
Shoot weight before removing wilted leaves (g),50,73,68.4900,"[210.0, 200.0, 212.0, 185.0, 178.0]"
shoot weight after removing wilted leaves(g),50,73,68.4900,"[208, 189, 183, 174, 171]"
Root weight (g),39,73,53.4200,"[33.0, 41.0, 39.0, 15.0, 22.0]"
No. of leaves,21,73,28.7700,"[30.0, 34.0, 26.0, 25.0, 27.0]"
system,6,73,8.2200,"['R1-T1', 'R1-T2', 'R1-T3', 'R2-T1',..."

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,Total weight (g),217.7500,259.0000,41.2500,155.8750,320.8750,1,1.3700
1,Plant height (cm),54.0000,61.2500,7.2500,43.1250,72.1250,3,4.1100
2,Shoot length (cm),12.0000,14.0000,2.0000,9.0000,17.0000,1,1.3700
3,Root length (cm),40.0000,48.1250,8.1250,27.8125,60.3125,1,1.3700
4,Stem diameter (cm),2.0000,2.0000,0.0000,2.0000,2.0000,15,20.5500
5,Shoot weight before removing wilted ...,181.5000,220.2500,38.7500,123.3750,278.3750,1,1.3700
6,shoot weight after removing wilted l...,173.0000,212.0000,39.0000,114.5000,270.5000,2,2.7400
7,Root weight (g),24.0000,41.0000,17.0000,-1.5000,66.5000,8,10.9600

──────────────────────────────────────────────────────────────────────

## 📂 Experiment 2 — Quality Assessment

---

### 🔍 Experiment 2 — seedlings

**Missing Values:**

      missing_count  missing_pct dtype
Date             12     100.0000   str

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 2 column(s) with ≤1 unique value: `experiment`, `Date`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,12,8.3300,['Experiment 2']
Date,0,12,0.0000,[]
plant NO.,12,12,100.0000,"[1, 2, 3, 4, 5]"
plant height (cm),5,12,41.6700,"[11, 13, 12.5, 12, 14]"
shoot length (cm),4,12,33.3300,"[5, 7, 6, 8]"
root length (cm),4,12,33.3300,"[6, 7.5, 8, 7]"
head diameter (cm),11,12,91.6700,"['7*8', '6*7', '5*6', '6*4', '6*4.5']"
stem diameter (cm),2,12,16.6700,"[0.3, 0.2]"
total weight (g),12,12,100.0000,"[5.13, 5, 5.25, 4.85, 5.36]"
shoot weight (g),12,12,100.0000,"[2.41, 2.14, 1.58, 2.45, 1.93]"
root weight (g),12,12,100.0000,"[2.7199999999999998, 2.86, 3.67, 2.3..."
no. of leaves,4,12,33.3300,"[7, 5, 6, 8]"

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — sensor_water_quality

**Missing Values:**

             missing_count  missing_pct dtype
Tme                    718     100.0000   str
pH.                    718     100.0000   str
TDS.                   718     100.0000   str
EC.                    718     100.0000   str
Water temp.            718     100.0000   str
Date                   717      99.8600   str

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 8 column(s) with ≤1 unique value: `experiment`, `replicate`, `Date`, `Tme`, `pH.`, `EC.`, `TDS.`, `Water temp.`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,718,0.1400,['Experiment 2']
replicate,1,718,0.1400,['Replicate 1 T1']
Date,1,718,0.1400,[' ']
Tme,0,718,0.0000,[]
pH.,0,718,0.0000,[]
EC.,0,718,0.0000,[]
TDS.,0,718,0.0000,[]
Water temp.,0,718,0.0000,[]
Date_1,32,718,4.4600,"[datetime.datetime(2024, 4, 16, 0, 0..."
Tme_1,24,718,3.3400,"[datetime.time(10, 0), datetime.time..."
RH%,591,718,82.3100,"[57.77, 54, 52.89, 52.01, 52.46]"
Air temp.,544,718,75.7700,"[28.28, 28.57, 27.68, 28.29, 27.32]"
CO2,681,718,94.8500,"[485.7, 463.92, 450.51, 444.88, 440.13]"

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `Date_1`: `[datetime.datetime(2024, 4, 16, 0, 0), datetime.datetime(2024, 4, 17, 0, 0), datetime.datetime(2024, 4, 18, 0, 0), datetime.datetime(2024, 4, 19, 0, 0), datetime.datetime(2024, 4, 20, 0, 0), datetime.datetime(2024, 4, 21, 0, 0), datetime.datetime(2024, 4, 22, 0, 0), datetime.datetime(2024, 4, 23, 0, 0), datetime.datetime(2024, 4, 24, 0, 0), datetime.datetime(2024, 4, 25, 0, 0)]` (10 unique invalid value(s))

- `Tme_1`: `[datetime.time(10, 0), datetime.time(11, 0), datetime.time(12, 0), datetime.time(13, 0), datetime.time(14, 0), datetime.time(15, 0), datetime.time(16, 0), datetime.time(17, 0), datetime.time(18, 0), datetime.time(19, 0)]` (10 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — portable_water_quality

**Missing Values:**

                           missing_count  missing_pct    dtype
100000_rh_%_col_28                    29     100.0000  float64
140000_air_air_parameters              1       3.4500   object
140000_rh%_col_54                      1       3.4500   object
140000_air_temp_col_55                 1       3.4500   object

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 2 column(s) with ≤1 unique value: `experiment`, `100000_rh_%_col_28`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,29,3.4500,['Experiment 2']
date,29,29,100.0000,"['16/4/2024', '17/4/2024', '18/4/202..."
100000_replicate_1_t1_ph,14,29,48.2800,"[6.8, 6.3, 6.6, 5.9, 6]"
100000_replicate_1_t1_ec,18,29,62.0700,"[1.44, 1.48, 1.72, 1.78, 1.79]"
100000_replicate_1_t1_tds,18,29,62.0700,"[0.72, 0.74, 0.86, 0.89, 0.895]"
100000_replicate_1_t1_water_temp,23,29,79.3100,"[25, 28.3, 25.3, 24.7, 22.8]"
100000_replicate_2_t1_ph,10,29,34.4800,"[7, 6.7, 6.2, 5.8, 5.7]"
100000_replicate_2_t1_ec,20,29,68.9700,"[1.33, 1.37, 1.71, 1.79, 1.75]"
100000_replicate_2_t1_tds,20,29,68.9700,"[0.665, 0.685, 0.855, 0.895, 0.875]"
100000_replicate_2_t1_water_temp,22,29,75.8600,"[25.2, 27.4, 25.8, 25, 24]"
100000_replicate_3_t1_ph,14,29,48.2800,"[7, 6.3, 6.8, 5.6, 5.7]"
100000_replicate_3_t1_ec,21,29,72.4100,"[1.33, 1.37, 1.73, 1.75, 1.78]"
100000_replicate_3_t1_tds,21,29,72.4100,"[0.665, 0.685, 0.865, 0.875, 0.89]"
100000_replicate_3_t1_water_temp,19,29,65.5200,"[24.3, 26.4, 24.8, 24.6, 23.6]"
100000_replicate_1_t2_ph,14,29,48.2800,"[6.9, 6.2, 6.7, 6.1, 5.8]"
100000_replicate_1_t2_ec,22,29,75.8600,"[1.89, 1.91, 2.17, 2.22, 2.2]"
100000_replicate_1_t2_tds,22,29,75.8600,"[0.945, 0.955, 1.085, 1.11, 1.1]"
100000_replicate_1_t2_water_temp,23,29,79.3100,"[25, 26.9, 24.6, 25.2, 23.2]"
100000_replicate_2_t2_ph,15,29,51.7200,"[7, 6, 6.5, 5.9, 5.6]"
100000_replicate_2_t2_ec,19,29,65.5200,"[1.95, 1.91, 2.27, 2.3, 2.24]"
100000_replicate_2_t2_tds,19,29,65.5200,"[0.975, 0.955, 1.135, 1.15, 1.12]"
100000_replicate_2_t2_water_temp,27,29,93.1000,"[26, 26.9, 24.9, 24, 25.4]"
100000_replicate_3_t2_ph,13,29,44.8300,"[6.9, 6.1, 6.3, 5.8, 6.7]"
100000_replicate_3_t2_ec,18,29,62.0700,"[1.8, 1.9, 2.22, 2.27, 2.25]"
100000_replicate_3_t2_tds,18,29,62.0700,"[0.9, 0.95, 1.11, 1.135, 1.125]"
100000_replicate_3_t2_water_temp,27,29,93.1000,"[25.3, 28.4, 25.6, 25.8, 24.7]"
100000_air_air_parameters,24,29,82.7600,"[7750, '-', 77040, 70360, 7254]"
100000_air_temp_col_26,24,29,82.7600,"[26.9, '-', 24.2, 28.5, 23.9]"
100000_rh_%_col_27,25,29,86.2100,"[63.5, '-', 55.3, 53.6, 44.2]"
100000_rh_%_col_28,0,29,0.0000,[]
140000_replicate_1_t1_ph,13,29,44.8300,"['-', 6.8, 6.1, 6, 5.7]"
140000_replicate_1_t1_ec,18,29,62.0700,"['-', 1.75, 1.8, 1.79, 1.78]"
140000_replicate_1_t1_tds,18,29,62.0700,"['-', 0.875, 0.9, 0.895, 0.89]"
140000_replicate_1_t1_water_temp,25,29,86.2100,"['-', 25.8, 27.8, 28.3, 23.9]"
140000_replicate_2_t1_ph,13,29,44.8300,"['-', 6.7, 5.9, 6.2, 5.7]"
140000_replicate_2_t1_ec,16,29,55.1700,"['-', 1.75, 1.76, 1.74, 1.73]"
140000_replicate_2_t1_tds,16,29,55.1700,"['-', 0.875, 0.88, 0.87, 0.865]"
140000_replicate_2_t1_water_temp,21,29,72.4100,"['-', 25.8, 27.6, 27.8, 25.6]"
140000_replicate_3_t1_ph,13,29,44.8300,"['-', 6.8, 6.3, 5.8, 6.2]"
140000_replicate_3_t1_ec,20,29,68.9700,"['-', 1.72, 1.75, 1.78, 1.73]"
140000_replicate_3_t1_tds,20,29,68.9700,"['-', 0.86, 0.875, 0.89, 0.865]"
140000_replicate_3_t1_water_temp,23,29,79.3100,"['-', 25.8, 28.2, 27.6, 26]"
140000_replicate_1_t2_ph,15,29,51.7200,"['-', 6.7, 6.2, 5.7, 6]"
140000_replicate_1_t2_ec,18,29,62.0700,"['-', 2.17, 2.21, 2.3, 2.26]"
140000_replicate_1_t2_tds,18,29,62.0700,"['-', 1.085, 1.105, 1.15, 1.13]"
140000_replicate_1_t2_water_temp,23,29,79.3100,"['-', 26, 28.3, 25.8, 26.2]"
140000_replicate_2_t2_ph,12,29,41.3800,"['-', 6.5, 6.1, 6, 5.9]"
140000_replicate_2_t2_ec,19,29,65.5200,"['-', 2.27, 2.23, 2.28, 2.3]"
140000_replicate_2_t2_tds,19,29,65.5200,"['-', 1.135, 1.115, 1.14, 1.15]"
140000_replicate_2_t2_water_temp,25,29,86.2100,"['-', 25.8, 28.6, 27, 21.3]"
140000_replicate_3_t2_ph,14,29,48.2800,"['-', 6.3, 6.9, 5.7, 6.2]"
140000_replicate_3_t2_ec,15,29,51.7200,"['-', 2.2, 2.25, 2.26, 2.24]"
140000_replicate_3_t2_tds,15,29,51.7200,"['-', 1.1, 1.125, 1.13, 1.12]"
140000_replicate_3_t2_water_temp,19,29,65.5200,"['-', 26.6, 27.6, 27.8, 27.1]"
140000_air_air_parameters,22,29,75.8600,"['-', 79490, 6212, 5162, 49230]"
140000_rh%_col_54,20,29,68.9700,"['-', 24.9, 28.1, 25.6, 31.4]"
140000_air_temp_col_55,21,29,72.4100,"['-', 55.6, 55.3, 62.1, 59.8]"

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `date`: `['16/4/2024', '17/4/2024', '18/4/2024', '19/4/2024', '20/4/2024', '21/4/2024', '22/4/2024', '23/4/2024', '24/4/2024', '25/4/2024']` (10 unique invalid value(s))

- `100000_air_air_parameters`: `['-']` (1 unique invalid value(s))

- `100000_air_temp_col_26`: `['-']` (1 unique invalid value(s))

- `100000_rh_%_col_27`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t1_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t1_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t1_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t1_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t1_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t1_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t1_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t1_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t1_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t2_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t2_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t2_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t2_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t2_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t2_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t2_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t2_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t2_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_air_air_parameters`: `['-']` (1 unique invalid value(s))

- `140000_rh%_col_54`: `['-']` (1 unique invalid value(s))

- `140000_air_temp_col_55`: `['-']` (1 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — nutrients_date

**Missing Values:**

      missing_count  missing_pct   dtype
date             22      91.6700  object

**Duplicate Rows:** ⚠️ **21** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,24,4.1700,['Experiment 2']
date,2,24,8.3300,"[datetime.datetime(2024, 2, 5, 0, 0)..."

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `date`: `[datetime.datetime(2024, 2, 5, 0, 0), 'Total ']` (2 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — nutrients_nutrient_solution_addition_(a+b)_ml

**Missing Values:**

                missing_count  missing_pct   dtype
Replicate_1_T1             21      87.5000  object
Replicate_2_T1             21      87.5000  object
Replicate_3_T1             21      87.5000  object
Replicate_1_T2             21      87.5000  object
Replicate_2_T2             21      87.5000  object
Replicate_3_T2             21      87.5000  object

**Duplicate Rows:** ⚠️ **20** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct     sample_values
experiment                 1          24      4.1700  ['Experiment 2']
Replicate_1_T1             3          24     12.5000      [22, 15, 37]
Replicate_2_T1             3          24     12.5000      [22, 10, 32]
Replicate_3_T1             3          24     12.5000      [22, 10, 32]
Replicate_1_T2             3          24     12.5000      [22, 10, 32]
Replicate_2_T2             3          24     12.5000      [22, 10, 32]
Replicate_3_T2             3          24     12.5000      [22, 25, 47]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — nutrients_water_consumption_l

**Missing Values:**

                missing_count  missing_pct   dtype
Replicate_1_T1             22      91.6700  object
Replicate_2_T1             22      91.6700  object
Replicate_3_T1             22      91.6700  object
Replicate_1_T2             22      91.6700  object
Replicate_2_T2             22      91.6700  object
Replicate_3_T2             22      91.6700  object

**Duplicate Rows:** ⚠️ **22** exact duplicates found.

**Constant Columns:** ⚠️ 7 column(s) with ≤1 unique value: `experiment`, `Replicate_1_T1`, `Replicate_2_T1`, `Replicate_3_T1`, `Replicate_1_T2`, `Replicate_2_T2`, `Replicate_3_T2`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct     sample_values
experiment                 1          24      4.1700  ['Experiment 2']
Replicate_1_T1             1          24      4.1700              [40]
Replicate_2_T1             1          24      4.1700              [40]
Replicate_3_T1             1          24      4.1700              [35]
Replicate_1_T2             1          24      4.1700              [40]
Replicate_2_T2             1          24      4.1700              [40]
Replicate_3_T2             1          24      4.1700              [30]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — harvest

**Missing Values:**

                                          missing_count  missing_pct    dtype
Plant No.                                             6       7.6900  float64
Plant height (cm)                                     6       7.6900  float64
Shoot length (cm)                                     6       7.6900  float64
Root length (cm)                                      6       7.6900  float64
Head diameter (cm)                                    6       7.6900      str
Stem diameter (cm)                                    6       7.6900  float64
Shoot weight before removing wilted l...              6       7.6900  float64
shoot weight after removing wilted le...              6       7.6900  float64
Root weight (g)                                       6       7.6900  float64
No. of leaves                                         6       7.6900  float64

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,78,1.2800,['Experiment 2']
Plant No.,12,78,15.3800,"[1.0, 2.0, 3.0, 4.0, 5.0]"
Total weight (g),65,78,83.3300,"[317.0, 270.0, 311.0, 360.0, 326.0]"
Plant height (cm),27,78,34.6200,"[55.0, 50.0, 52.0, 70.0, 67.0]"
Shoot length (cm),13,78,16.6700,"[15.0, 16.0, 14.0, 17.0, 19.0]"
Root length (cm),35,78,44.8700,"[40.0, 34.0, 38.0, 53.0, 48.0]"
Head diameter (cm),37,78,47.4400,"['25*26', '30*25', '29*30', '30*31',..."
Stem diameter (cm),5,78,6.4100,"[2.0, 2.5, 2.1, 1.8, 1.5]"
Shoot weight before removing wilted leaves (g),54,78,69.2300,"[272.0, 248.0, 292.0, 300.0, 227.0]"
shoot weight after removing wilted leaves(g),58,78,74.3600,"[264.0, 239.0, 283.0, 293.0, 300.0]"
Root weight (g),30,78,38.4600,"[45.0, 22.0, 19.0, 60.0, 26.0]"
No. of leaves,20,78,25.6400,"[37.0, 29.0, 38.0, 34.0, 33.0]"
system,6,78,7.6900,"['R1-T1', 'R2-T1', 'R3-T1', 'R1-T2',..."

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,Stem diameter (cm),2.0000,2.0000,0.0000,2.0000,2.0000,7,8.9700
1,Shoot weight before removing wilted ...,265.7500,318.5000,52.7500,186.6250,397.6250,1,1.2800
2,shoot weight after removing wilted l...,264.0000,319.2500,55.2500,181.1250,402.1250,1,1.2800
3,Root weight (g),30.0000,43.0000,13.0000,10.5000,62.5000,1,1.2800
4,No. of leaves,38.7500,44.2500,5.5000,30.5000,52.5000,1,1.2800

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — taste_test

**Missing Values:**

    missing_count  missing_pct   dtype
13              6      85.7100     str
0               1      14.2900  object
3               1      14.2900     str
4               1      14.2900  object
5               1      14.2900  object
2               1      14.2900     str
6               1      14.2900  object
7               1      14.2900  object
9               1      14.2900  object
8               1      14.2900  object
10              1      14.2900  object
11              1      14.2900  object
12              1      14.2900  object
15              1      14.2900  object
16              1      14.2900  object
17              1      14.2900  object
18              1      14.2900  object
19              1      14.2900  object
20              1      14.2900  object
21              1      14.2900  object
22              1      14.2900  object
23              1      14.2900  object

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 2 column(s) with ≤1 unique value: `experiment`, `13`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,7,14.2900,['Experiment 2']
0,6,7,85.7100,"['Timestamp', datetime.datetime(2024..."
1,7,7,100.0000,"['R1', 'Age', 22, 26, 31]"
2,3,7,42.8600,"['Gender ', 'Male', 'Female']"
3,3,7,42.8600,"['Smell (الرائحة)', 'Fresh', 'Normal']"
4,5,7,71.4300,"['Appearance (المظهر)', 9, 6, 7, '10..."
5,4,7,57.1400,"['Flavor (الطعم)', 8, 6, 9]"
6,5,7,71.4300,"['Crunchy (مقرمش)', 9, 8, 7, 5]"
7,4,7,57.1400,"['Sweetness (الحلاوة )', '5 (Extreme..."
8,5,7,71.4300,"['Bitter (المرارة)', '5 (Extremely B..."
9,4,7,57.1400,"['Color (اللون)', 5, 4, 3]"
10,4,7,57.1400,"['After taste (المذاق الأخير)', 9, 8..."
11,5,7,71.4300,"['Acceptance', 9, 8, 6, '10 (like ex..."
12,4,7,57.1400,"['Overall evaluation (The best)', '1..."
13,1,7,14.2900,['Comments']
14,4,7,57.1400,"['R2', 'Smell (الرائحة)', 'Fresh', '..."
15,5,7,71.4300,"['Appearance (المظهر)', 9, 7, 8, '10..."
16,4,7,57.1400,"['Flavor (الطعم)', 9, 7, 8]"
17,3,7,42.8600,"['Crunchy (مقرمش)', 9, 7]"
18,4,7,57.1400,"['Sweetness (الحلاوة )', '5 (Extreme..."
19,4,7,57.1400,"['Bitter (المرارة)', '5 (Extremely B..."
20,3,7,42.8600,"['Color (اللون)', 5, 4]"
21,4,7,57.1400,"['After taste (المذاق الأخير)', '10 ..."
22,5,7,71.4300,"['Acceptance', '10 (like extremely )..."
23,5,7,71.4300,"['Overall evaluation (The best)', 9,..."

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `0`: `['Timestamp', datetime.datetime(2024, 5, 15, 16, 28, 34, 895000), datetime.datetime(2024, 5, 15, 16, 30, 37, 820000), datetime.datetime(2024, 5, 15, 16, 33, 12, 614000), datetime.datetime(2024, 5, 15, 16, 33, 33, 60000), datetime.datetime(2024, 5, 15, 17, 12, 17, 188000)]` (6 unique invalid value(s))

- `1`: `['R1', 'Age']` (2 unique invalid value(s))

- `4`: `['Appearance (المظهر)', '10 (like extremely )']` (2 unique invalid value(s))

- `5`: `['Flavor (الطعم)']` (1 unique invalid value(s))

- `6`: `['Crunchy (مقرمش)']` (1 unique invalid value(s))

- `7`: `['Sweetness (الحلاوة )', '5 (Extremely sweet  )']` (2 unique invalid value(s))

- `8`: `['Bitter (المرارة)', '5 (Extremely Bitter )', '1 (Not at all bitter)']` (3 unique invalid value(s))

- `9`: `['Color (اللون)']` (1 unique invalid value(s))

- `10`: `['After taste (المذاق الأخير)']` (1 unique invalid value(s))

- `11`: `['Acceptance', '10 (like extremely )']` (2 unique invalid value(s))

- `12`: `['Overall evaluation (The best)', '10 (like extremely )']` (2 unique invalid value(s))

- `15`: `['Appearance (المظهر)', '10 (like extremely )']` (2 unique invalid value(s))

- `16`: `['Flavor (الطعم)']` (1 unique invalid value(s))

- `17`: `['Crunchy (مقرمش)']` (1 unique invalid value(s))

- `18`: `['Sweetness (الحلاوة )', '5 (Extremely sweet  )']` (2 unique invalid value(s))

- `19`: `['Bitter (المرارة)', '5 (Extremely Bitter )', '1 (Not at all bitter)']` (3 unique invalid value(s))

- `20`: `['Color (اللون)']` (1 unique invalid value(s))

- `21`: `['After taste (المذاق الأخير)', '10 (like extremely )']` (2 unique invalid value(s))

- `22`: `['Acceptance', '10 (like extremely )']` (2 unique invalid value(s))

- `23`: `['Overall evaluation (The best)', '10 (like extremely )']` (2 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — form_responses

**Missing Values:**

    missing_count  missing_pct   dtype
13              6      85.7100     str
24              6      85.7100     str
0               1      14.2900  object
4               1      14.2900  object
5               1      14.2900  object
2               1      14.2900     str
3               1      14.2900     str
7               1      14.2900  object
6               1      14.2900  object
10              1      14.2900  object
8               1      14.2900  object
11              1      14.2900  object
12              1      14.2900  object
15              1      14.2900  object
9               1      14.2900  object
16              1      14.2900  object
17              1      14.2900  object
19              1      14.2900  object
18              1      14.2900  object
20              1      14.2900  object
21              1      14.2900  object
22              1      14.2900  object
23              1      14.2900  object

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 3 column(s) with ≤1 unique value: `experiment`, `13`, `24`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,7,14.2900,['Experiment 2']
0,6,7,85.7100,"['Timestamp', datetime.datetime(2024..."
1,7,7,100.0000,"['R1', 'Age', 22, 26, 31]"
2,3,7,42.8600,"['Gender ', 'Male', 'Female']"
3,3,7,42.8600,"['Smell (الرائحة)', 'Fresh', 'Normal']"
4,5,7,71.4300,"['Appearance (المظهر)', 9, 6, 7, '10..."
5,4,7,57.1400,"['Flavor (الطعم)', 8, 6, 9]"
6,5,7,71.4300,"['Crunchy (مقرمش)', 9, 8, 7, 5]"
7,4,7,57.1400,"['Sweetness (الحلاوة )', '5 (Extreme..."
8,5,7,71.4300,"['Bitter (المرارة)', '5 (Extremely B..."
9,4,7,57.1400,"['Color (اللون)', 5, 4, 3]"
10,4,7,57.1400,"['After taste (المذاق الأخير)', 9, 8..."
11,5,7,71.4300,"['Acceptance', 9, 8, 6, '10 (like ex..."
12,4,7,57.1400,"['Overall evaluation (The best)', '1..."
13,1,7,14.2900,['Comments']
14,4,7,57.1400,"['R2', 'Smell (الرائحة)', 'Fresh', '..."
15,5,7,71.4300,"['Appearance (المظهر)', 9, 7, 8, '10..."
16,4,7,57.1400,"['Flavor (الطعم)', 9, 7, 8]"
17,3,7,42.8600,"['Crunchy (مقرمش)', 9, 7]"
18,4,7,57.1400,"['Sweetness (الحلاوة )', '5 (Extreme..."
19,4,7,57.1400,"['Bitter (المرارة)', '5 (Extremely B..."
20,3,7,42.8600,"['Color (اللون)', 5, 4]"
21,4,7,57.1400,"['After taste (المذاق الأخير)', '10 ..."
22,5,7,71.4300,"['Acceptance', '10 (like extremely )..."
23,5,7,71.4300,"['Overall evaluation (The best)', 9,..."
24,1,7,14.2900,['Comments']

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `0`: `['Timestamp', datetime.datetime(2024, 5, 15, 16, 28, 34, 895000), datetime.datetime(2024, 5, 15, 16, 30, 37, 820000), datetime.datetime(2024, 5, 15, 16, 33, 12, 614000), datetime.datetime(2024, 5, 15, 16, 33, 33, 60000), datetime.datetime(2024, 5, 15, 17, 12, 17, 188000)]` (6 unique invalid value(s))

- `1`: `['R1', 'Age']` (2 unique invalid value(s))

- `4`: `['Appearance (المظهر)', '10 (like extremely )']` (2 unique invalid value(s))

- `5`: `['Flavor (الطعم)']` (1 unique invalid value(s))

- `6`: `['Crunchy (مقرمش)']` (1 unique invalid value(s))

- `7`: `['Sweetness (الحلاوة )', '5 (Extremely sweet  )']` (2 unique invalid value(s))

- `8`: `['Bitter (المرارة)', '5 (Extremely Bitter )', '1 (Not at all bitter)']` (3 unique invalid value(s))

- `9`: `['Color (اللون)']` (1 unique invalid value(s))

- `10`: `['After taste (المذاق الأخير)']` (1 unique invalid value(s))

- `11`: `['Acceptance', '10 (like extremely )']` (2 unique invalid value(s))

- `12`: `['Overall evaluation (The best)', '10 (like extremely )']` (2 unique invalid value(s))

- `15`: `['Appearance (المظهر)', '10 (like extremely )']` (2 unique invalid value(s))

- `16`: `['Flavor (الطعم)']` (1 unique invalid value(s))

- `17`: `['Crunchy (مقرمش)']` (1 unique invalid value(s))

- `18`: `['Sweetness (الحلاوة )', '5 (Extremely sweet  )']` (2 unique invalid value(s))

- `19`: `['Bitter (المرارة)', '5 (Extremely Bitter )', '1 (Not at all bitter)']` (3 unique invalid value(s))

- `20`: `['Color (اللون)']` (1 unique invalid value(s))

- `21`: `['After taste (المذاق الأخير)', '10 (like extremely )']` (2 unique invalid value(s))

- `22`: `['Acceptance', '10 (like extremely )']` (2 unique invalid value(s))

- `23`: `['Overall evaluation (The best)', '10 (like extremely )']` (2 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

## 📂 Experiment 3 — Quality Assessment

---

### 🔍 Experiment 3 — seedlings

**Missing Values:** ✅ None detected.

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,10,10.0000,['Experiment 3']
Plant NO.,10,10,100.0000,"[1, 2, 3, 4, 5]"
Plant height (cm),7,10,70.0000,"[16.5, 15, 16, 12.5, 13.5]"
Shoot length (cm),4,10,40.0000,"[8, 7, 6, 5.5]"
Root length (cm),6,10,60.0000,"[8.5, 8, 6.5, 7.5, 9]"
Head diameter (cm),10,10,100.0000,"['9*5', '8*5', '10*9', '6.5*6', '6.5..."
Stem diameter (cm),2,10,20.0000,"[0.3, 0.4]"
Total weight (g),3,10,30.0000,"[6, 5, 4]"
Shoot weight (g),3,10,30.0000,"[4, 3, 2]"
Root weight (g),3,10,30.0000,"[2, 3, 1]"
No. of leaves,4,10,40.0000,"[12, 10, 11, 13]"

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — sensor_water_quality

**Missing Values:**

             missing_count  missing_pct dtype
Tme                    712     100.0000   str
pH                     712     100.0000   str
TDS                    712     100.0000   str
EC                     712     100.0000   str
Water temp.            712     100.0000   str
Date                   711      99.8600   str

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 8 column(s) with ≤1 unique value: `experiment`, `replicate`, `Date`, `Tme`, `pH`, `EC`, `TDS`, `Water temp.`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,712,0.1400,['Experiment 3']
replicate,1,712,0.1400,['Replicate 1 T1']
Date,1,712,0.1400,[' ']
Tme,0,712,0.0000,[]
pH,0,712,0.0000,[]
EC,0,712,0.0000,[]
TDS,0,712,0.0000,[]
Water temp.,0,712,0.0000,[]
Date_1,32,712,4.4900,"[datetime.datetime(2024, 5, 19, 0, 0..."
Tme_1,24,712,3.3700,"[datetime.time(17, 0), datetime.time..."
RH%,595,712,83.5700,"[51.62, 53.18, 54.38, 55.19, 57.2]"
Air temp.,501,712,70.3700,"[24.81, 23.45, 24.87, 25.29, 25.28]"
CO2,679,712,95.3700,"[415.25, 415.76, 424.68, 432.47, 435..."

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `Date_1`: `[datetime.datetime(2024, 5, 19, 0, 0), datetime.datetime(2024, 5, 20, 0, 0), datetime.datetime(2024, 5, 21, 0, 0), datetime.datetime(2024, 5, 22, 0, 0), datetime.datetime(2024, 5, 23, 0, 0), datetime.datetime(2024, 5, 24, 0, 0), datetime.datetime(2024, 5, 25, 0, 0), datetime.datetime(2024, 5, 26, 0, 0), datetime.datetime(2024, 5, 27, 0, 0), datetime.datetime(2024, 5, 28, 0, 0)]` (10 unique invalid value(s))

- `Tme_1`: `[datetime.time(17, 0), datetime.time(18, 0), datetime.time(19, 0), datetime.time(20, 0), datetime.time(21, 0), datetime.time(22, 0), datetime.time(23, 0), datetime.time(0, 0), datetime.time(1, 0), datetime.time(2, 0)]` (10 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — portable_water_quality

**Missing Values:**

                                  missing_count  missing_pct    dtype
100000_rh%_col_28                            33     100.0000  float64
100000_replicate_2_t2_ph                      3       9.0900   object
100000_air_air_parameters                     3       9.0900   object
100000_replicate_3_t2_ph                      3       9.0900   object
100000_air_temp_col_26                        3       9.0900   object
100000_rh%_col_27                             3       9.0900   object
100000_replicate_2_t1_ph                      2       6.0600   object
100000_replicate_2_t2_water_temp              2       6.0600   object
100000_replicate_3_t2_tds                     2       6.0600   object
100000_replicate_2_t2_tds                     2       6.0600   object
140000_replicate_3_t1_ph                      2       6.0600   object
140000_replicate_2_t1_water_temp              2       6.0600   object
140000_replicate_2_t1_tds                     2       6.0600   object
140000_replicate_2_t1_ec                      2       6.0600   object
140000_replicate_2_t1_ph                      2       6.0600   object
140000_replicate_1_t1_water_temp              2       6.0600   object
140000_replicate_1_t1_tds                     2       6.0600   object
140000_replicate_1_t1_ec                      2       6.0600   object
140000_replicate_1_t1_ph                      2       6.0600   object
100000_replicate_3_t2_water_temp              2       6.0600   object
100000_replicate_3_t2_ec                      2       6.0600   object
100000_replicate_3_t1_ph                      2       6.0600   object
100000_replicate_2_t2_ec                      2       6.0600   object
100000_replicate_1_t2_water_temp              2       6.0600   object
140000_replicate_3_t1_water_temp              2       6.0600   object
140000_replicate_1_t2_ph                      2       6.0600   object
140000_replicate_1_t2_ec                      2       6.0600   object
140000_replicate_1_t2_tds                     2       6.0600   object
140000_replicate_1_t2_water_temp              2       6.0600   object
140000_replicate_2_t2_ph                      2       6.0600   object
140000_replicate_2_t2_ec                      2       6.0600   object
140000_replicate_2_t2_tds                     2       6.0600   object
140000_replicate_2_t2_water_temp              2       6.0600   object
140000_replicate_3_t2_ph                      2       6.0600   object
140000_replicate_3_t2_ec                      2       6.0600   object
140000_replicate_3_t2_tds                     2       6.0600   object
140000_replicate_3_t2_water_temp              2       6.0600   object
140000_air_air_parameters                     2       6.0600   object
140000_replicate_3_t1_ec                      2       6.0600   object
140000_replicate_3_t1_tds                     2       6.0600   object
140000_air_temp_col_54                        2       6.0600   object
140000_rh%_col_55                             2       6.0600   object
100000_replicate_3_t1_water_temp              1       3.0300   object
100000_replicate_2_t1_water_temp              1       3.0300   object
100000_replicate_1_t2_ec                      1       3.0300   object
100000_replicate_1_t2_ph                      1       3.0300   object
100000_replicate_3_t1_ec                      1       3.0300   object
100000_replicate_3_t1_tds                     1       3.0300   object
100000_replicate_1_t1_tds                     1       3.0300   object
date                                          1       3.0300   object
100000_replicate_1_t1_ec                      1       3.0300   object
100000_replicate_1_t1_ph                      1       3.0300   object
100000_replicate_2_t1_ec                      1       3.0300   object
100000_replicate_1_t1_water_temp              1       3.0300   object
100000_replicate_1_t2_tds                     1       3.0300   object
100000_replicate_2_t1_tds                     1       3.0300   object

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 2 column(s) with ≤1 unique value: `experiment`, `100000_rh%_col_28`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,33,3.0300,['Experiment 3']
date,32,33,96.9700,"['19/5/2024', '20/5/2024', '21/5/202..."
100000_replicate_1_t1_ph,19,33,57.5800,"['-', 6.9, 7, 7.2, 7.1]"
100000_replicate_1_t1_ec,29,33,87.8800,"['-', 2.17, 2.6, 1.74, 1.94]"
100000_replicate_1_t1_tds,29,33,87.8800,"['-', 1.085, 1.3, 0.87, 0.97]"
100000_replicate_1_t1_water_temp,22,33,66.6700,"['-', 21.4, 21.7, 22.3, 19.6]"
100000_replicate_2_t1_ph,16,33,48.4800,"['-', 7.2, 6.9, 6.6, 6.7]"
100000_replicate_2_t1_ec,26,33,78.7900,"['-', 2.62, 2.63, 2.32, 2.52]"
100000_replicate_2_t1_tds,26,33,78.7900,"['-', 1.31, 1.315, 1.16, 1.26]"
100000_replicate_2_t1_water_temp,21,33,63.6400,"['-', 21.3, 21.7, 22.2, 20.8]"
100000_replicate_3_t1_ph,16,33,48.4800,"['-', 7.6, 7.1, 7.2, 7.4]"
100000_replicate_3_t1_ec,22,33,66.6700,"['-', 2.6, 2.55, 1.75, 1.98]"
100000_replicate_3_t1_tds,22,33,66.6700,"['-', 1.3, 1.275, 0.875, 0.99]"
100000_replicate_3_t1_water_temp,23,33,69.7000,"['-', 21.3, 21.5, 22.5, 20.9]"
100000_replicate_1_t2_ph,12,33,36.3600,"['-', 7.6, 7.5, 7.7, 7.4]"
100000_replicate_1_t2_ec,26,33,78.7900,"['-', 2.4, 2.8, 1.73, 1.91]"
100000_replicate_1_t2_tds,26,33,78.7900,"['-', 1.2, 1.4, 0.865, 0.955]"
100000_replicate_1_t2_water_temp,21,33,63.6400,"['-', 21.3, 22.1, 20.8, 20.4]"
100000_replicate_2_t2_ph,12,33,36.3600,"['-', 7.8, 7.7, 7.6, 7.5]"
100000_replicate_2_t2_ec,27,33,81.8200,"['-', 2.8, 2.5, 1.76, 2.3]"
100000_replicate_2_t2_tds,27,33,81.8200,"['-', 1.4, 1.25, 0.88, 1.15]"
100000_replicate_2_t2_water_temp,21,33,63.6400,"['-', 21.3, 21.2, 22.5, 26.9]"
100000_replicate_3_t2_ph,13,33,39.3900,"['-', 7.7, 7.6, 7.8, 7.5]"
100000_replicate_3_t2_ec,23,33,69.7000,"['-', 2.7, 2.8, 1.75, 2]"
100000_replicate_3_t2_tds,23,33,69.7000,"['-', 1.35, 1.4, 0.875, 1]"
100000_replicate_3_t2_water_temp,21,33,63.6400,"['-', 21.7, 22, 22.8, 21.3]"
100000_air_air_parameters,22,33,66.6700,"['-', 1944, 1664, 33970, 20880]"
100000_air_temp_col_26,18,33,54.5500,"['-', 22.5, 25, 27.4, 26.5]"
100000_rh%_col_27,22,33,66.6700,"['-', 74.6, 73.9, 56.9, 72.8]"
100000_rh%_col_28,0,33,0.0000,[]
140000_replicate_1_t1_ph,16,33,48.4800,"['-', 6.8, 7, 6.7, 6.6]"
140000_replicate_1_t1_ec,23,33,69.7000,"['-', 2.6, 1.97, 1.96, 2.54]"
140000_replicate_1_t1_tds,23,33,69.7000,"['-', 1.3, 0.985, 0.98, 1.27]"
140000_replicate_1_t1_water_temp,25,33,75.7600,"['-', 22.5, 23.9, 22.3, 20.5]"
140000_replicate_2_t1_ph,17,33,51.5200,"['-', 7.1, 7, 6.8, 6.7]"
140000_replicate_2_t1_ec,27,33,81.8200,"['-', 2.62, 2.54, 2.49, 2.02]"
140000_replicate_2_t1_tds,27,33,81.8200,"['-', 1.31, 1.27, 1.245, 1.01]"
140000_replicate_2_t1_water_temp,22,33,66.6700,"['-', 22.8, 23.9, 22.3, 22.5]"
140000_replicate_3_t1_ph,16,33,48.4800,"['-', 7.5, 7.3, 7.2, 7]"
140000_replicate_3_t1_ec,25,33,75.7600,"['-', 2.13, 2, 1.99, 1.65]"
140000_replicate_3_t1_tds,25,33,75.7600,"['-', 1.065, 1, 0.995, 0.825]"
140000_replicate_3_t1_water_temp,23,33,69.7000,"['-', 22.3, 23.8, 22.4, 22.2]"
140000_replicate_1_t2_ph,10,33,30.3000,"['-', 7.4, 7.6, 7.5, 7.3]"
140000_replicate_1_t2_ec,23,33,69.7000,"['-', 2.8, 1.79, 1.06, 1.55]"
140000_replicate_1_t2_tds,23,33,69.7000,"['-', 1.4, 0.895, 0.53, 0.775]"
140000_replicate_1_t2_water_temp,21,33,63.6400,"['-', 23.2, 24, 22.4, 22.2]"
140000_replicate_2_t2_ph,9,33,27.2700,"['-', 7.6, 7.7, 7.5, 7.4]"
140000_replicate_2_t2_ec,23,33,69.7000,"['-', 2.5, 2.2, 2.03, 1.6]"
140000_replicate_2_t2_tds,23,33,69.7000,"['-', 1.25, 1.1, 1.015, 0.8]"
140000_replicate_2_t2_water_temp,21,33,63.6400,"['-', 23.2, 24.1, 26.9, 22.4]"
140000_replicate_3_t2_ph,12,33,36.3600,"['-', 7.5, 7.6, 7.7, 7.4]"
140000_replicate_3_t2_ec,24,33,72.7300,"['-', 2.7, 2.73, 1.99, 1.58]"
140000_replicate_3_t2_tds,24,33,72.7300,"['-', 1.35, 1.365, 0.995, 0.79]"
140000_replicate_3_t2_water_temp,17,33,51.5200,"['-', 23.7, 24.5, 23.6, 22.9]"
140000_air_air_parameters,21,33,63.6400,"['-', 20190, 33360, 33800, 31580]"
140000_air_temp_col_54,20,33,60.6100,"['-', 25.3, 24.9, 26.5, 30.2]"
140000_rh%_col_55,22,33,66.6700,"['-', 67.9, 70.3, 57.5, 61.9]"

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `date`: `['19/5/2024', '20/5/2024', '21/5/2024', '22/5/2024', '23/5/2024', '24\\05\\2024', '25/5/2024', '26\\5\\2024', '27\\5\\2024', '28\\5\\2024']` (10 unique invalid value(s))

- `100000_replicate_1_t1_ph`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t1_ec`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t1_tds`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t1_ph`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t1_ec`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t1_tds`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t1_ph`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t1_ec`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t1_tds`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t2_ph`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t2_ec`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t2_tds`: `['-']` (1 unique invalid value(s))

- `100000_replicate_1_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t2_ph`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t2_ec`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t2_tds`: `['-']` (1 unique invalid value(s))

- `100000_replicate_2_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t2_ph`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t2_ec`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t2_tds`: `['-']` (1 unique invalid value(s))

- `100000_replicate_3_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `100000_air_air_parameters`: `['-']` (1 unique invalid value(s))

- `100000_air_temp_col_26`: `['-']` (1 unique invalid value(s))

- `100000_rh%_col_27`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t1_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t1_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t1_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t1_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t1_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t1_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t1_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t1_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t1_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t1_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t2_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t2_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t2_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_1_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t2_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t2_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t2_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_2_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t2_ph`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t2_ec`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t2_tds`: `['-']` (1 unique invalid value(s))

- `140000_replicate_3_t2_water_temp`: `['-']` (1 unique invalid value(s))

- `140000_air_air_parameters`: `['-']` (1 unique invalid value(s))

- `140000_air_temp_col_54`: `['-']` (1 unique invalid value(s))

- `140000_rh%_col_55`: `['-']` (1 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — nutrients_date

**Missing Values:**

      missing_count  missing_pct   dtype
date              8      72.7300  object

**Duplicate Rows:** ⚠️ **7** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,11,9.0900,['Experiment 3']
date,3,11,27.2700,"['24/5/2024', datetime.datetime(2024..."

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `date`: `['24/5/2024', datetime.datetime(2024, 5, 6, 0, 0), 'Total ']` (3 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — nutrients_nutrient_solution_addition_(a+b)_ml

**Missing Values:**

                missing_count  missing_pct   dtype
Replicate_1_T1              8      72.7300  object
Replicate_2_T1              8      72.7300  object
Replicate_3_T1              8      72.7300  object
Replicate_1_T2              8      72.7300  object
Replicate_2_T2              8      72.7300  object
Replicate_3_T2              8      72.7300  object

**Duplicate Rows:** ⚠️ **7** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct     sample_values
experiment                 1          11      9.0900  ['Experiment 3']
Replicate_1_T1             3          11     27.2700   [180, 197, 377]
Replicate_2_T1             3          11     27.2700   [180, 173, 353]
Replicate_3_T1             3          11     27.2700   [180, 187, 367]
Replicate_1_T2             3          11     27.2700   [180, 188, 368]
Replicate_2_T2             3          11     27.2700   [180, 187, 367]
Replicate_3_T2             3          11     27.2700   [180, 190, 370]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — nutrients_water_consumption_l

**Missing Values:**

                missing_count  missing_pct   dtype
Replicate_1_T1              7      63.6400  object
Replicate_2_T1              7      63.6400  object
Replicate_3_T1              7      63.6400  object
Replicate_1_T2              7      63.6400  object
Replicate_2_T2              7      63.6400  object
Replicate_3_T2              7      63.6400  object

**Duplicate Rows:** ⚠️ **6** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct       sample_values
experiment                 1          11      9.0900    ['Experiment 3']
Replicate_1_T1             4          11     36.3600  [100, 45, 50, 195]
Replicate_2_T1             4          11     36.3600  [100, 40, 50, 190]
Replicate_3_T1             4          11     36.3600  [100, 30, 50, 180]
Replicate_1_T2             4          11     36.3600  [100, 30, 50, 180]
Replicate_2_T2             4          11     36.3600  [100, 35, 50, 185]
Replicate_3_T2             4          11     36.3600  [100, 40, 50, 190]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — nutrients_acid_consumption_ml

**Missing Values:**

                missing_count  missing_pct   dtype
Replicate_1_T1              8      72.7300  object
Replicate_2_T1              8      72.7300  object
Replicate_3_T1              8      72.7300  object
Replicate_1_T2              8      72.7300  object
Replicate_2_T2              8      72.7300  object
Replicate_3_T2              8      72.7300  object

**Duplicate Rows:** ⚠️ **8** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct     sample_values
experiment                 1          11      9.0900  ['Experiment 3']
Replicate_1_T1             2          11     18.1800          [15, 30]
Replicate_2_T1             2          11     18.1800          [15, 30]
Replicate_3_T1             2          11     18.1800          [15, 30]
Replicate_1_T2             2          11     18.1800          [15, 30]
Replicate_2_T2             2          11     18.1800          [15, 30]
Replicate_3_T2             2          11     18.1800          [15, 30]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — harvest

**Missing Values:**

           missing_count  missing_pct   dtype
Plant No.              6       7.2300  object
H.D (cm)               6       7.2300     str

**Duplicate Rows:** ⚠️ **4** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,83,1.2000,['Experiment 3']
system,7,83,8.4300,"['R1T1', 'System ', 'R2T1', 'R3T1', ..."
Plant No.,13,83,15.6600,"[1, 2, 3, 4, 5]"
Plant height (cm),34,83,40.9600,"[60, 75, 100, 72, 76]"
Shoot length (cm),15,83,18.0700,"[20, 19, 17, 15, 16]"
Root length (cm),36,83,43.3700,"[40, 41, 58, 83, 57]"
H.D (cm),51,83,61.4500,"['30*31', '29*31', '28*30', '29*29',..."
Total weight (g),62,83,74.7000,"[328, 252, 294, 331, 357]"
Stem diameter (cm),10,83,12.0500,"[1, 1.5, 1.2, 1.141666667, 'Stem dia..."
Shoot weight before removing wilted leaves (g),65,83,78.3100,"[271, 244, 239, 295, 317]"
Shoot weight after removing wilted leaves (g),67,83,80.7200,"[269, 243, 237, 292, 317]"
Root weight (g),36,83,43.3700,"[57, 8, 55, 36, 40]"
No.of leaves,26,83,31.3300,"[42, 46, 43, 40, 36]"

**Invalid Numeric Values (non-numeric in expected numeric columns):**

- `Plant No.`: `['Plant No.']` (1 unique invalid value(s))

- `Plant height (cm)`: `['Plant height (cm)']` (1 unique invalid value(s))

- `Shoot length (cm)`: `['Shoot length (cm)']` (1 unique invalid value(s))

- `Root length (cm)`: `['Root length (cm)']` (1 unique invalid value(s))

- `Total weight (g)`: `['Total weight (g)']` (1 unique invalid value(s))

- `Stem diameter (cm)`: `['Stem diameter (cm)']` (1 unique invalid value(s))

- `Shoot weight before removing wilted leaves (g)`: `['Shoot weight before removing wilted leaves (g) ']` (1 unique invalid value(s))

- `Shoot weight after removing wilted leaves (g)`: `['Shoot weight after removing wilted leaves (g) ']` (1 unique invalid value(s))

- `Root weight (g)`: `['Root weight (g) ']` (1 unique invalid value(s))

- `No.of leaves`: `['No.of leaves ']` (1 unique invalid value(s))

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

2026-07-15 19:49:09,850 | INFO | Quality assessment complete for all datasets.

──────────────────────────────────────────────────────────────────────

---

## 6 · Cleaning

### Cleaning Philosophy

We apply **only safe, reversible, non-destructive** transformations:

| ✅ Allowed | ❌ Not Allowed |
|---|---|
| Trim whitespace from strings | Delete rows due to outliers |
| Remove exact duplicate rows | Remove suspicious values |
| Standardize column names (snake_case) | Fill missing values without justification |
| Fix obvious datatype issues | Drop columns with partial data |
| Convert date strings to datetime | Impute scientific measurements |
| Replace dash/hyphen placeholders with NaN | Modify measurement values |

Every cleaning step shows: **reason**, **before**, and **after**.

In [20]:
# ==========================================================================
# Cleaning utility functions
# ==========================================================================

def standardize_column_names(df: pd.DataFrame) -> pd.DataFrame:
    """
    Standardize column names to lowercase snake_case.
    Removes trailing/leading whitespace, replaces spaces and special chars.
    """
    df = df.copy()
    new_cols = []
    for col in df.columns:
        c = str(col).strip()
        c = c.lower()
        c = c.replace(" ", "_").replace(".", "").replace("(", "").replace(")", "")
        c = c.replace("__", "_").replace("___", "_")
        c = c.rstrip("_")
        new_cols.append(c)
    df.columns = new_cols
    return df


def trim_string_whitespace(df: pd.DataFrame) -> pd.DataFrame:
    """
    Trim leading/trailing whitespace from all string columns.
    """
    df = df.copy()
    str_cols = df.select_dtypes(include=["object", "string"]).columns
    for col in str_cols:
        df[col] = df[col].astype(str).str.strip()
        # Restore NaN for values that were 'nan' strings
        df[col] = df[col].replace({"nan": np.nan, "NaT": np.nan, "": np.nan, "None": np.nan})
    return df


def replace_dash_placeholders(df: pd.DataFrame) -> pd.DataFrame:
    """
    Replace dash/hyphen placeholder values with NaN.
    These are commonly used in the raw data to indicate no measurement.
    """
    df = df.copy()
    dash_patterns = ["-", "--", "- ", " -", "N/A", "n/a", "NA", "na"]
    df = df.replace(dash_patterns, np.nan)
    return df


def remove_exact_duplicates(df: pd.DataFrame) -> Tuple[pd.DataFrame, int]:
    """
    Remove exact duplicate rows. Returns (cleaned_df, n_removed).
    """
    n_before = len(df)
    df_clean = df.drop_duplicates().reset_index(drop=True)
    n_removed = n_before - len(df_clean)
    return df_clean, n_removed


def remove_fully_empty_rows(df: pd.DataFrame) -> Tuple[pd.DataFrame, int]:
    """
    Remove rows where ALL values (excluding the 'experiment' label column) are NaN.
    Returns (cleaned_df, n_removed).
    """
    non_label_cols = [c for c in df.columns if c != "experiment"]
    mask = df[non_label_cols].notna().any(axis=1)
    n_removed = int((~mask).sum())
    return df[mask].reset_index(drop=True), n_removed


def try_convert_dates(df: pd.DataFrame, date_cols: Optional[List[str]] = None) -> pd.DataFrame:
    """
    Attempt to convert date columns to datetime.
    If date_cols is None, auto-detects columns with 'date' in the name.
    """
    df = df.copy()
    if date_cols is None:
        date_cols = [c for c in df.columns if "date" in c.lower()]

    for col in date_cols:
        if col not in df.columns:
            continue
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            continue
        try:
            df[col] = pd.to_datetime(df[col], errors="coerce", dayfirst=True)
            logger.info(f"  Converted '{col}' to datetime.")
        except Exception as e:
            logger.warning(f"  Could not convert '{col}' to datetime: {e}")
    return df


def try_convert_numeric(df: pd.DataFrame, exclude_cols: Optional[List[str]] = None) -> pd.DataFrame:
    """
    Attempt to convert object columns to numeric where possible.
    Columns where conversion fails for >50% of non-null values are left as-is.
    """
    df = df.copy()
    exclude = set(exclude_cols or [])
    exclude.update({"experiment", "replicate", "system", "day"})

    for col in df.select_dtypes(include=["object"]).columns:
        if col in exclude:
            continue
        non_null = df[col].dropna()
        if non_null.empty:
            continue
        converted = pd.to_numeric(non_null, errors="coerce")
        success_rate = converted.notna().sum() / len(non_null)
        if success_rate > 0.5:
            df[col] = pd.to_numeric(df[col], errors="coerce")
            logger.info(
                f"  Converted '{col}' to numeric "
                f"({success_rate:.0%} success, {(1-success_rate):.0%} coerced to NaN)."
            )
    return df


logger.info("Cleaning utility functions defined.")

2026-07-15 19:50:02,469 | INFO | Cleaning utility functions defined.

In [21]:
def clean_dataframe(
    df: pd.DataFrame, table_name: str, exp_label: str
) -> pd.DataFrame:
    """
    Apply the full cleaning pipeline to a single DataFrame.
    Documents every step with before/after comparisons.
    """
    display(Markdown(f"### 🧹 Cleaning: {exp_label} — {table_name}"))

    original_shape = df.shape
    df_clean = df.copy()

    # ── Step 1: Standardize column names ──
    display(Markdown("**Step 1: Standardize column names to snake_case**"))
    display(Markdown("*Reason:* Consistent naming convention for downstream processing."))
    cols_before = list(df_clean.columns)
    df_clean = standardize_column_names(df_clean)
    cols_after = list(df_clean.columns)

    changed = [(b, a) for b, a in zip(cols_before, cols_after) if b != a]
    if changed:
        rename_df = pd.DataFrame(changed, columns=["Before (Raw)", "After (Snake Case)"])
        display(rename_df.head(15))
        if len(changed) > 15:
            print(f"  ... and {len(changed) - 15} more.")
    else:
        display(Markdown("*Before:* " + ", ".join([f"`{c}`" for c in cols_before[:5]]) + ("..." if len(cols_before) > 5 else "")))
        display(Markdown("*After:* " + ", ".join([f"`{c}`" for c in cols_after[:5]]) + ("..." if len(cols_after) > 5 else "")))
        print("  No changes needed.")

    # ── Step 2: Trim whitespace ──
    display(Markdown("**Step 2: Trim string whitespace**"))
    display(Markdown("*Reason:* Remove invisible whitespace that causes false mismatches."))
    
    str_cols = df_clean.select_dtypes(include=["object", "string"]).columns
    trimmed_examples = []
    for col in str_cols:
        non_null_mask = df_clean[col].notna()
        if not non_null_mask.any():
            continue
        vals_before = df_clean.loc[non_null_mask, col].astype(str)
        vals_after = vals_before.str.strip()
        diff_mask = vals_before != vals_after
        if diff_mask.any():
            for val_b, val_a in zip(vals_before[diff_mask].unique(), vals_after[diff_mask].unique()):
                trimmed_examples.append((col, repr(val_b), repr(val_a)))
                
    df_clean = trim_string_whitespace(df_clean)
    
    if trimmed_examples:
        trim_df = pd.DataFrame(trimmed_examples[:15], columns=["Column", "Before (Untrimmed)", "After (Trimmed)"])
        display(trim_df)
        if len(trimmed_examples) > 15:
            print(f"  ... and {len(trimmed_examples) - 15} more whitespace modifications.")
    else:
        if len(str_cols) > 0:
            sample_col = str_cols[0]
            sample_val = df_clean[sample_col].dropna().iloc[0] if df_clean[sample_col].dropna().shape[0] > 0 else "N/A"
            display(Markdown(f"*Before:* `{repr(sample_val)}` (in `{sample_col}`)"))
            display(Markdown(f"*After:* `{repr(sample_val)}` (in `{sample_col}`)"))
        print("  No leading/trailing whitespace detected.")

    # ── Step 3: Replace dash placeholders ──
    display(Markdown("**Step 3: Replace dash/placeholder values with NaN**"))
    display(Markdown("*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements."))
    
    dash_patterns = ["-", "--", "- ", " -", "N/A", "n/a", "NA", "na"]
    placeholder_changes = []
    for col in df_clean.columns:
        mask = df_clean[col].isin(dash_patterns)
        if mask.any():
            found_vals = df_clean.loc[mask, col].unique()
            count = mask.sum()
            for val in found_vals:
                placeholder_changes.append((col, f"'{val}' (count: {count})", "NaN"))
                
    null_before = int(df_clean.isnull().sum().sum())
    df_clean = replace_dash_placeholders(df_clean)
    null_after = int(df_clean.isnull().sum().sum())
    new_nulls = null_after - null_before
    
    if placeholder_changes:
        placeholder_df = pd.DataFrame(placeholder_changes, columns=["Column", "Before (Placeholder)", "After (Converted)"])
        display(placeholder_df)
    else:
        display(Markdown(f"*Before:* {null_before:,} NaN values"))
        display(Markdown(f"*After:* {null_after:,} NaN values"))
        print("  No dash/placeholder values detected.")

    # ── Step 4: Remove fully empty rows ──
    display(Markdown("**Step 4: Remove fully empty rows**"))
    display(Markdown("*Reason:* Rows with no data (all NaN) are structural artifacts from Excel."))
    rows_before = len(df_clean)
    df_clean, n_empty = remove_fully_empty_rows(df_clean)
    
    display(Markdown(f"| Metric | Before | After | Removed |"))
    display(Markdown(f"|---|---|---|---|"))
    display(Markdown(f"| Row Count | {rows_before:,} | {len(df_clean):,} | {n_empty:,} |"))

    # ── Step 5: Remove exact duplicates ──
    display(Markdown("**Step 5: Remove exact duplicate rows**"))
    display(Markdown("*Reason:* Exact duplicates are data entry artifacts, not real observations."))
    rows_before = len(df_clean)
    df_clean, n_dups = remove_exact_duplicates(df_clean)
    
    display(Markdown(f"| Metric | Before | After | Removed |"))
    display(Markdown(f"|---|---|---|---|"))
    display(Markdown(f"| Row Count | {rows_before:,} | {len(df_clean):,} | {n_dups:,} |"))

    # ── Step 6: Convert dates ──
    display(Markdown("**Step 6: Convert date columns to datetime**"))
    display(Markdown("*Reason:* Enable time-series analysis and proper sorting."))
    
    date_cols = [c for c in df_clean.columns if "date" in c.lower()]
    dtypes_before = {col: str(df_clean[col].dtype) for col in date_cols if col in df_clean.columns}
    
    df_clean = try_convert_dates(df_clean)
    
    if date_cols:
        date_changes = []
        for col in date_cols:
            if col in df_clean.columns:
                date_changes.append((col, dtypes_before.get(col, "unknown"), str(df_clean[col].dtype)))
        
        date_df = pd.DataFrame(date_changes, columns=["Column", "Before (Dtype)", "After (Dtype)"])
        display(date_df)
    else:
        display(Markdown("*Before:* No date columns"))
        display(Markdown("*After:* No date columns"))
        print("  No date columns detected.")

    # ── Step 7: Convert numeric columns ──
    display(Markdown("**Step 7: Convert object columns to numeric where appropriate**"))
    display(Markdown(
        "*Reason:* Some numeric measurements are stored as strings due to Excel parsing. "
        "Columns with >50% numeric success rate are converted; non-convertible values become NaN."
    ))
    text_keep = [c for c in df_clean.columns if "diameter" in c.lower() and "head" in c.lower()]
    
    obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
    dtypes_before = {col: str(df_clean[col].dtype) for col in obj_cols}
    
    df_clean = try_convert_numeric(df_clean, exclude_cols=text_keep)
    
    numeric_changes = []
    for col in obj_cols:
        if col in df_clean.columns:
            dtype_after = str(df_clean[col].dtype)
            numeric_changes.append((col, dtypes_before[col], dtype_after))
                
    if numeric_changes:
        num_df = pd.DataFrame(numeric_changes, columns=["Column", "Before (Dtype)", "After (Dtype)"])
        display(num_df)
    else:
        display(Markdown("*Before:* No object columns to convert"))
        display(Markdown("*After:* No object columns to convert"))
        print("  No object columns converted to numeric.")

    # ── Summary ──
    display(Markdown(f"**Cleaning Summary for {table_name}:**"))
    print(f"  Original shape: {original_shape}")
    print(f"  Cleaned shape:  {df_clean.shape}")
    print(f"  Rows removed:   {original_shape[0] - df_clean.shape[0]}")
    print("\n" + "─" * 70 + "\n")

    return df_clean

In [22]:
# ==========================================================================
# Apply cleaning to ALL parsed tables
# ==========================================================================
cleaned_data: Dict[str, Dict[str, pd.DataFrame]] = {}

for exp_label, tables in parsed_data.items():
    display(Markdown(f"## 📂 {exp_label} — Cleaning"))
    display(Markdown("---"))
    cleaned_data[exp_label] = {}

    for tname, tdata in tables.items():
        if isinstance(tdata, pd.DataFrame) and not tdata.empty:
            cleaned_data[exp_label][tname] = clean_dataframe(
                tdata, tname, exp_label
            )

logger.info("Cleaning complete for all datasets.")
print("\n✅ All datasets cleaned.")

## 📂 Experiment 1 — Cleaning

---

### 🧹 Cleaning: Experiment 1 — seedlings

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

           Before (Raw) After (Snake Case)
0                  Date               date
1             plant NO.           plant_no
2    plant height  (cm)    plant_height_cm
3     shoot length (cm)    shoot_length_cm
4      root length (cm)     root_length_cm
5    head diameter (cm)   head_diameter_cm
6   stem diameter  (cm)   stem_diameter_cm
7      total weight (g)     total_weight_g
8      shoot weight (g)     shoot_weight_g
9       root weight (g)      root_weight_g
10        no. of leaves       no_of_leaves

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 1'` (in `experiment`)

*After:* `'Experiment 1'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 9 NaN values

*After:* 9 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 10 | 10 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 10 | 10 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

2026-07-15 19:50:13,930 | INFO |   Converted 'date' to datetime.

  Column Before (Dtype)   After (Dtype)
0   date            str  datetime64[us]

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:13,942 | INFO |   Converted 'plant_no' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:13,944 | INFO |   Converted 'plant_height_cm' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:13,945 | INFO |   Converted 'shoot_length_cm' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:13,947 | INFO |   Converted 'root_length_cm' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:13,948 | INFO |   Converted 'stem_diameter_cm' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:13,950 | INFO |   Converted 'total_weight_g' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:13,952 | INFO |   Converted 'shoot_weight_g' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:13,954 | INFO |   Converted 'root_weight_g' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:13,956 | INFO |   Converted 'no_of_leaves' to numeric (100% success, 0% coerced to NaN).

             Column Before (Dtype) After (Dtype)
0          plant_no            str         int64
1   plant_height_cm            str       float64
2   shoot_length_cm            str       float64
3    root_length_cm            str       float64
4  stem_diameter_cm            str       float64
5    total_weight_g            str       float64
6    shoot_weight_g            str       float64
7     root_weight_g            str       float64
8      no_of_leaves            str         int64

**Cleaning Summary for seedlings:**

  Original shape: (10, 12)
  Cleaned shape:  (10, 12)
  Rows removed:   0

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 1 — sensor_water_quality

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

   Before (Raw) After (Snake Case)
0          Date               date
1           Tme                tme
2            pH                 ph
3            EC                 ec
4           TDS                tds
5   Water temp.         water_temp
6        Date_1             date_1
7         Tme_1              tme_1
8          RH %               rh_%
9   Air temp. C         air_temp_c
10      CO2 PPM            co2_ppm

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

  Column Before (Untrimmed) After (Trimmed)
0   date                ' '              ''

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 3,851 NaN values

*After:* 3,851 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 641 | 641 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 641 | 641 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

2026-07-15 19:50:14,059 | INFO |   Converted 'date' to datetime.
2026-07-15 19:50:14,061 | INFO |   Converted 'date_1' to datetime.

   Column Before (Dtype)   After (Dtype)
0    date            str   datetime64[s]
1  date_1            str  datetime64[us]

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:14,077 | INFO |   Converted 'rh_%' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,080 | INFO |   Converted 'air_temp_c' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,083 | INFO |   Converted 'co2_ppm' to numeric (100% success, 0% coerced to NaN).

       Column Before (Dtype) After (Dtype)
0         tme            str           str
1          ph            str           str
2          ec            str           str
3         tds            str           str
4  water_temp            str           str
5       tme_1            str           str
6        rh_%            str       float64
7  air_temp_c            str       float64
8     co2_ppm            str       float64

**Cleaning Summary for sensor_water_quality:**

  Original shape: (641, 13)
  Cleaned shape:  (641, 13)
  Rows removed:   0

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 1 — portable_water_quality

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

*Before:* `experiment`, `date`, `100000_replicate_1_t1_ph`, `100000_replicate_1_t1_ec`, `100000_replicate_1_t1_tds`...

*After:* `experiment`, `date`, `100000_replicate_1_t1_ph`, `100000_replicate_1_t1_ec`, `100000_replicate_1_t1_tds`...

  No changes needed.

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

                     Column Before (Untrimmed) After (Trimmed)
0  100000_replicate_1_t1_ph               ' -'             '-'

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

                              Column Before (Placeholder) After (Converted)
0           100000_replicate_1_t1_ph       '-' (count: 5)               NaN
1           100000_replicate_1_t1_ec       '-' (count: 5)               NaN
2          100000_replicate_1_t1_tds       '-' (count: 5)               NaN
3   100000_replicate_1_t1_water_temp       '-' (count: 5)               NaN
4           100000_replicate_2_t1_ph       '-' (count: 5)               NaN
5           100000_replicate_2_t1_ec       '-' (count: 5)               NaN
6          100000_replicate_2_t1_tds       '-' (count: 5)               NaN
7   100000_replicate_2_t1_water_temp       '-' (count: 5)               NaN
8           100000_replicate_3_t1_ph       '-' (count: 5)               NaN
9           100000_replicate_3_t1_ec       '-' (count: 5)               NaN
10         100000_replicate_3_t1_tds       '-' (count: 5)               NaN
11  100000_replicate_3_t1_water_temp       '-' (count: 5)               NaN
12          100000_replicate_1_t2_ph       '-' (count: 5)               NaN
13          100000_replicate_1_t2_ec       '-' (count: 5)               NaN
14         100000_replicate_1_t2_tds       '-' (count: 5)               NaN
15  100000_replicate_1_t2_water_temp       '-' (count: 5)               NaN
16          100000_replicate_2_t2_ph       '-' (count: 5)               NaN
17          100000_replicate_2_t2_ec       '-' (count: 5)               NaN
18         100000_replicate_2_t2_tds       '-' (count: 4)               NaN
19  100000_replicate_2_t2_water_temp       '-' (count: 5)               NaN
20          100000_replicate_3_t2_ph       '-' (count: 5)               NaN
21          100000_replicate_3_t2_ec       '-' (count: 5)               NaN
22         100000_replicate_3_t2_tds       '-' (count: 5)               NaN
23  100000_replicate_3_t2_water_temp       '-' (count: 5)               NaN
24         100000_air_air_parameters       '-' (count: 1)               NaN
25                 100000_rh%_col_26       '-' (count: 1)               NaN
26            100000_air_temp_col_27       '-' (count: 1)               NaN
27          140000_replicate_1_t1_ph       '-' (count: 4)               NaN
28          140000_replicate_1_t1_ec       '-' (count: 4)               NaN
29         140000_replicate_1_t1_tds       '-' (count: 4)               NaN
30  140000_replicate_1_t1_water_temp       '-' (count: 4)               NaN
31          140000_replicate_2_t1_ph       '-' (count: 4)               NaN
32          140000_replicate_2_t1_ec       '-' (count: 4)               NaN
33         140000_replicate_2_t1_tds       '-' (count: 4)               NaN
34  140000_replicate_2_t1_water_temp       '-' (count: 4)               NaN
35          140000_replicate_3_t1_ph       '-' (count: 4)               NaN
36          140000_replicate_3_t1_ec       '-' (count: 4)               NaN
37         140000_replicate_3_t1_tds       '-' (count: 4)               NaN
38  140000_replicate_3_t1_water_temp       '-' (count: 4)               NaN
39          140000_replicate_1_t2_ph       '-' (count: 4)               NaN
40          140000_replicate_1_t2_ec       '-' (count: 4)               NaN
41         140000_replicate_1_t2_tds       '-' (count: 4)               NaN
42  140000_replicate_1_t2_water_temp       '-' (count: 4)               NaN
43          140000_replicate_2_t2_ph       '-' (count: 4)               NaN
44          140000_replicate_2_t2_ec       '-' (count: 4)               NaN
45         140000_replicate_2_t2_tds       '-' (count: 4)               NaN
46  140000_replicate_2_t2_water_temp       '-' (count: 4)               NaN
47          140000_replicate_3_t2_ph       '-' (count: 4)               NaN
48          140000_replicate_3_t2_ec       '-' (count: 4)               NaN
49         140000_replicate_3_t2_tds       '-' (count: 4)               NaN
50  140000_replicate_3_t2_water_temp       '-' (count: 4)               NaN

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 33 | 32 | 1 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 32 | 32 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

2026-07-15 19:50:14,283 | INFO |   Converted 'date' to datetime.

  Column Before (Dtype)   After (Dtype)
0   date            str  datetime64[us]

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:14,297 | INFO |   Converted '100000_replicate_1_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,299 | INFO |   Converted '100000_replicate_1_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,301 | INFO |   Converted '100000_replicate_1_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,304 | INFO |   Converted '100000_replicate_1_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,305 | INFO |   Converted '100000_replicate_2_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,306 | INFO |   Converted '100000_replicate_2_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,307 | INFO |   Converted '100000_replicate_2_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,309 | INFO |   Converted '100000_replicate_2_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,311 | INFO |   Converted '100000_replicate_3_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,312 | INFO |   Converted '100000_replicate_3_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,314 | INFO |   Converted '100000_replicate_3_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,316 | INFO |   Converted '100000_replicate_3_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,318 | INFO |   Converted '100000_replicate_1_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,321 | INFO |   Converted '100000_replicate_1_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,323 | INFO |   Converted '100000_replicate_1_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,324 | INFO |   Converted '100000_replicate_1_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,326 | INFO |   Converted '100000_replicate_2_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,327 | INFO |   Converted '100000_replicate_2_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,329 | INFO |   Converted '100000_replicate_2_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,330 | INFO |   Converted '100000_replicate_2_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,332 | INFO |   Converted '100000_replicate_3_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,333 | INFO |   Converted '100000_replicate_3_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,334 | INFO |   Converted '100000_replicate_3_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,336 | INFO |   Converted '100000_replicate_3_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,338 | INFO |   Converted '100000_air_air_parameters' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,340 | INFO |   Converted '100000_rh%_col_26' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,342 | INFO |   Converted '100000_air_temp_col_27' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,344 | INFO |   Converted '140000_replicate_1_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,346 | INFO |   Converted '140000_replicate_1_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,348 | INFO |   Converted '140000_replicate_1_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,350 | INFO |   Converted '140000_replicate_1_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,352 | INFO |   Converted '140000_replicate_2_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,355 | INFO |   Converted '140000_replicate_2_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,356 | INFO |   Converted '140000_replicate_2_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,358 | INFO |   Converted '140000_replicate_2_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,359 | INFO |   Converted '140000_replicate_3_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,361 | INFO |   Converted '140000_replicate_3_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,363 | INFO |   Converted '140000_replicate_3_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,365 | INFO |   Converted '140000_replicate_3_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,368 | INFO |   Converted '140000_replicate_1_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,370 | INFO |   Converted '140000_replicate_1_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,372 | INFO |   Converted '140000_replicate_1_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,374 | INFO |   Converted '140000_replicate_1_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,376 | INFO |   Converted '140000_replicate_2_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,378 | INFO |   Converted '140000_replicate_2_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,379 | INFO |   Converted '140000_replicate_2_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,381 | INFO |   Converted '140000_replicate_2_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,383 | INFO |   Converted '140000_replicate_3_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,385 | INFO |   Converted '140000_replicate_3_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,387 | INFO |   Converted '140000_replicate_3_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,390 | INFO |   Converted '140000_replicate_3_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,392 | INFO |   Converted '140000_air_air_parameters' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,393 | INFO |   Converted '140000_rh%_col_54' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,395 | INFO |   Converted '140000_air_temp_col_55' to numeric (100% success, 0% coerced to NaN).

                              Column Before (Dtype) After (Dtype)
0           100000_replicate_1_t1_ph            str       float64
1           100000_replicate_1_t1_ec            str       float64
2          100000_replicate_1_t1_tds            str       float64
3   100000_replicate_1_t1_water_temp            str       float64
4           100000_replicate_2_t1_ph            str       float64
5           100000_replicate_2_t1_ec            str       float64
6          100000_replicate_2_t1_tds            str       float64
7   100000_replicate_2_t1_water_temp            str       float64
8           100000_replicate_3_t1_ph            str       float64
9           100000_replicate_3_t1_ec            str       float64
10         100000_replicate_3_t1_tds            str       float64
11  100000_replicate_3_t1_water_temp            str       float64
12          100000_replicate_1_t2_ph            str       float64
13          100000_replicate_1_t2_ec            str       float64
14         100000_replicate_1_t2_tds            str       float64
15  100000_replicate_1_t2_water_temp            str       float64
16          100000_replicate_2_t2_ph            str       float64
17          100000_replicate_2_t2_ec            str       float64
18         100000_replicate_2_t2_tds            str       float64
19  100000_replicate_2_t2_water_temp            str       float64
20          100000_replicate_3_t2_ph            str       float64
21          100000_replicate_3_t2_ec            str       float64
22         100000_replicate_3_t2_tds            str       float64
23  100000_replicate_3_t2_water_temp            str       float64
24         100000_air_air_parameters            str       float64
25                 100000_rh%_col_26            str       float64
26            100000_air_temp_col_27            str       float64
27          140000_replicate_1_t1_ph            str       float64
28          140000_replicate_1_t1_ec            str       float64
29         140000_replicate_1_t1_tds            str       float64
30  140000_replicate_1_t1_water_temp            str       float64
31          140000_replicate_2_t1_ph            str       float64
32          140000_replicate_2_t1_ec            str       float64
33         140000_replicate_2_t1_tds            str       float64
34  140000_replicate_2_t1_water_temp            str       float64
35          140000_replicate_3_t1_ph            str       float64
36          140000_replicate_3_t1_ec            str       float64
37         140000_replicate_3_t1_tds            str       float64
38  140000_replicate_3_t1_water_temp            str       float64
39          140000_replicate_1_t2_ph            str       float64
40          140000_replicate_1_t2_ec            str       float64
41         140000_replicate_1_t2_tds            str       float64
42  140000_replicate_1_t2_water_temp            str       float64
43          140000_replicate_2_t2_ph            str       float64
44          140000_replicate_2_t2_ec            str       float64
45         140000_replicate_2_t2_tds            str       float64
46  140000_replicate_2_t2_water_temp            str       float64
47          140000_replicate_3_t2_ph            str       float64
48          140000_replicate_3_t2_ec            str       float64
49         140000_replicate_3_t2_tds            str       float64
50  140000_replicate_3_t2_water_temp            str       float64
51         140000_air_air_parameters            str       float64
52                 140000_rh%_col_54            str       float64
53            140000_air_temp_col_55            str       float64

**Cleaning Summary for portable_water_quality:**

  Original shape: (33, 57)
  Cleaned shape:  (32, 57)
  Rows removed:   1

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 1 — nutrients_date

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

*Before:* `experiment`, `date`

*After:* `experiment`, `date`

  No changes needed.

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

  Column Before (Untrimmed) After (Trimmed)
0   date           'Total '         'Total'

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 19 NaN values

*After:* 19 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 24 | 5 | 19 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 5 | 5 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

2026-07-15 19:50:14,512 | INFO |   Converted 'date' to datetime.

  Column Before (Dtype)   After (Dtype)
0   date            str  datetime64[us]

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:

*Before:* No object columns to convert

*After:* No object columns to convert

  No object columns converted to numeric.

**Cleaning Summary for nutrients_date:**

  Original shape: (24, 2)
  Cleaned shape:  (5, 2)
  Rows removed:   19

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 1 — nutrients_nutrient_solution_addition_(a+b)_ml

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

     Before (Raw) After (Snake Case)
0  Replicate_1_T1     replicate_1_t1
1  Replicate_2_T1     replicate_2_t1
2  Replicate_3_T1     replicate_3_t1
3  Replicate_1_T2     replicate_1_t2
4  Replicate_2_T2     replicate_2_t2
5  Replicate_3_T2     replicate_3_t2

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 1'` (in `experiment`)

*After:* `'Experiment 1'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 114 NaN values

*After:* 114 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 24 | 5 | 19 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 5 | 5 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:14,665 | INFO |   Converted 'replicate_1_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,669 | INFO |   Converted 'replicate_2_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,673 | INFO |   Converted 'replicate_3_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,676 | INFO |   Converted 'replicate_1_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,679 | INFO |   Converted 'replicate_2_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,682 | INFO |   Converted 'replicate_3_t2' to numeric (100% success, 0% coerced to NaN).

           Column Before (Dtype) After (Dtype)
0  replicate_1_t1            str         int64
1  replicate_2_t1            str         int64
2  replicate_3_t1            str         int64
3  replicate_1_t2            str         int64
4  replicate_2_t2            str         int64
5  replicate_3_t2            str         int64

**Cleaning Summary for nutrients_nutrient_solution_addition_(a+b)_ml:**

  Original shape: (24, 7)
  Cleaned shape:  (5, 7)
  Rows removed:   19

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 1 — nutrients_acid_consumption_(ml)

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

     Before (Raw) After (Snake Case)
0  Replicate_1_T1     replicate_1_t1
1  Replicate_2_T1     replicate_2_t1
2  Replicate_3_T1     replicate_3_t1
3  Replicate_1_T2     replicate_1_t2
4  Replicate_2_T2     replicate_2_t2
5  Replicate_3_T2     replicate_3_t2

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 1'` (in `experiment`)

*After:* `'Experiment 1'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 120 NaN values

*After:* 120 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 24 | 4 | 20 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 4 | 4 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:14,853 | INFO |   Converted 'replicate_1_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,857 | INFO |   Converted 'replicate_2_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,861 | INFO |   Converted 'replicate_3_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,864 | INFO |   Converted 'replicate_1_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,867 | INFO |   Converted 'replicate_2_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:14,871 | INFO |   Converted 'replicate_3_t2' to numeric (100% success, 0% coerced to NaN).

           Column Before (Dtype) After (Dtype)
0  replicate_1_t1            str         int64
1  replicate_2_t1            str         int64
2  replicate_3_t1            str         int64
3  replicate_1_t2            str         int64
4  replicate_2_t2            str         int64
5  replicate_3_t2            str         int64

**Cleaning Summary for nutrients_acid_consumption_(ml):**

  Original shape: (24, 7)
  Cleaned shape:  (4, 7)
  Rows removed:   20

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 1 — nutrients_water_consumption_l

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

     Before (Raw) After (Snake Case)
0  Replicate_1_T1     replicate_1_t1
1  Replicate_2_T1     replicate_2_t1
2  Replicate_3_T1     replicate_3_t1
3  Replicate_1_T2     replicate_1_t2
4  Replicate_2_T2     replicate_2_t2
5  Replicate_3_T2     replicate_3_t2

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 1'` (in `experiment`)

*After:* `'Experiment 1'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 114 NaN values

*After:* 114 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 24 | 5 | 19 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 5 | 5 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:15,042 | INFO |   Converted 'replicate_1_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,049 | INFO |   Converted 'replicate_2_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,053 | INFO |   Converted 'replicate_3_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,056 | INFO |   Converted 'replicate_1_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,059 | INFO |   Converted 'replicate_2_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,064 | INFO |   Converted 'replicate_3_t2' to numeric (100% success, 0% coerced to NaN).

           Column Before (Dtype) After (Dtype)
0  replicate_1_t1            str         int64
1  replicate_2_t1            str         int64
2  replicate_3_t1            str         int64
3  replicate_1_t2            str         int64
4  replicate_2_t2            str         int64
5  replicate_3_t2            str         int64

**Cleaning Summary for nutrients_water_consumption_l:**

  Original shape: (24, 7)
  Cleaned shape:  (5, 7)
  Rows removed:   19

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 1 — head_diameter

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

*Before:* `experiment`, `replicate`, `day`, `plant_no`, `head_diameter`

*After:* `experiment`, `replicate`, `day`, `plant_no`, `head_diameter`

  No changes needed.

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 1'` (in `experiment`)

*After:* `'Experiment 1'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 240 NaN values

*After:* 240 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 300 | 300 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 300 | 204 | 96 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:

*Before:* No object columns to convert

*After:* No object columns to convert

  No object columns converted to numeric.

**Cleaning Summary for head_diameter:**

  Original shape: (300, 5)
  Cleaned shape:  (204, 5)
  Rows removed:   96

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 1 — harvest

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

,Before (Raw),After (Snake Case)
0,Plant No.,plant_no
1,Total weight (g),total_weight_g
2,Plant height (cm),plant_height_cm
3,Shoot length (cm),shoot_length_cm
4,Root length (cm),root_length_cm
5,Head diameter (cm),head_diameter_cm
6,Stem diameter (cm),stem_diameter_cm
7,Shoot weight before removing wilted ...,shoot_weight_before_removing_wilted_...
8,shoot weight after removing wilted l...,shoot_weight_after_removing_wilted_l...
9,Root weight (g),root_weight_g
10,No. of leaves,no_of_leaves

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 1'` (in `experiment`)

*After:* `'Experiment 1'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 10 NaN values

*After:* 10 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 73 | 73 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 73 | 73 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:

*Before:* No object columns to convert

*After:* No object columns to convert

  No object columns converted to numeric.

**Cleaning Summary for harvest:**

  Original shape: (73, 13)
  Cleaned shape:  (73, 13)
  Rows removed:   0

──────────────────────────────────────────────────────────────────────

## 📂 Experiment 2 — Cleaning

---

### 🧹 Cleaning: Experiment 2 — seedlings

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

           Before (Raw) After (Snake Case)
0                  Date               date
1             plant NO.           plant_no
2    plant height  (cm)    plant_height_cm
3     shoot length (cm)    shoot_length_cm
4      root length (cm)     root_length_cm
5    head diameter (cm)   head_diameter_cm
6   stem diameter  (cm)   stem_diameter_cm
7      total weight (g)     total_weight_g
8      shoot weight (g)     shoot_weight_g
9       root weight (g)      root_weight_g
10        no. of leaves       no_of_leaves

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 2'` (in `experiment`)

*After:* `'Experiment 2'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 12 NaN values

*After:* 12 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 12 | 12 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 12 | 12 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

2026-07-15 19:50:15,521 | INFO |   Converted 'date' to datetime.

  Column Before (Dtype)  After (Dtype)
0   date            str  datetime64[s]

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:15,542 | INFO |   Converted 'plant_no' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,545 | INFO |   Converted 'plant_height_cm' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,548 | INFO |   Converted 'shoot_length_cm' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,551 | INFO |   Converted 'root_length_cm' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,555 | INFO |   Converted 'stem_diameter_cm' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,558 | INFO |   Converted 'total_weight_g' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,561 | INFO |   Converted 'shoot_weight_g' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,564 | INFO |   Converted 'root_weight_g' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,567 | INFO |   Converted 'no_of_leaves' to numeric (100% success, 0% coerced to NaN).

             Column Before (Dtype) After (Dtype)
0          plant_no            str         int64
1   plant_height_cm            str       float64
2   shoot_length_cm            str         int64
3    root_length_cm            str       float64
4  stem_diameter_cm            str       float64
5    total_weight_g            str       float64
6    shoot_weight_g            str       float64
7     root_weight_g            str       float64
8      no_of_leaves            str         int64

**Cleaning Summary for seedlings:**

  Original shape: (12, 12)
  Cleaned shape:  (12, 12)
  Rows removed:   0

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 2 — sensor_water_quality

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

   Before (Raw) After (Snake Case)
0          Date               date
1           Tme                tme
2           pH.                 ph
3           EC.                 ec
4          TDS.                tds
5   Water temp.         water_temp
6        Date_1             date_1
7         Tme_1              tme_1
8           RH%                rh%
9     Air temp.           air_temp
10          CO2                co2

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

  Column Before (Untrimmed) After (Trimmed)
0   date                ' '              ''

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 4,308 NaN values

*After:* 4,308 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 718 | 718 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 718 | 718 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

2026-07-15 19:50:15,806 | INFO |   Converted 'date' to datetime.
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:83: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce", dayfirst=True)
2026-07-15 19:50:15,813 | INFO |   Converted 'date_1' to datetime.

   Column Before (Dtype)   After (Dtype)
0    date            str   datetime64[s]
1  date_1            str  datetime64[us]

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:15,845 | INFO |   Converted 'rh%' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,849 | INFO |   Converted 'air_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:15,855 | INFO |   Converted 'co2' to numeric (100% success, 0% coerced to NaN).

       Column Before (Dtype) After (Dtype)
0         tme            str           str
1          ph            str           str
2          ec            str           str
3         tds            str           str
4  water_temp            str           str
5       tme_1            str           str
6         rh%            str       float64
7    air_temp            str       float64
8         co2            str       float64

**Cleaning Summary for sensor_water_quality:**

  Original shape: (718, 13)
  Cleaned shape:  (718, 13)
  Rows removed:   0

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 2 — portable_water_quality

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

*Before:* `experiment`, `date`, `100000_replicate_1_t1_ph`, `100000_replicate_1_t1_ec`, `100000_replicate_1_t1_tds`...

*After:* `experiment`, `date`, `100000_replicate_1_t1_ph`, `100000_replicate_1_t1_ec`, `100000_replicate_1_t1_tds`...

  No changes needed.

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 2'` (in `experiment`)

*After:* `'Experiment 2'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

                              Column Before (Placeholder) After (Converted)
0          100000_air_air_parameters       '-' (count: 5)               NaN
1             100000_air_temp_col_26       '-' (count: 5)               NaN
2                 100000_rh_%_col_27       '-' (count: 5)               NaN
3           140000_replicate_1_t1_ph       '-' (count: 4)               NaN
4           140000_replicate_1_t1_ec       '-' (count: 4)               NaN
5          140000_replicate_1_t1_tds       '-' (count: 4)               NaN
6   140000_replicate_1_t1_water_temp       '-' (count: 4)               NaN
7           140000_replicate_2_t1_ph       '-' (count: 4)               NaN
8           140000_replicate_2_t1_ec       '-' (count: 4)               NaN
9          140000_replicate_2_t1_tds       '-' (count: 4)               NaN
10  140000_replicate_2_t1_water_temp       '-' (count: 4)               NaN
11          140000_replicate_3_t1_ph       '-' (count: 5)               NaN
12          140000_replicate_3_t1_ec       '-' (count: 5)               NaN
13         140000_replicate_3_t1_tds       '-' (count: 5)               NaN
14  140000_replicate_3_t1_water_temp       '-' (count: 5)               NaN
15          140000_replicate_1_t2_ph       '-' (count: 4)               NaN
16          140000_replicate_1_t2_ec       '-' (count: 4)               NaN
17         140000_replicate_1_t2_tds       '-' (count: 4)               NaN
18  140000_replicate_1_t2_water_temp       '-' (count: 4)               NaN
19          140000_replicate_2_t2_ph       '-' (count: 4)               NaN
20          140000_replicate_2_t2_ec       '-' (count: 4)               NaN
21         140000_replicate_2_t2_tds       '-' (count: 4)               NaN
22  140000_replicate_2_t2_water_temp       '-' (count: 4)               NaN
23          140000_replicate_3_t2_ph       '-' (count: 4)               NaN
24          140000_replicate_3_t2_ec       '-' (count: 4)               NaN
25         140000_replicate_3_t2_tds       '-' (count: 4)               NaN
26  140000_replicate_3_t2_water_temp       '-' (count: 4)               NaN
27         140000_air_air_parameters       '-' (count: 7)               NaN
28                 140000_rh%_col_54       '-' (count: 7)               NaN
29            140000_air_temp_col_55       '-' (count: 7)               NaN

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 29 | 29 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 29 | 29 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

2026-07-15 19:50:16,225 | INFO |   Converted 'date' to datetime.

  Column Before (Dtype)   After (Dtype)
0   date            str  datetime64[us]

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:16,252 | INFO |   Converted '100000_replicate_1_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,256 | INFO |   Converted '100000_replicate_1_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,260 | INFO |   Converted '100000_replicate_1_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,263 | INFO |   Converted '100000_replicate_1_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,266 | INFO |   Converted '100000_replicate_2_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,269 | INFO |   Converted '100000_replicate_2_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,272 | INFO |   Converted '100000_replicate_2_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,276 | INFO |   Converted '100000_replicate_2_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,284 | INFO |   Converted '100000_replicate_3_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,291 | INFO |   Converted '100000_replicate_3_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,298 | INFO |   Converted '100000_replicate_3_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,304 | INFO |   Converted '100000_replicate_3_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,307 | INFO |   Converted '100000_replicate_1_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,310 | INFO |   Converted '100000_replicate_1_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,314 | INFO |   Converted '100000_replicate_1_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,318 | INFO |   Converted '100000_replicate_1_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,322 | INFO |   Converted '100000_replicate_2_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,325 | INFO |   Converted '100000_replicate_2_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,329 | INFO |   Converted '100000_replicate_2_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,333 | INFO |   Converted '100000_replicate_2_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,337 | INFO |   Converted '100000_replicate_3_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,340 | INFO |   Converted '100000_replicate_3_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,344 | INFO |   Converted '100000_replicate_3_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,348 | INFO |   Converted '100000_replicate_3_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,353 | INFO |   Converted '100000_air_air_parameters' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,357 | INFO |   Converted '100000_air_temp_col_26' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,360 | INFO |   Converted '100000_rh_%_col_27' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,364 | INFO |   Converted '140000_replicate_1_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,368 | INFO |   Converted '140000_replicate_1_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,373 | INFO |   Converted '140000_replicate_1_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,377 | INFO |   Converted '140000_replicate_1_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,381 | INFO |   Converted '140000_replicate_2_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,387 | INFO |   Converted '140000_replicate_2_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,390 | INFO |   Converted '140000_replicate_2_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,394 | INFO |   Converted '140000_replicate_2_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,398 | INFO |   Converted '140000_replicate_3_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,402 | INFO |   Converted '140000_replicate_3_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,405 | INFO |   Converted '140000_replicate_3_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,408 | INFO |   Converted '140000_replicate_3_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,412 | INFO |   Converted '140000_replicate_1_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,415 | INFO |   Converted '140000_replicate_1_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,420 | INFO |   Converted '140000_replicate_1_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,425 | INFO |   Converted '140000_replicate_1_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,429 | INFO |   Converted '140000_replicate_2_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,432 | INFO |   Converted '140000_replicate_2_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,437 | INFO |   Converted '140000_replicate_2_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,441 | INFO |   Converted '140000_replicate_2_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,444 | INFO |   Converted '140000_replicate_3_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,447 | INFO |   Converted '140000_replicate_3_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,450 | INFO |   Converted '140000_replicate_3_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,453 | INFO |   Converted '140000_replicate_3_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,457 | INFO |   Converted '140000_air_air_parameters' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,461 | INFO |   Converted '140000_rh%_col_54' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,465 | INFO |   Converted '140000_air_temp_col_55' to numeric (100% success, 0% coerced to NaN).

                              Column Before (Dtype) After (Dtype)
0           100000_replicate_1_t1_ph            str       float64
1           100000_replicate_1_t1_ec            str       float64
2          100000_replicate_1_t1_tds            str       float64
3   100000_replicate_1_t1_water_temp            str       float64
4           100000_replicate_2_t1_ph            str       float64
5           100000_replicate_2_t1_ec            str       float64
6          100000_replicate_2_t1_tds            str       float64
7   100000_replicate_2_t1_water_temp            str       float64
8           100000_replicate_3_t1_ph            str       float64
9           100000_replicate_3_t1_ec            str       float64
10         100000_replicate_3_t1_tds            str       float64
11  100000_replicate_3_t1_water_temp            str       float64
12          100000_replicate_1_t2_ph            str       float64
13          100000_replicate_1_t2_ec            str       float64
14         100000_replicate_1_t2_tds            str       float64
15  100000_replicate_1_t2_water_temp            str       float64
16          100000_replicate_2_t2_ph            str       float64
17          100000_replicate_2_t2_ec            str       float64
18         100000_replicate_2_t2_tds            str       float64
19  100000_replicate_2_t2_water_temp            str       float64
20          100000_replicate_3_t2_ph            str       float64
21          100000_replicate_3_t2_ec            str       float64
22         100000_replicate_3_t2_tds            str       float64
23  100000_replicate_3_t2_water_temp            str       float64
24         100000_air_air_parameters            str       float64
25            100000_air_temp_col_26            str       float64
26                100000_rh_%_col_27            str       float64
27          140000_replicate_1_t1_ph            str       float64
28          140000_replicate_1_t1_ec            str       float64
29         140000_replicate_1_t1_tds            str       float64
30  140000_replicate_1_t1_water_temp            str       float64
31          140000_replicate_2_t1_ph            str       float64
32          140000_replicate_2_t1_ec            str       float64
33         140000_replicate_2_t1_tds            str       float64
34  140000_replicate_2_t1_water_temp            str       float64
35          140000_replicate_3_t1_ph            str       float64
36          140000_replicate_3_t1_ec            str       float64
37         140000_replicate_3_t1_tds            str       float64
38  140000_replicate_3_t1_water_temp            str       float64
39          140000_replicate_1_t2_ph            str       float64
40          140000_replicate_1_t2_ec            str       float64
41         140000_replicate_1_t2_tds            str       float64
42  140000_replicate_1_t2_water_temp            str       float64
43          140000_replicate_2_t2_ph            str       float64
44          140000_replicate_2_t2_ec            str       float64
45         140000_replicate_2_t2_tds            str       float64
46  140000_replicate_2_t2_water_temp            str       float64
47          140000_replicate_3_t2_ph            str       float64
48          140000_replicate_3_t2_ec            str       float64
49         140000_replicate_3_t2_tds            str       float64
50  140000_replicate_3_t2_water_temp            str       float64
51         140000_air_air_parameters            str       float64
52                 140000_rh%_col_54            str       float64
53            140000_air_temp_col_55            str       float64

**Cleaning Summary for portable_water_quality:**

  Original shape: (29, 57)
  Cleaned shape:  (29, 57)
  Rows removed:   0

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 2 — nutrients_date

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

*Before:* `experiment`, `date`

*After:* `experiment`, `date`

  No changes needed.

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

  Column Before (Untrimmed) After (Trimmed)
0   date           'Total '         'Total'

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 22 NaN values

*After:* 22 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 24 | 2 | 22 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 2 | 2 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

2026-07-15 19:50:16,614 | INFO |   Converted 'date' to datetime.

  Column Before (Dtype)   After (Dtype)
0   date            str  datetime64[us]

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:

*Before:* No object columns to convert

*After:* No object columns to convert

  No object columns converted to numeric.

**Cleaning Summary for nutrients_date:**

  Original shape: (24, 2)
  Cleaned shape:  (2, 2)
  Rows removed:   22

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 2 — nutrients_nutrient_solution_addition_(a+b)_ml

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

     Before (Raw) After (Snake Case)
0  Replicate_1_T1     replicate_1_t1
1  Replicate_2_T1     replicate_2_t1
2  Replicate_3_T1     replicate_3_t1
3  Replicate_1_T2     replicate_1_t2
4  Replicate_2_T2     replicate_2_t2
5  Replicate_3_T2     replicate_3_t2

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 2'` (in `experiment`)

*After:* `'Experiment 2'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 126 NaN values

*After:* 126 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 24 | 3 | 21 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 3 | 3 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:16,798 | INFO |   Converted 'replicate_1_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,802 | INFO |   Converted 'replicate_2_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,805 | INFO |   Converted 'replicate_3_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,807 | INFO |   Converted 'replicate_1_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,810 | INFO |   Converted 'replicate_2_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,813 | INFO |   Converted 'replicate_3_t2' to numeric (100% success, 0% coerced to NaN).

           Column Before (Dtype) After (Dtype)
0  replicate_1_t1            str         int64
1  replicate_2_t1            str         int64
2  replicate_3_t1            str         int64
3  replicate_1_t2            str         int64
4  replicate_2_t2            str         int64
5  replicate_3_t2            str         int64

**Cleaning Summary for nutrients_nutrient_solution_addition_(a+b)_ml:**

  Original shape: (24, 7)
  Cleaned shape:  (3, 7)
  Rows removed:   21

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 2 — nutrients_water_consumption_l

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

     Before (Raw) After (Snake Case)
0  Replicate_1_T1     replicate_1_t1
1  Replicate_2_T1     replicate_2_t1
2  Replicate_3_T1     replicate_3_t1
3  Replicate_1_T2     replicate_1_t2
4  Replicate_2_T2     replicate_2_t2
5  Replicate_3_T2     replicate_3_t2

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 2'` (in `experiment`)

*After:* `'Experiment 2'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 132 NaN values

*After:* 132 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 24 | 2 | 22 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 2 | 1 | 1 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:16,956 | INFO |   Converted 'replicate_1_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,960 | INFO |   Converted 'replicate_2_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,963 | INFO |   Converted 'replicate_3_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,967 | INFO |   Converted 'replicate_1_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,970 | INFO |   Converted 'replicate_2_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:16,974 | INFO |   Converted 'replicate_3_t2' to numeric (100% success, 0% coerced to NaN).

           Column Before (Dtype) After (Dtype)
0  replicate_1_t1            str         int64
1  replicate_2_t1            str         int64
2  replicate_3_t1            str         int64
3  replicate_1_t2            str         int64
4  replicate_2_t2            str         int64
5  replicate_3_t2            str         int64

**Cleaning Summary for nutrients_water_consumption_l:**

  Original shape: (24, 7)
  Cleaned shape:  (1, 7)
  Rows removed:   23

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 2 — harvest

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

,Before (Raw),After (Snake Case)
0,Plant No.,plant_no
1,Total weight (g),total_weight_g
2,Plant height (cm),plant_height_cm
3,Shoot length (cm),shoot_length_cm
4,Root length (cm),root_length_cm
5,Head diameter (cm),head_diameter_cm
6,Stem diameter (cm),stem_diameter_cm
7,Shoot weight before removing wilted ...,shoot_weight_before_removing_wilted_...
8,shoot weight after removing wilted l...,shoot_weight_after_removing_wilted_l...
9,Root weight (g),root_weight_g
10,No. of leaves,no_of_leaves

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 2'` (in `experiment`)

*After:* `'Experiment 2'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 60 NaN values

*After:* 60 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 78 | 78 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 78 | 78 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:

*Before:* No object columns to convert

*After:* No object columns to convert

  No object columns converted to numeric.

**Cleaning Summary for harvest:**

  Original shape: (78, 13)
  Cleaned shape:  (78, 13)
  Rows removed:   0

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 2 — taste_test

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

    Before (Raw) After (Snake Case)
0              0                  0
1              1                  1
2              2                  2
3              3                  3
4              4                  4
5              5                  5
6              6                  6
7              7                  7
8              8                  8
9              9                  9
10            10                 10
11            11                 11
12            12                 12
13            13                 13
14            14                 14

  ... and 9 more.

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

  Column Before (Untrimmed) After (Trimmed)
0      2          'Gender '        'Gender'

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 27 NaN values

*After:* 27 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 7 | 7 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 7 | 7 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:17,350 | INFO |   Converted '1' to numeric (71% success, 29% coerced to NaN).
2026-07-15 19:50:17,355 | INFO |   Converted '4' to numeric (67% success, 33% coerced to NaN).
2026-07-15 19:50:17,358 | INFO |   Converted '5' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,360 | INFO |   Converted '6' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,363 | INFO |   Converted '7' to numeric (67% success, 33% coerced to NaN).
2026-07-15 19:50:17,367 | INFO |   Converted '9' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,370 | INFO |   Converted '10' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,373 | INFO |   Converted '11' to numeric (67% success, 33% coerced to NaN).
2026-07-15 19:50:17,379 | INFO |   Converted '15' to numeric (67% success, 33% coerced to NaN).
2026-07-15 19:50:17,382 | INFO |   Converted '16' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,395 | INFO |   Converted '17' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,408 | INFO |   Converted '20' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,413 | INFO |   Converted '23' to numeric (67% success, 33% coerced to NaN).

   Column Before (Dtype) After (Dtype)
0       0            str           str
1       1            str       float64
2       2            str           str
3       3            str           str
4       4            str       float64
5       5            str       float64
6       6            str       float64
7       7            str       float64
8       8            str           str
9       9            str       float64
10     10            str       float64
11     11            str       float64
12     12            str           str
13     13            str           str
14     14            str           str
15     15            str       float64
16     16            str       float64
17     17            str       float64
18     18            str           str
19     19            str           str
20     20            str       float64
21     21            str           str
22     22            str           str
23     23            str       float64

**Cleaning Summary for taste_test:**

  Original shape: (7, 25)
  Cleaned shape:  (7, 25)
  Rows removed:   0

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 2 — form_responses

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

    Before (Raw) After (Snake Case)
0              0                  0
1              1                  1
2              2                  2
3              3                  3
4              4                  4
5              5                  5
6              6                  6
7              7                  7
8              8                  8
9              9                  9
10            10                 10
11            11                 11
12            12                 12
13            13                 13
14            14                 14

  ... and 10 more.

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

  Column Before (Untrimmed) After (Trimmed)
0      2          'Gender '        'Gender'

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 33 NaN values

*After:* 33 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 7 | 7 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 7 | 7 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:17,667 | INFO |   Converted '1' to numeric (71% success, 29% coerced to NaN).
2026-07-15 19:50:17,673 | INFO |   Converted '4' to numeric (67% success, 33% coerced to NaN).
2026-07-15 19:50:17,677 | INFO |   Converted '5' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,680 | INFO |   Converted '6' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,683 | INFO |   Converted '7' to numeric (67% success, 33% coerced to NaN).
2026-07-15 19:50:17,687 | INFO |   Converted '9' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,691 | INFO |   Converted '10' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,694 | INFO |   Converted '11' to numeric (67% success, 33% coerced to NaN).
2026-07-15 19:50:17,702 | INFO |   Converted '15' to numeric (67% success, 33% coerced to NaN).
2026-07-15 19:50:17,705 | INFO |   Converted '16' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,709 | INFO |   Converted '17' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,714 | INFO |   Converted '20' to numeric (83% success, 17% coerced to NaN).
2026-07-15 19:50:17,719 | INFO |   Converted '23' to numeric (67% success, 33% coerced to NaN).

   Column Before (Dtype) After (Dtype)
0       0            str           str
1       1            str       float64
2       2            str           str
3       3            str           str
4       4            str       float64
5       5            str       float64
6       6            str       float64
7       7            str       float64
8       8            str           str
9       9            str       float64
10     10            str       float64
11     11            str       float64
12     12            str           str
13     13            str           str
14     14            str           str
15     15            str       float64
16     16            str       float64
17     17            str       float64
18     18            str           str
19     19            str           str
20     20            str       float64
21     21            str           str
22     22            str           str
23     23            str       float64
24     24            str           str

**Cleaning Summary for form_responses:**

  Original shape: (7, 26)
  Cleaned shape:  (7, 26)
  Rows removed:   0

──────────────────────────────────────────────────────────────────────

## 📂 Experiment 3 — Cleaning

---

### 🧹 Cleaning: Experiment 3 — seedlings

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

          Before (Raw) After (Snake Case)
0            Plant NO.           plant_no
1   Plant height  (cm)    plant_height_cm
2    Shoot length (cm)    shoot_length_cm
3     Root length (cm)     root_length_cm
4   Head diameter (cm)   head_diameter_cm
5  Stem diameter  (cm)   stem_diameter_cm
6     Total weight (g)     total_weight_g
7     Shoot weight (g)     shoot_weight_g
8      Root weight (g)      root_weight_g
9        No. of leaves       no_of_leaves

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 3'` (in `experiment`)

*After:* `'Experiment 3'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 0 NaN values

*After:* 0 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 10 | 10 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 10 | 10 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:17,912 | INFO |   Converted 'plant_no' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:17,916 | INFO |   Converted 'plant_height_cm' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:17,919 | INFO |   Converted 'shoot_length_cm' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:17,922 | INFO |   Converted 'root_length_cm' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:17,925 | INFO |   Converted 'stem_diameter_cm' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:17,928 | INFO |   Converted 'total_weight_g' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:17,933 | INFO |   Converted 'shoot_weight_g' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:17,936 | INFO |   Converted 'root_weight_g' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:17,940 | INFO |   Converted 'no_of_leaves' to numeric (100% success, 0% coerced to NaN).

             Column Before (Dtype) After (Dtype)
0          plant_no            str         int64
1   plant_height_cm            str       float64
2   shoot_length_cm            str       float64
3    root_length_cm            str       float64
4  stem_diameter_cm            str       float64
5    total_weight_g            str         int64
6    shoot_weight_g            str         int64
7     root_weight_g            str         int64
8      no_of_leaves            str         int64

**Cleaning Summary for seedlings:**

  Original shape: (10, 11)
  Cleaned shape:  (10, 11)
  Rows removed:   0

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 3 — sensor_water_quality

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

   Before (Raw) After (Snake Case)
0          Date               date
1           Tme                tme
2            pH                 ph
3            EC                 ec
4           TDS                tds
5   Water temp.         water_temp
6        Date_1             date_1
7         Tme_1              tme_1
8           RH%                rh%
9     Air temp.           air_temp
10          CO2                co2

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

  Column Before (Untrimmed) After (Trimmed)
0   date                ' '              ''

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 4,272 NaN values

*After:* 4,272 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 712 | 712 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 712 | 712 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

2026-07-15 19:50:18,129 | INFO |   Converted 'date' to datetime.
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:83: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce", dayfirst=True)
2026-07-15 19:50:18,135 | INFO |   Converted 'date_1' to datetime.

   Column Before (Dtype)   After (Dtype)
0    date            str   datetime64[s]
1  date_1            str  datetime64[us]

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:18,162 | INFO |   Converted 'rh%' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,167 | INFO |   Converted 'air_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,172 | INFO |   Converted 'co2' to numeric (100% success, 0% coerced to NaN).

       Column Before (Dtype) After (Dtype)
0         tme            str           str
1          ph            str           str
2          ec            str           str
3         tds            str           str
4  water_temp            str           str
5       tme_1            str           str
6         rh%            str       float64
7    air_temp            str       float64
8         co2            str       float64

**Cleaning Summary for sensor_water_quality:**

  Original shape: (712, 13)
  Cleaned shape:  (712, 13)
  Rows removed:   0

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 3 — portable_water_quality

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

*Before:* `experiment`, `date`, `100000_replicate_1_t1_ph`, `100000_replicate_1_t1_ec`, `100000_replicate_1_t1_tds`...

*After:* `experiment`, `date`, `100000_replicate_1_t1_ph`, `100000_replicate_1_t1_ec`, `100000_replicate_1_t1_tds`...

  No changes needed.

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 3'` (in `experiment`)

*After:* `'Experiment 3'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

                              Column Before (Placeholder) After (Converted)
0           100000_replicate_1_t1_ph       '-' (count: 5)               NaN
1           100000_replicate_1_t1_ec       '-' (count: 4)               NaN
2          100000_replicate_1_t1_tds       '-' (count: 4)               NaN
3   100000_replicate_1_t1_water_temp       '-' (count: 4)               NaN
4           100000_replicate_2_t1_ph       '-' (count: 4)               NaN
5           100000_replicate_2_t1_ec       '-' (count: 4)               NaN
6          100000_replicate_2_t1_tds       '-' (count: 4)               NaN
7   100000_replicate_2_t1_water_temp       '-' (count: 4)               NaN
8           100000_replicate_3_t1_ph       '-' (count: 4)               NaN
9           100000_replicate_3_t1_ec       '-' (count: 4)               NaN
10         100000_replicate_3_t1_tds       '-' (count: 4)               NaN
11  100000_replicate_3_t1_water_temp       '-' (count: 4)               NaN
12          100000_replicate_1_t2_ph       '-' (count: 4)               NaN
13          100000_replicate_1_t2_ec       '-' (count: 4)               NaN
14         100000_replicate_1_t2_tds       '-' (count: 4)               NaN
15  100000_replicate_1_t2_water_temp       '-' (count: 4)               NaN
16          100000_replicate_2_t2_ph       '-' (count: 4)               NaN
17          100000_replicate_2_t2_ec       '-' (count: 4)               NaN
18         100000_replicate_2_t2_tds       '-' (count: 4)               NaN
19  100000_replicate_2_t2_water_temp       '-' (count: 4)               NaN
20          100000_replicate_3_t2_ph       '-' (count: 4)               NaN
21          100000_replicate_3_t2_ec       '-' (count: 4)               NaN
22         100000_replicate_3_t2_tds       '-' (count: 4)               NaN
23  100000_replicate_3_t2_water_temp       '-' (count: 6)               NaN
24         100000_air_air_parameters       '-' (count: 8)               NaN
25            100000_air_temp_col_26       '-' (count: 8)               NaN
26                 100000_rh%_col_27       '-' (count: 8)               NaN
27          140000_replicate_1_t1_ph       '-' (count: 4)               NaN
28          140000_replicate_1_t1_ec       '-' (count: 4)               NaN
29         140000_replicate_1_t1_tds       '-' (count: 4)               NaN
30  140000_replicate_1_t1_water_temp       '-' (count: 4)               NaN
31          140000_replicate_2_t1_ph       '-' (count: 4)               NaN
32          140000_replicate_2_t1_ec       '-' (count: 4)               NaN
33         140000_replicate_2_t1_tds       '-' (count: 4)               NaN
34  140000_replicate_2_t1_water_temp       '-' (count: 4)               NaN
35          140000_replicate_3_t1_ph       '-' (count: 4)               NaN
36          140000_replicate_3_t1_ec       '-' (count: 4)               NaN
37         140000_replicate_3_t1_tds       '-' (count: 4)               NaN
38  140000_replicate_3_t1_water_temp       '-' (count: 5)               NaN
39          140000_replicate_1_t2_ph       '-' (count: 5)               NaN
40          140000_replicate_1_t2_ec       '-' (count: 5)               NaN
41         140000_replicate_1_t2_tds       '-' (count: 5)               NaN
42  140000_replicate_1_t2_water_temp       '-' (count: 5)               NaN
43          140000_replicate_2_t2_ph       '-' (count: 5)               NaN
44          140000_replicate_2_t2_ec       '-' (count: 5)               NaN
45         140000_replicate_2_t2_tds       '-' (count: 5)               NaN
46  140000_replicate_2_t2_water_temp       '-' (count: 5)               NaN
47          140000_replicate_3_t2_ph       '-' (count: 5)               NaN
48          140000_replicate_3_t2_ec       '-' (count: 5)               NaN
49         140000_replicate_3_t2_tds       '-' (count: 5)               NaN
50  140000_replicate_3_t2_water_temp       '-' (count: 5)               NaN
51         140000_air_air_parameters       '-' (count: 9)               NaN
52            140000_air_temp_col_54       '-' (count: 9)               NaN
53                 140000_rh%_col_55       '-' (count: 9)               NaN

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 33 | 33 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 33 | 33 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

2026-07-15 19:50:18,544 | INFO |   Converted 'date' to datetime.

  Column Before (Dtype)   After (Dtype)
0   date            str  datetime64[us]

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:18,568 | INFO |   Converted '100000_replicate_1_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,571 | INFO |   Converted '100000_replicate_1_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,574 | INFO |   Converted '100000_replicate_1_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,577 | INFO |   Converted '100000_replicate_1_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,580 | INFO |   Converted '100000_replicate_2_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,584 | INFO |   Converted '100000_replicate_2_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,587 | INFO |   Converted '100000_replicate_2_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,589 | INFO |   Converted '100000_replicate_2_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,592 | INFO |   Converted '100000_replicate_3_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,596 | INFO |   Converted '100000_replicate_3_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,600 | INFO |   Converted '100000_replicate_3_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,605 | INFO |   Converted '100000_replicate_3_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,608 | INFO |   Converted '100000_replicate_1_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,611 | INFO |   Converted '100000_replicate_1_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,614 | INFO |   Converted '100000_replicate_1_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,619 | INFO |   Converted '100000_replicate_1_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,622 | INFO |   Converted '100000_replicate_2_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,626 | INFO |   Converted '100000_replicate_2_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,630 | INFO |   Converted '100000_replicate_2_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,633 | INFO |   Converted '100000_replicate_2_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,637 | INFO |   Converted '100000_replicate_3_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,639 | INFO |   Converted '100000_replicate_3_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,642 | INFO |   Converted '100000_replicate_3_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,645 | INFO |   Converted '100000_replicate_3_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,648 | INFO |   Converted '100000_air_air_parameters' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,652 | INFO |   Converted '100000_air_temp_col_26' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,655 | INFO |   Converted '100000_rh%_col_27' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,658 | INFO |   Converted '140000_replicate_1_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,661 | INFO |   Converted '140000_replicate_1_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,663 | INFO |   Converted '140000_replicate_1_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,666 | INFO |   Converted '140000_replicate_1_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,669 | INFO |   Converted '140000_replicate_2_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,672 | INFO |   Converted '140000_replicate_2_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,675 | INFO |   Converted '140000_replicate_2_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,677 | INFO |   Converted '140000_replicate_2_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,679 | INFO |   Converted '140000_replicate_3_t1_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,681 | INFO |   Converted '140000_replicate_3_t1_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,683 | INFO |   Converted '140000_replicate_3_t1_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,686 | INFO |   Converted '140000_replicate_3_t1_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,690 | INFO |   Converted '140000_replicate_1_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,692 | INFO |   Converted '140000_replicate_1_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,695 | INFO |   Converted '140000_replicate_1_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,697 | INFO |   Converted '140000_replicate_1_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,699 | INFO |   Converted '140000_replicate_2_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,702 | INFO |   Converted '140000_replicate_2_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,705 | INFO |   Converted '140000_replicate_2_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,708 | INFO |   Converted '140000_replicate_2_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,711 | INFO |   Converted '140000_replicate_3_t2_ph' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,714 | INFO |   Converted '140000_replicate_3_t2_ec' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,717 | INFO |   Converted '140000_replicate_3_t2_tds' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,721 | INFO |   Converted '140000_replicate_3_t2_water_temp' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,723 | INFO |   Converted '140000_air_air_parameters' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,726 | INFO |   Converted '140000_air_temp_col_54' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:18,730 | INFO |   Converted '140000_rh%_col_55' to numeric (100% success, 0% coerced to NaN).

                              Column Before (Dtype) After (Dtype)
0           100000_replicate_1_t1_ph            str       float64
1           100000_replicate_1_t1_ec            str       float64
2          100000_replicate_1_t1_tds            str       float64
3   100000_replicate_1_t1_water_temp            str       float64
4           100000_replicate_2_t1_ph            str       float64
5           100000_replicate_2_t1_ec            str       float64
6          100000_replicate_2_t1_tds            str       float64
7   100000_replicate_2_t1_water_temp            str       float64
8           100000_replicate_3_t1_ph            str       float64
9           100000_replicate_3_t1_ec            str       float64
10         100000_replicate_3_t1_tds            str       float64
11  100000_replicate_3_t1_water_temp            str       float64
12          100000_replicate_1_t2_ph            str       float64
13          100000_replicate_1_t2_ec            str       float64
14         100000_replicate_1_t2_tds            str       float64
15  100000_replicate_1_t2_water_temp            str       float64
16          100000_replicate_2_t2_ph            str       float64
17          100000_replicate_2_t2_ec            str       float64
18         100000_replicate_2_t2_tds            str       float64
19  100000_replicate_2_t2_water_temp            str       float64
20          100000_replicate_3_t2_ph            str       float64
21          100000_replicate_3_t2_ec            str       float64
22         100000_replicate_3_t2_tds            str       float64
23  100000_replicate_3_t2_water_temp            str       float64
24         100000_air_air_parameters            str       float64
25            100000_air_temp_col_26            str       float64
26                 100000_rh%_col_27            str       float64
27          140000_replicate_1_t1_ph            str       float64
28          140000_replicate_1_t1_ec            str       float64
29         140000_replicate_1_t1_tds            str       float64
30  140000_replicate_1_t1_water_temp            str       float64
31          140000_replicate_2_t1_ph            str       float64
32          140000_replicate_2_t1_ec            str       float64
33         140000_replicate_2_t1_tds            str       float64
34  140000_replicate_2_t1_water_temp            str       float64
35          140000_replicate_3_t1_ph            str       float64
36          140000_replicate_3_t1_ec            str       float64
37         140000_replicate_3_t1_tds            str       float64
38  140000_replicate_3_t1_water_temp            str       float64
39          140000_replicate_1_t2_ph            str       float64
40          140000_replicate_1_t2_ec            str       float64
41         140000_replicate_1_t2_tds            str       float64
42  140000_replicate_1_t2_water_temp            str       float64
43          140000_replicate_2_t2_ph            str       float64
44          140000_replicate_2_t2_ec            str       float64
45         140000_replicate_2_t2_tds            str       float64
46  140000_replicate_2_t2_water_temp            str       float64
47          140000_replicate_3_t2_ph            str       float64
48          140000_replicate_3_t2_ec            str       float64
49         140000_replicate_3_t2_tds            str       float64
50  140000_replicate_3_t2_water_temp            str       float64
51         140000_air_air_parameters            str       float64
52            140000_air_temp_col_54            str       float64
53                 140000_rh%_col_55            str       float64

**Cleaning Summary for portable_water_quality:**

  Original shape: (33, 57)
  Cleaned shape:  (33, 57)
  Rows removed:   0

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 3 — nutrients_date

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

*Before:* `experiment`, `date`

*After:* `experiment`, `date`

  No changes needed.

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

  Column Before (Untrimmed) After (Trimmed)
0   date           'Total '         'Total'

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 8 NaN values

*After:* 8 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 11 | 3 | 8 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 3 | 3 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

2026-07-15 19:50:18,862 | INFO |   Converted 'date' to datetime.

  Column Before (Dtype)   After (Dtype)
0   date            str  datetime64[us]

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:

*Before:* No object columns to convert

*After:* No object columns to convert

  No object columns converted to numeric.

**Cleaning Summary for nutrients_date:**

  Original shape: (11, 2)
  Cleaned shape:  (3, 2)
  Rows removed:   8

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 3 — nutrients_nutrient_solution_addition_(a+b)_ml

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

     Before (Raw) After (Snake Case)
0  Replicate_1_T1     replicate_1_t1
1  Replicate_2_T1     replicate_2_t1
2  Replicate_3_T1     replicate_3_t1
3  Replicate_1_T2     replicate_1_t2
4  Replicate_2_T2     replicate_2_t2
5  Replicate_3_T2     replicate_3_t2

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 3'` (in `experiment`)

*After:* `'Experiment 3'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 48 NaN values

*After:* 48 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 11 | 3 | 8 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 3 | 3 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:19,036 | INFO |   Converted 'replicate_1_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,039 | INFO |   Converted 'replicate_2_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,042 | INFO |   Converted 'replicate_3_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,044 | INFO |   Converted 'replicate_1_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,047 | INFO |   Converted 'replicate_2_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,049 | INFO |   Converted 'replicate_3_t2' to numeric (100% success, 0% coerced to NaN).

           Column Before (Dtype) After (Dtype)
0  replicate_1_t1            str         int64
1  replicate_2_t1            str         int64
2  replicate_3_t1            str         int64
3  replicate_1_t2            str         int64
4  replicate_2_t2            str         int64
5  replicate_3_t2            str         int64

**Cleaning Summary for nutrients_nutrient_solution_addition_(a+b)_ml:**

  Original shape: (11, 7)
  Cleaned shape:  (3, 7)
  Rows removed:   8

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 3 — nutrients_water_consumption_l

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

     Before (Raw) After (Snake Case)
0  Replicate_1_T1     replicate_1_t1
1  Replicate_2_T1     replicate_2_t1
2  Replicate_3_T1     replicate_3_t1
3  Replicate_1_T2     replicate_1_t2
4  Replicate_2_T2     replicate_2_t2
5  Replicate_3_T2     replicate_3_t2

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 3'` (in `experiment`)

*After:* `'Experiment 3'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 42 NaN values

*After:* 42 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 11 | 4 | 7 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 4 | 4 | 0 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:19,196 | INFO |   Converted 'replicate_1_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,199 | INFO |   Converted 'replicate_2_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,202 | INFO |   Converted 'replicate_3_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,205 | INFO |   Converted 'replicate_1_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,208 | INFO |   Converted 'replicate_2_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,210 | INFO |   Converted 'replicate_3_t2' to numeric (100% success, 0% coerced to NaN).

           Column Before (Dtype) After (Dtype)
0  replicate_1_t1            str         int64
1  replicate_2_t1            str         int64
2  replicate_3_t1            str         int64
3  replicate_1_t2            str         int64
4  replicate_2_t2            str         int64
5  replicate_3_t2            str         int64

**Cleaning Summary for nutrients_water_consumption_l:**

  Original shape: (11, 7)
  Cleaned shape:  (4, 7)
  Rows removed:   7

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 3 — nutrients_acid_consumption_ml

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

     Before (Raw) After (Snake Case)
0  Replicate_1_T1     replicate_1_t1
1  Replicate_2_T1     replicate_2_t1
2  Replicate_3_T1     replicate_3_t1
3  Replicate_1_T2     replicate_1_t2
4  Replicate_2_T2     replicate_2_t2
5  Replicate_3_T2     replicate_3_t2

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

*Before:* `'Experiment 3'` (in `experiment`)

*After:* `'Experiment 3'` (in `experiment`)

  No leading/trailing whitespace detected.

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 48 NaN values

*After:* 48 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 11 | 3 | 8 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 3 | 2 | 1 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:19,352 | INFO |   Converted 'replicate_1_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,354 | INFO |   Converted 'replicate_2_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,357 | INFO |   Converted 'replicate_3_t1' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,359 | INFO |   Converted 'replicate_1_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,361 | INFO |   Converted 'replicate_2_t2' to numeric (100% success, 0% coerced to NaN).
2026-07-15 19:50:19,363 | INFO |   Converted 'replicate_3_t2' to numeric (100% success, 0% coerced to NaN).

           Column Before (Dtype) After (Dtype)
0  replicate_1_t1            str         int64
1  replicate_2_t1            str         int64
2  replicate_3_t1            str         int64
3  replicate_1_t2            str         int64
4  replicate_2_t2            str         int64
5  replicate_3_t2            str         int64

**Cleaning Summary for nutrients_acid_consumption_ml:**

  Original shape: (11, 7)
  Cleaned shape:  (2, 7)
  Rows removed:   9

──────────────────────────────────────────────────────────────────────

### 🧹 Cleaning: Experiment 3 — harvest

**Step 1: Standardize column names to snake_case**

*Reason:* Consistent naming convention for downstream processing.

,Before (Raw),After (Snake Case)
0,Plant No.,plant_no
1,Plant height (cm),plant_height_cm
2,Shoot length (cm),shoot_length_cm
3,Root length (cm),root_length_cm
4,H.D (cm),hd_cm
5,Total weight (g),total_weight_g
6,Stem diameter (cm),stem_diameter_cm
7,Shoot weight before removing wilted ...,shoot_weight_before_removing_wilted_...
8,Shoot weight after removing wilted l...,shoot_weight_after_removing_wilted_l...
9,Root weight (g),root_weight_g
10,No.of leaves,noof_leaves

**Step 2: Trim string whitespace**

*Reason:* Remove invisible whitespace that causes false mismatches.

,Column,Before (Untrimmed),After (Trimmed)
0,system,'System ','System'
1,shoot_weight_before_removing_wilted_...,'Shoot weight before removing wilted...,'Shoot weight before removing wilted...
2,shoot_weight_after_removing_wilted_l...,'Shoot weight after removing wilted ...,'Shoot weight after removing wilted ...
3,root_weight_g,'Root weight (g) ','Root weight (g)'
4,noof_leaves,'No.of leaves ','No.of leaves'

**Step 3: Replace dash/placeholder values with NaN**

*Reason:* Dashes ('-') and placeholders are used as 'no data' markers, not valid measurements.

*Before:* 12 NaN values

*After:* 12 NaN values

  No dash/placeholder values detected.

**Step 4: Remove fully empty rows**

*Reason:* Rows with no data (all NaN) are structural artifacts from Excel.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 83 | 83 | 0 |

**Step 5: Remove exact duplicate rows**

*Reason:* Exact duplicates are data entry artifacts, not real observations.

| Metric | Before | After | Removed |

|---|---|---|---|

| Row Count | 83 | 79 | 4 |

**Step 6: Convert date columns to datetime**

*Reason:* Enable time-series analysis and proper sorting.

*Before:* No date columns

*After:* No date columns

  No date columns detected.

**Step 7: Convert object columns to numeric where appropriate**

*Reason:* Some numeric measurements are stored as strings due to Excel parsing. Columns with >50% numeric success rate are converted; non-convertible values become NaN.

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\4227539317.py:140: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = [c for c in df_clean.select_dtypes(include=["object"]).columns if c not in text_keep and c not in {"experiment", "replicate", "system", "day"}]
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_18536\1126182943.py:99: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=["object"]).columns:
2026-07-15 19:50:19,543 | INFO |   Converted 'plant_no' to numeric (99% success, 1% coerced to NaN).
2026-07-15 19:50:19,546 | INFO |   Converted 'plant_height_cm' to numeric (99% success, 1% coerced to NaN).
2026-07-15 19:50:19,548 | INFO |   Converted 'shoot_length_cm' to numeric (99% success, 1% coerced to NaN).
2026-07-15 19:50:19,551 | INFO |   Converted 'root_length_cm' to numeric (99% success, 1% coerced to NaN).
2026-07-15 19:50:19,555 | INFO |   Converted 'total_weight_g' to numeric (99% success, 1% coerced to NaN).
2026-07-15 19:50:19,557 | INFO |   Converted 'stem_diameter_cm' to numeric (99% success, 1% coerced to NaN).
2026-07-15 19:50:19,560 | INFO |   Converted 'shoot_weight_before_removing_wilted_leaves_g' to numeric (99% success, 1% coerced to NaN).
2026-07-15 19:50:19,563 | INFO |   Converted 'shoot_weight_after_removing_wilted_leaves_g' to numeric (99% success, 1% coerced to NaN).
2026-07-15 19:50:19,566 | INFO |   Converted 'root_weight_g' to numeric (99% success, 1% coerced to NaN).
2026-07-15 19:50:19,568 | INFO |   Converted 'noof_leaves' to numeric (99% success, 1% coerced to NaN).

                                     Column Before (Dtype) After (Dtype)
0                                  plant_no            str       float64
1                           plant_height_cm            str       float64
2                           shoot_length_cm            str       float64
3                            root_length_cm            str       float64
4                                     hd_cm            str           str
5                            total_weight_g            str       float64
6                          stem_diameter_cm            str       float64
7   shoot_weight_before_removing_wilted_...            str       float64
8   shoot_weight_after_removing_wilted_l...            str       float64
9                             root_weight_g            str       float64
10                              noof_leaves            str       float64

**Cleaning Summary for harvest:**

2026-07-15 19:50:19,589 | INFO | Cleaning complete for all datasets.

  Original shape: (83, 13)
  Cleaned shape:  (79, 13)
  Rows removed:   4

──────────────────────────────────────────────────────────────────────


✅ All datasets cleaned.

---

## 7 · Validation

After cleaning, we re-run the **entire quality assessment suite** on the cleaned data to:
1. Confirm that cleaning steps had the desired effect.
2. Verify no new issues were introduced.
3. Document the remaining data quality state.

> Any remaining issues flagged here are documented but **not automatically fixed** — they require domain-expert review.

In [23]:
# ==========================================================================
# Post-cleaning validation
# ==========================================================================
validation_reports: Dict[str, Dict[str, Dict]] = {}

for exp_label, tables in cleaned_data.items():
    display(Markdown(f"## ✅ {exp_label} — Post-Cleaning Validation"))
    display(Markdown("---"))
    validation_reports[exp_label] = {}

    for tname, tdata in tables.items():
        if isinstance(tdata, pd.DataFrame) and not tdata.empty:
            validation_reports[exp_label][tname] = run_quality_assessment(
                tdata, f"{exp_label} — {tname} (POST-CLEANING)"
            )

logger.info("Post-cleaning validation complete.")

## ✅ Experiment 1 — Post-Cleaning Validation

---

### 🔍 Experiment 1 — seedlings (POST-CLEANING)

**Missing Values:**

      missing_count  missing_pct           dtype
date              9      90.0000  datetime64[us]

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 3 column(s) with ≤1 unique value: `experiment`, `date`, `stem_diameter_cm`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,10,10.0000,['Experiment 1']
date,1,10,10.0000,[Timestamp('2024-03-09 00:00:00')]
plant_no,10,10,100.0000,"[1, 2, 3, 4, 5]"
plant_height_cm,4,10,40.0000,"[9.0, 10.0, 9.5, 12.0]"
shoot_length_cm,3,10,30.0000,"[2.0, 3.0, 2.5]"
root_length_cm,3,10,30.0000,"[7.0, 6.5, 9.0]"
head_diameter_cm,7,10,70.0000,"['4*2', '3.5*3', '3.5*2.5', '3*3', '..."
stem_diameter_cm,1,10,10.0000,[0.1]
total_weight_g,7,10,70.0000,"[1.3, 1.2, 1.1, 1.14, 1.0]"
shoot_weight_g,9,10,90.0000,"[0.5, 0.55, 0.53, 0.45, 0.4]"
root_weight_g,9,10,90.0000,"[0.8, 0.6499999999999999, 0.57000000..."
no_of_leaves,2,10,20.0000,"[5, 4]"

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,plant_height_cm,9.0000,10.0000,1.0000,7.5000,11.5000,1,10.0000
1,root_length_cm,7.0000,7.0000,0.0000,7.0000,7.0000,3,30.0000

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — sensor_water_quality (POST-CLEANING)

**Missing Values:**

            missing_count  missing_pct           dtype
date                  641     100.0000   datetime64[s]
tme                   641     100.0000             str
ph                    641     100.0000             str
ec                    641     100.0000             str
tds                   641     100.0000             str
water_temp            641     100.0000             str
date_1                449      70.0500  datetime64[us]
tme_1                   1       0.1600             str
rh_%                    1       0.1600         float64
air_temp_c              1       0.1600         float64
co2_ppm                 1       0.1600         float64

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 8 column(s) with ≤1 unique value: `experiment`, `replicate`, `date`, `tme`, `ph`, `ec`, `tds`, `water_temp`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,641,0.1600,['Experiment 1']
replicate,1,641,0.1600,['Replicate 1 T1']
date,0,641,0.0000,[]
tme,0,641,0.0000,[]
ph,0,641,0.0000,[]
ec,0,641,0.0000,[]
tds,0,641,0.0000,[]
water_temp,0,641,0.0000,[]
date_1,10,641,1.5600,"[Timestamp('2024-10-03 00:00:00'), T..."
tme_1,24,641,3.7400,"['10:00:00', '11:00:00', '12:00:00',..."
rh_%,554,641,86.4300,"[49.08, 47.51, 46.8, 47.12, 47.64]"
air_temp_c,512,641,79.8800,"[24.18, 23.55, 23.81, 24.48, 24.74]"
co2_ppm,620,641,96.7200,"[406.96, 406.55, 413.38, 412.5, 408.94]"

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — portable_water_quality (POST-CLEANING)

**Missing Values:**

                                  missing_count  missing_pct           dtype
100000_air_temp_col_28                       32     100.0000         float64
140000_air_temp_col_55                       25      78.1200         float64
140000_rh%_col_54                            25      78.1200         float64
140000_air_air_parameters                    25      78.1200         float64
date                                         21      65.6200  datetime64[us]
100000_rh%_col_26                            18      56.2500         float64
100000_air_air_parameters                    18      56.2500         float64
100000_air_temp_col_27                       18      56.2500         float64
140000_replicate_1_t1_water_temp             14      43.7500         float64
140000_replicate_2_t1_ph                     14      43.7500         float64
140000_replicate_1_t1_ph                     14      43.7500         float64
140000_replicate_3_t1_water_temp             14      43.7500         float64
140000_replicate_2_t1_water_temp             14      43.7500         float64
140000_replicate_2_t1_ec                     14      43.7500         float64
140000_replicate_3_t1_ph                     14      43.7500         float64
140000_replicate_3_t1_ec                     14      43.7500         float64
140000_replicate_1_t1_ec                     14      43.7500         float64
140000_replicate_1_t2_ec                     14      43.7500         float64
140000_replicate_1_t2_ph                     14      43.7500         float64
140000_replicate_2_t2_ec                     14      43.7500         float64
140000_replicate_2_t2_water_temp             14      43.7500         float64
140000_replicate_2_t2_ph                     14      43.7500         float64
140000_replicate_3_t2_ec                     14      43.7500         float64
140000_replicate_3_t2_ph                     14      43.7500         float64
140000_replicate_3_t2_water_temp             14      43.7500         float64
140000_replicate_1_t2_water_temp             14      43.7500         float64
100000_replicate_2_t1_ph                     12      37.5000         float64
100000_replicate_3_t1_ph                     12      37.5000         float64
100000_replicate_1_t1_water_temp             12      37.5000         float64
100000_replicate_1_t1_ec                     12      37.5000         float64
100000_replicate_2_t2_water_temp             12      37.5000         float64
100000_replicate_2_t1_ec                     12      37.5000         float64
100000_replicate_2_t1_water_temp             12      37.5000         float64
100000_replicate_2_t2_ph                     12      37.5000         float64
100000_replicate_1_t2_ph                     12      37.5000         float64
100000_replicate_1_t2_ec                     12      37.5000         float64
100000_replicate_3_t1_water_temp             12      37.5000         float64
100000_replicate_3_t1_ec                     12      37.5000         float64
100000_replicate_3_t2_ph                     12      37.5000         float64
100000_replicate_3_t2_ec                     12      37.5000         float64
100000_replicate_1_t2_water_temp             12      37.5000         float64
140000_replicate_2_t1_tds                    12      37.5000         float64
100000_replicate_3_t2_water_temp             12      37.5000         float64
140000_replicate_1_t1_tds                    12      37.5000         float64
140000_replicate_3_t1_tds                    12      37.5000         float64
140000_replicate_1_t2_tds                    12      37.5000         float64
100000_replicate_1_t1_ph                     12      37.5000         float64
100000_replicate_2_t2_ec                     12      37.5000         float64
140000_replicate_2_t2_tds                    12      37.5000         float64
140000_replicate_3_t2_tds                    12      37.5000         float64
100000_replicate_3_t2_tds                    11      34.3800         float64
100000_replicate_2_t2_tds                    11      34.3800         float64
100000_replicate_1_t1_tds                    11      34.3800         float64
100000_replicate_2_t1_tds                    11      34.3800         float64
100000_replicate_3_t1_tds                    11      34.3800         float64
100000_replicate_1_t2_tds                    11      34.3800         float64

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 2 column(s) with ≤1 unique value: `experiment`, `100000_air_temp_col_28`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,32,3.1200,['Experiment 1']
date,11,32,34.3800,"[Timestamp('2024-03-10 00:00:00'), T..."
100000_replicate_1_t1_ph,12,32,37.5000,"[5.3, 5.7, 5.9, 6.0, 5.8]"
100000_replicate_1_t1_ec,18,32,56.2500,"[2.0, 1.95, 1.97, 1.92, 1.94]"
100000_replicate_1_t1_tds,19,32,59.3800,"[1.0, 0.975, 0.985, 0.96, 0.97]"
100000_replicate_1_t1_water_temp,17,32,53.1200,"[19.3, 22.0, 26.6, 24.3, 23.0]"
100000_replicate_2_t1_ph,9,32,28.1200,"[5.8, 6.0, 5.9, 5.7, 5.5]"
100000_replicate_2_t1_ec,17,32,53.1200,"[2.02, 2.0, 2.03, 2.01, 1.94]"
100000_replicate_2_t1_tds,18,32,56.2500,"[1.01, 1.0, 1.015, 1.005, 0.97]"
100000_replicate_2_t1_water_temp,15,32,46.8800,"[19.1, 21.2, 22.0, 25.1, 24.9]"
100000_replicate_3_t1_ph,12,32,37.5000,"[5.6, 5.7, 5.8, 5.4, 5.5]"
100000_replicate_3_t1_ec,16,32,50.0000,"[2.02, 2.01, 1.99, 2.03, 1.96]"
100000_replicate_3_t1_tds,17,32,53.1200,"[1.01, 1.005, 0.995, 1.015, 0.98]"
100000_replicate_3_t1_water_temp,19,32,59.3800,"[18.9, 20.6, 22.0, 24.0, 24.8]"
100000_replicate_1_t2_ph,12,32,37.5000,"[5.6, 5.4, 5.5, 5.1, 5.2]"
100000_replicate_1_t2_ec,15,32,46.8800,"[1.94, 1.98, 1.96, 1.95, 1.89]"
100000_replicate_1_t2_tds,16,32,50.0000,"[0.97, 0.99, 0.98, 0.975, 0.945]"
100000_replicate_1_t2_water_temp,17,32,53.1200,"[18.6, 21.4, 22.0, 25.0, 26.2]"
100000_replicate_2_t2_ph,11,32,34.3800,"[5.8, 5.9, 5.5, 5.7, 5.4]"
100000_replicate_2_t2_ec,17,32,53.1200,"[2.01, 2.02, 2.03, 2.0, 2.1]"
100000_replicate_2_t2_tds,18,32,56.2500,"[1.005, 1.01, 1.015, 1.0, 1.05]"
100000_replicate_2_t2_water_temp,17,32,53.1200,"[19.7, 22.0, 22.4, 22.9, 23.4]"
100000_replicate_3_t2_ph,11,32,34.3800,"[5.6, 6.9, 6.5, 6.4, 6.0]"
100000_replicate_3_t2_ec,14,32,43.7500,"[2.16, 1.54, 1.87, 1.82, 1.88]"
100000_replicate_3_t2_tds,15,32,46.8800,"[1.08, 0.77, 0.935, 0.91, 0.94]"
100000_replicate_3_t2_water_temp,18,32,56.2500,"[22.9, 22.6, 23.0, 26.2, 28.5]"
100000_air_air_parameters,14,32,43.7500,"[50330.0, 60540.0, 22050.0, 38880.0,..."
100000_rh%_col_26,14,32,43.7500,"[64.0, 45.0, 60.0, 68.1, 65.3]"
100000_air_temp_col_27,14,32,43.7500,"[20.4, 29.5, 23.5, 22.3, 21.8]"
100000_air_temp_col_28,0,32,0.0000,[]
140000_replicate_1_t1_ph,12,32,37.5000,"[6.9, 5.2, 5.7, 6.0, 5.6]"
140000_replicate_1_t1_ec,15,32,46.8800,"[1.61, 2.0, 1.94, 2.02, 1.93]"
140000_replicate_1_t1_tds,14,32,43.7500,"[0.8, 1.0, 0.97, 1.01, 0.965]"
140000_replicate_1_t1_water_temp,15,32,46.8800,"[22.5, 23.9, 25.7, 22.0, 26.0]"
140000_replicate_2_t1_ph,7,32,21.8800,"[6.9, 5.8, 6.0, 6.1, 5.7]"
140000_replicate_2_t1_ec,13,32,40.6200,"[1.57, 2.02, 2.01, 1.89, 1.9]"
140000_replicate_2_t1_tds,13,32,40.6200,"[0.78, 1.01, 1.005, 0.945, 0.95]"
140000_replicate_2_t1_water_temp,17,32,53.1200,"[22.5, 22.1, 25.7, 25.4, 24.8]"
140000_replicate_3_t1_ph,8,32,25.0000,"[6.9, 5.7, 5.9, 5.8, 6.4]"
140000_replicate_3_t1_ec,16,32,50.0000,"[1.56, 2.01, 2.0, 1.98, 2.02]"
140000_replicate_3_t1_tds,15,32,46.8800,"[0.78, 1.005, 1.0, 0.99, 1.01]"
140000_replicate_3_t1_water_temp,15,32,46.8800,"[22.3, 26.0, 25.0, 24.1, 24.9]"
140000_replicate_1_t2_ph,10,32,31.2500,"[6.8, 5.4, 5.5, 5.6, 5.7]"
140000_replicate_1_t2_ec,15,32,46.8800,"[1.57, 1.94, 1.98, 1.95, 1.75]"
140000_replicate_1_t2_tds,14,32,43.7500,"[0.78, 0.97, 0.99, 0.975, 0.875]"
140000_replicate_1_t2_water_temp,16,32,50.0000,"[22.7, 22.5, 25.4, 25.3, 26.0]"
140000_replicate_2_t2_ph,9,32,28.1200,"[7.0, 5.8, 5.9, 6.0, 6.1]"
140000_replicate_2_t2_ec,14,32,43.7500,"[1.56, 2.02, 2.01, 1.78, 1.79]"
140000_replicate_2_t2_tds,13,32,40.6200,"[0.77, 1.01, 1.005, 0.89, 0.895]"
140000_replicate_2_t2_water_temp,16,32,50.0000,"[22.9, 22.3, 25.5, 25.4, 25.6]"
140000_replicate_3_t2_ph,12,32,37.5000,"[6.9, 5.6, 6.3, 6.5, 6.4]"
140000_replicate_3_t2_ec,15,32,46.8800,"[1.56, 2.16, 1.86, 1.87, 1.82]"
140000_replicate_3_t2_tds,14,32,43.7500,"[0.76, 1.08, 0.93, 0.935, 0.91]"
140000_replicate_3_t2_water_temp,16,32,50.0000,"[23.0, 22.9, 26.0, 28.0, 24.7]"
140000_air_air_parameters,7,32,21.8800,"[48300.0, 61270.0, 45190.0, 36530.0,..."
140000_rh%_col_54,7,32,21.8800,"[60.8, 59.5, 55.0, 54.8, 61.7]"
140000_air_temp_col_55,7,32,21.8800,"[22.1, 21.8, 26.7, 25.1, 26.3]"

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,100000_replicate_1_t1_tds,0.8850,0.9600,0.0750,0.7725,1.0725,1,3.1200
1,100000_replicate_2_t1_ph,5.8000,6.0500,0.2500,5.4250,6.4250,2,6.2500
2,100000_replicate_2_t1_tds,0.8850,1.0000,0.1150,0.7125,1.1725,1,3.1200
3,100000_replicate_3_t1_tds,0.8900,1.0050,0.1150,0.7175,1.1775,1,3.1200
4,100000_replicate_3_t1_water_temp,22.5500,24.8250,2.2750,19.1375,28.2375,1,3.1200
5,100000_replicate_1_t2_tds,0.8950,0.9700,0.0750,0.7825,1.0825,1,3.1200
6,100000_replicate_1_t2_water_temp,23.3500,25.4250,2.0750,20.2375,28.5375,2,6.2500
7,100000_replicate_2_t2_ph,5.8750,6.2000,0.3250,5.3875,6.6875,3,9.3800
8,100000_replicate_2_t2_ec,1.7800,2.0025,0.2225,1.4462,2.3362,1,3.1200
9,100000_replicate_2_t2_tds,0.8900,1.0000,0.1100,0.7250,1.1650,2,6.2500
10,100000_replicate_3_t2_ec,1.7300,1.8400,0.1100,1.5650,2.0050,2,6.2500
11,100000_replicate_3_t2_tds,0.8650,0.9200,0.0550,0.7825,1.0025,3,9.3800
12,100000_rh%_col_26,57.0500,63.0750,6.0250,48.0125,72.1125,2,6.2500
13,140000_replicate_1_t1_ec,1.7225,1.8925,0.1700,1.4675,2.1475,1,3.1200
14,140000_replicate_1_t1_tds,0.7538,0.9388,0.1850,0.4763,1.2162,4,12.5000
15,140000_replicate_2_t1_ec,1.7600,1.9825,0.2225,1.4262,2.3162,1,3.1200
16,140000_replicate_2_t1_tds,0.7288,0.9637,0.2350,0.3763,1.3162,4,12.5000
17,140000_replicate_3_t1_tds,0.7463,0.9562,0.2100,0.4313,1.2712,4,12.5000
18,140000_replicate_1_t2_tds,0.7738,0.9362,0.1625,0.5300,1.1800,4,12.5000
19,140000_replicate_2_t2_ec,1.6475,1.9750,0.3275,1.1562,2.4662,1,3.1200
20,140000_replicate_2_t2_tds,0.6925,0.9525,0.2600,0.3025,1.3425,4,12.5000
21,140000_replicate_3_t2_ec,1.6725,1.8200,0.1475,1.4512,2.0413,3,9.3800
22,140000_replicate_3_t2_tds,0.6825,0.9100,0.2275,0.3412,1.2513,4,12.5000

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — nutrients_date (POST-CLEANING)

**Missing Values:**

      missing_count  missing_pct           dtype
date              3      60.0000  datetime64[us]

**Duplicate Rows:** ⚠️ **2** exact duplicates found.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,5,20.0000,['Experiment 1']
date,2,5,40.0000,"[Timestamp('2024-03-11 00:00:00'), T..."

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — nutrients_nutrient_solution_addition_(a+b)_ml (POST-CLEANING)

**Missing Values:** ✅ None detected.

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct          sample_values
experiment                 1           5     20.0000       ['Experiment 1']
replicate_1_t1             5           5    100.0000  [115, 30, 0, 12, 157]
replicate_2_t1             5           5    100.0000   [136, 30, 0, 9, 175]
replicate_3_t1             5           5    100.0000   [136, 30, 0, 9, 175]
replicate_1_t2             5           5    100.0000  [136, 30, 0, 21, 187]
replicate_2_t2             5           5    100.0000  [136, 30, 0, 21, 187]
replicate_3_t2             4           5     80.0000     [136, 30, 27, 329]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,replicate_3_t2,30.0000,136.0000,106.0000,-129.0000,295.0000,1,20.0000

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — nutrients_acid_consumption_(ml) (POST-CLEANING)

**Missing Values:** ✅ None detected.

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct     sample_values
experiment                 1           4     25.0000  ['Experiment 1']
replicate_1_t1             4           4    100.0000   [20, 14, 5, 39]
replicate_2_t1             4           4    100.0000   [20, 10, 5, 35]
replicate_3_t1             4           4    100.0000   [20, 10, 5, 35]
replicate_1_t2             4           4    100.0000   [20, 10, 5, 35]
replicate_2_t2             4           4    100.0000   [20, 10, 5, 35]
replicate_3_t2             4           4    100.0000   [20, 10, 5, 35]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — nutrients_water_consumption_l (POST-CLEANING)

**Missing Values:** ✅ None detected.

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct           sample_values
experiment                 1           5     20.0000        ['Experiment 1']
replicate_1_t1             4           5     80.0000         [10, 0, 15, 35]
replicate_2_t1             4           5     80.0000         [0, 10, 15, 25]
replicate_3_t1             4           5     80.0000         [0, 10, 15, 25]
replicate_1_t2             4           5     80.0000         [0, 10, 15, 25]
replicate_2_t2             3           5     60.0000             [0, 15, 30]
replicate_3_t2             5           5    100.0000  [100, 10, 16, 15, 141]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,replicate_1_t1,10.0000,15.0000,5.0000,2.5000,22.5000,2,40.0000

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — head_diameter (POST-CLEANING)

**Missing Values:**

               missing_count  missing_pct    dtype
plant_no                  24      11.7600  float64
head_diameter             24      11.7600      str

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,204,0.4900,['Experiment 1']
replicate,6,204,2.9400,"['Replicate 1', 'Replicate 2', 'Repl..."
day,5,204,2.4500,"['day 3', 'day 6', 'Day 9', 'Day 12'..."
plant_no,10,204,4.9000,"[1.0, 2.0, 3.0, 4.0, 5.0]"
head_diameter,86,204,42.1600,"['4*4', '5*5', '9*12', '11*12', '16*..."

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,plant_no,2.0000,5.0000,3.0000,-2.5000,9.5000,6,2.9400

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 1 — harvest (POST-CLEANING)

**Missing Values:**

                                          missing_count  missing_pct    dtype
plant_no                                              1       1.3700  float64
total_weight_g                                        1       1.3700  float64
plant_height_cm                                       1       1.3700  float64
shoot_length_cm                                       1       1.3700  float64
root_length_cm                                        1       1.3700  float64
head_diameter_cm                                      1       1.3700      str
stem_diameter_cm                                      1       1.3700  float64
shoot_weight_before_removing_wilted_l...              1       1.3700  float64
root_weight_g                                         1       1.3700  float64
no_of_leaves                                          1       1.3700  float64

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,73,1.3700,['Experiment 1']
plant_no,12,73,16.4400,"[1.0, 2.0, 3.0, 4.0, 5.0]"
total_weight_g,54,73,73.9700,"[243.0, 241.0, 251.0, 200.0, 209.0]"
plant_height_cm,26,73,35.6200,"[42.0, 54.0, 62.0, 55.0, 66.0]"
shoot_length_cm,13,73,17.8100,"[13.5, 10.5, 14.0, 13.0, 16.0]"
root_length_cm,33,73,45.2100,"[28.5, 43.5, 48.5, 41.5, 52.0]"
head_diameter_cm,35,73,47.9500,"['24*27', '27*27', '26*26.5', '26*26..."
stem_diameter_cm,6,73,8.2200,"[1.7, 2.0, 1.5, 1.4, 1.8]"
shoot_weight_before_removing_wilted_leaves_g,50,73,68.4900,"[210.0, 200.0, 212.0, 185.0, 178.0]"
shoot_weight_after_removing_wilted_leavesg,50,73,68.4900,"[208, 189, 183, 174, 171]"
root_weight_g,39,73,53.4200,"[33.0, 41.0, 39.0, 15.0, 22.0]"
no_of_leaves,21,73,28.7700,"[30.0, 34.0, 26.0, 25.0, 27.0]"
system,6,73,8.2200,"['R1-T1', 'R1-T2', 'R1-T3', 'R2-T1',..."

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,total_weight_g,217.7500,259.0000,41.2500,155.8750,320.8750,1,1.3700
1,plant_height_cm,54.0000,61.2500,7.2500,43.1250,72.1250,3,4.1100
2,shoot_length_cm,12.0000,14.0000,2.0000,9.0000,17.0000,1,1.3700
3,root_length_cm,40.0000,48.1250,8.1250,27.8125,60.3125,1,1.3700
4,stem_diameter_cm,2.0000,2.0000,0.0000,2.0000,2.0000,15,20.5500
5,shoot_weight_before_removing_wilted_...,181.5000,220.2500,38.7500,123.3750,278.3750,1,1.3700
6,shoot_weight_after_removing_wilted_l...,173.0000,212.0000,39.0000,114.5000,270.5000,2,2.7400
7,root_weight_g,24.0000,41.0000,17.0000,-1.5000,66.5000,8,10.9600

──────────────────────────────────────────────────────────────────────

## ✅ Experiment 2 — Post-Cleaning Validation

---

### 🔍 Experiment 2 — seedlings (POST-CLEANING)

**Missing Values:**

      missing_count  missing_pct          dtype
date             12     100.0000  datetime64[s]

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 2 column(s) with ≤1 unique value: `experiment`, `date`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,12,8.3300,['Experiment 2']
date,0,12,0.0000,[]
plant_no,12,12,100.0000,"[1, 2, 3, 4, 5]"
plant_height_cm,5,12,41.6700,"[11.0, 13.0, 12.5, 12.0, 14.0]"
shoot_length_cm,4,12,33.3300,"[5, 7, 6, 8]"
root_length_cm,4,12,33.3300,"[6.0, 7.5, 8.0, 7.0]"
head_diameter_cm,11,12,91.6700,"['7*8', '6*7', '5*6', '6*4', '6*4.5']"
stem_diameter_cm,2,12,16.6700,"[0.3, 0.2]"
total_weight_g,12,12,100.0000,"[5.13, 5.0, 5.25, 4.85, 5.36]"
shoot_weight_g,12,12,100.0000,"[2.41, 2.14, 1.58, 2.45, 1.93]"
root_weight_g,12,12,100.0000,"[2.72, 2.86, 3.67, 2.399999999999999..."
no_of_leaves,4,12,33.3300,"[7, 5, 6, 8]"

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,root_length_cm,6.0000,6.2500,0.2500,5.6250,6.6250,3,25.0000
1,stem_diameter_cm,0.3000,0.3000,0.0000,0.3000,0.3000,2,16.6700
2,total_weight_g,4.7700,5.2700,0.5000,4.0200,6.0200,2,16.6700

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — sensor_water_quality (POST-CLEANING)

**Missing Values:**

            missing_count  missing_pct          dtype
date                  718     100.0000  datetime64[s]
tme                   718     100.0000            str
ph                    718     100.0000            str
ec                    718     100.0000            str
tds                   718     100.0000            str
water_temp            718     100.0000            str

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 8 column(s) with ≤1 unique value: `experiment`, `replicate`, `date`, `tme`, `ph`, `ec`, `tds`, `water_temp`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,718,0.1400,['Experiment 2']
replicate,1,718,0.1400,['Replicate 1 T1']
date,0,718,0.0000,[]
tme,0,718,0.0000,[]
ph,0,718,0.0000,[]
ec,0,718,0.0000,[]
tds,0,718,0.0000,[]
water_temp,0,718,0.0000,[]
date_1,32,718,4.4600,"[Timestamp('2024-04-16 00:00:00'), T..."
tme_1,24,718,3.3400,"['10:00:00', '11:00:00', '12:00:00',..."
rh%,591,718,82.3100,"[57.77, 54.0, 52.89, 52.01, 52.46]"
air_temp,544,718,75.7700,"[28.28, 28.57, 27.68, 28.29, 27.32]"
co2,681,718,94.8500,"[485.7, 463.92, 450.51, 444.88, 440.13]"

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,rh%,54.2125,62.4575,8.2450,41.8450,74.8250,3,0.4200
1,air_temp,19.6500,24.8900,5.2400,11.7900,32.7500,5,0.7000
2,co2,438.7200,468.2775,29.5575,394.3837,512.6138,9,1.2500

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — portable_water_quality (POST-CLEANING)

**Missing Values:**

                                  missing_count  missing_pct           dtype
100000_rh_%_col_28                           29     100.0000         float64
date                                         12      41.3800  datetime64[us]
140000_air_air_parameters                     8      27.5900         float64
140000_air_temp_col_55                        8      27.5900         float64
140000_rh%_col_54                             8      27.5900         float64
100000_rh_%_col_27                            5      17.2400         float64
100000_air_temp_col_26                        5      17.2400         float64
100000_air_air_parameters                     5      17.2400         float64
140000_replicate_3_t1_water_temp              5      17.2400         float64
140000_replicate_3_t1_ph                      5      17.2400         float64
140000_replicate_3_t1_tds                     5      17.2400         float64
140000_replicate_3_t1_ec                      5      17.2400         float64
140000_replicate_1_t1_tds                     4      13.7900         float64
140000_replicate_1_t1_ec                      4      13.7900         float64
140000_replicate_1_t1_ph                      4      13.7900         float64
140000_replicate_1_t1_water_temp              4      13.7900         float64
140000_replicate_2_t1_water_temp              4      13.7900         float64
140000_replicate_2_t1_ph                      4      13.7900         float64
140000_replicate_2_t1_ec                      4      13.7900         float64
140000_replicate_2_t1_tds                     4      13.7900         float64
140000_replicate_1_t2_water_temp              4      13.7900         float64
140000_replicate_1_t2_ph                      4      13.7900         float64
140000_replicate_1_t2_ec                      4      13.7900         float64
140000_replicate_1_t2_tds                     4      13.7900         float64
140000_replicate_2_t2_tds                     4      13.7900         float64
140000_replicate_2_t2_ec                      4      13.7900         float64
140000_replicate_2_t2_ph                      4      13.7900         float64
140000_replicate_2_t2_water_temp              4      13.7900         float64
140000_replicate_3_t2_tds                     4      13.7900         float64
140000_replicate_3_t2_ec                      4      13.7900         float64
140000_replicate_3_t2_ph                      4      13.7900         float64
140000_replicate_3_t2_water_temp              4      13.7900         float64

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 2 column(s) with ≤1 unique value: `experiment`, `100000_rh_%_col_28`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,29,3.4500,['Experiment 2']
date,17,29,58.6200,"[Timestamp('2024-04-16 00:00:00'), T..."
100000_replicate_1_t1_ph,14,29,48.2800,"[6.8, 6.3, 6.6, 5.9, 6.0]"
100000_replicate_1_t1_ec,18,29,62.0700,"[1.44, 1.48, 1.72, 1.78, 1.79]"
100000_replicate_1_t1_tds,18,29,62.0700,"[0.72, 0.74, 0.86, 0.89, 0.895]"
100000_replicate_1_t1_water_temp,23,29,79.3100,"[25.0, 28.3, 25.3, 24.7, 22.8]"
100000_replicate_2_t1_ph,10,29,34.4800,"[7.0, 6.7, 6.2, 5.8, 5.7]"
100000_replicate_2_t1_ec,20,29,68.9700,"[1.33, 1.37, 1.71, 1.79, 1.75]"
100000_replicate_2_t1_tds,20,29,68.9700,"[0.665, 0.685, 0.855, 0.895, 0.875]"
100000_replicate_2_t1_water_temp,22,29,75.8600,"[25.2, 27.4, 25.8, 25.0, 24.0]"
100000_replicate_3_t1_ph,14,29,48.2800,"[7.0, 6.3, 6.8, 5.6, 5.7]"
100000_replicate_3_t1_ec,21,29,72.4100,"[1.33, 1.37, 1.73, 1.75, 1.78]"
100000_replicate_3_t1_tds,21,29,72.4100,"[0.665, 0.685, 0.865, 0.875, 0.89]"
100000_replicate_3_t1_water_temp,19,29,65.5200,"[24.3, 26.4, 24.8, 24.6, 23.6]"
100000_replicate_1_t2_ph,14,29,48.2800,"[6.9, 6.2, 6.7, 6.1, 5.8]"
100000_replicate_1_t2_ec,22,29,75.8600,"[1.89, 1.91, 2.17, 2.22, 2.2]"
100000_replicate_1_t2_tds,22,29,75.8600,"[0.945, 0.955, 1.085, 1.11, 1.1]"
100000_replicate_1_t2_water_temp,23,29,79.3100,"[25.0, 26.9, 24.6, 25.2, 23.2]"
100000_replicate_2_t2_ph,15,29,51.7200,"[7.0, 6.0, 6.5, 5.9, 5.6]"
100000_replicate_2_t2_ec,19,29,65.5200,"[1.95, 1.91, 2.27, 2.3, 2.24]"
100000_replicate_2_t2_tds,19,29,65.5200,"[0.975, 0.955, 1.135, 1.15, 1.12]"
100000_replicate_2_t2_water_temp,27,29,93.1000,"[26.0, 26.9, 24.9, 24.0, 25.4]"
100000_replicate_3_t2_ph,13,29,44.8300,"[6.9, 6.1, 6.3, 5.8, 6.7]"
100000_replicate_3_t2_ec,18,29,62.0700,"[1.8, 1.9, 2.22, 2.27, 2.25]"
100000_replicate_3_t2_tds,18,29,62.0700,"[0.9, 0.95, 1.11, 1.135, 1.125]"
100000_replicate_3_t2_water_temp,27,29,93.1000,"[25.3, 28.4, 25.6, 25.8, 24.7]"
100000_air_air_parameters,23,29,79.3100,"[7750.0, 77040.0, 70360.0, 7254.0, 3..."
100000_air_temp_col_26,23,29,79.3100,"[26.9, 24.2, 28.5, 23.9, 27.4]"
100000_rh_%_col_27,24,29,82.7600,"[63.5, 55.3, 53.6, 44.2, 70.2]"
100000_rh_%_col_28,0,29,0.0000,[]
140000_replicate_1_t1_ph,12,29,41.3800,"[6.8, 6.1, 6.0, 5.7, 5.9]"
140000_replicate_1_t1_ec,17,29,58.6200,"[1.75, 1.8, 1.79, 1.78, 1.76]"
140000_replicate_1_t1_tds,17,29,58.6200,"[0.875, 0.9, 0.895, 0.89, 0.88]"
140000_replicate_1_t1_water_temp,24,29,82.7600,"[25.8, 27.8, 28.3, 23.9, 25.6]"
140000_replicate_2_t1_ph,12,29,41.3800,"[6.7, 5.9, 6.2, 5.7, 5.8]"
140000_replicate_2_t1_ec,15,29,51.7200,"[1.75, 1.76, 1.74, 1.73, 1.71]"
140000_replicate_2_t1_tds,15,29,51.7200,"[0.875, 0.88, 0.87, 0.865, 0.855]"
140000_replicate_2_t1_water_temp,20,29,68.9700,"[25.8, 27.6, 27.8, 25.6, 27.4]"
140000_replicate_3_t1_ph,12,29,41.3800,"[6.8, 6.3, 5.8, 6.2, 6.0]"
140000_replicate_3_t1_ec,19,29,65.5200,"[1.72, 1.75, 1.78, 1.73, 1.76]"
140000_replicate_3_t1_tds,19,29,65.5200,"[0.86, 0.875, 0.89, 0.865, 0.88]"
140000_replicate_3_t1_water_temp,22,29,75.8600,"[25.8, 28.2, 27.6, 26.0, 25.4]"
140000_replicate_1_t2_ph,14,29,48.2800,"[6.7, 6.2, 5.7, 6.0, 6.1]"
140000_replicate_1_t2_ec,17,29,58.6200,"[2.17, 2.21, 2.3, 2.26, 2.18]"
140000_replicate_1_t2_tds,17,29,58.6200,"[1.085, 1.105, 1.15, 1.13, 1.09]"
140000_replicate_1_t2_water_temp,22,29,75.8600,"[26.0, 28.3, 25.8, 26.2, 25.7]"
140000_replicate_2_t2_ph,11,29,37.9300,"[6.5, 6.1, 6.0, 5.9, 5.7]"
140000_replicate_2_t2_ec,18,29,62.0700,"[2.27, 2.23, 2.28, 2.3, 2.21]"
140000_replicate_2_t2_tds,18,29,62.0700,"[1.135, 1.115, 1.14, 1.15, 1.105]"
140000_replicate_2_t2_water_temp,24,29,82.7600,"[25.8, 28.6, 27.0, 21.3, 25.7]"
140000_replicate_3_t2_ph,13,29,44.8300,"[6.3, 6.9, 5.7, 6.2, 5.8]"
140000_replicate_3_t2_ec,14,29,48.2800,"[2.2, 2.25, 2.26, 2.24, 2.22]"
140000_replicate_3_t2_tds,14,29,48.2800,"[1.1, 1.125, 1.13, 1.12, 1.11]"
140000_replicate_3_t2_water_temp,18,29,62.0700,"[26.6, 27.6, 27.8, 27.1, 27.0]"
140000_air_air_parameters,21,29,72.4100,"[79490.0, 6212.0, 5162.0, 49230.0, 4..."
140000_rh%_col_54,19,29,65.5200,"[24.9, 28.1, 25.6, 31.4, 29.5]"
140000_air_temp_col_55,20,29,68.9700,"[55.6, 55.3, 62.1, 59.8, 60.2]"

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,100000_replicate_1_t1_ec,1.7400,1.8300,0.0900,1.6050,1.9650,5,17.2400
1,100000_replicate_1_t1_tds,0.8700,0.9150,0.0450,0.8025,0.9825,5,17.2400
2,100000_replicate_2_t1_ec,1.7000,1.8200,0.1200,1.5200,2.0000,4,13.7900
3,100000_replicate_2_t1_tds,0.8500,0.9100,0.0600,0.7600,1.0000,4,13.7900
4,100000_replicate_3_t1_ec,1.7300,1.9500,0.2200,1.4000,2.2800,6,20.6900
5,100000_replicate_3_t1_tds,0.8650,0.9750,0.1100,0.7000,1.1400,6,20.6900
6,100000_replicate_1_t2_ec,2.1700,2.3400,0.1700,1.9150,2.5950,5,17.2400
7,100000_replicate_1_t2_tds,1.0850,1.1700,0.0850,0.9575,1.2975,5,17.2400
8,100000_replicate_2_t2_ec,2.2400,2.4200,0.1800,1.9700,2.6900,2,6.9000
9,100000_replicate_2_t2_tds,1.1200,1.2100,0.0900,0.9850,1.3450,2,6.9000
10,100000_replicate_3_t2_ec,2.1300,2.2400,0.1100,1.9650,2.4050,5,17.2400
11,100000_replicate_3_t2_tds,1.0650,1.1200,0.0550,0.9825,1.2025,5,17.2400
12,100000_air_air_parameters,18360.0000,28577.5000,10217.5000,3033.7500,43903.7500,5,17.2400
13,100000_rh_%_col_27,61.4250,71.3250,9.9000,46.5750,86.1750,1,3.4500
14,140000_replicate_1_t1_ec,1.7400,1.8000,0.0600,1.6500,1.8900,5,17.2400
15,140000_replicate_1_t1_tds,0.8700,0.9000,0.0300,0.8250,0.9450,5,17.2400
16,140000_replicate_2_t1_ec,1.7000,1.7600,0.0600,1.6100,1.8500,5,17.2400
17,140000_replicate_2_t1_tds,0.8500,0.8800,0.0300,0.8050,0.9250,5,17.2400
18,140000_replicate_3_t1_ph,5.9750,6.4000,0.4250,5.3375,7.0375,1,3.4500
19,140000_replicate_3_t1_ec,1.7375,1.9200,0.1825,1.4638,2.1937,4,13.7900
20,140000_replicate_3_t1_tds,0.8688,0.9600,0.0912,0.7319,1.0969,4,13.7900
21,140000_replicate_1_t2_ec,2.1800,2.3500,0.1700,1.9250,2.6050,4,13.7900
22,140000_replicate_1_t2_tds,1.0900,1.1750,0.0850,0.9625,1.3025,4,13.7900
23,140000_replicate_2_t2_ec,2.2300,2.4300,0.2000,1.9300,2.7300,2,6.9000
24,140000_replicate_2_t2_tds,1.1150,1.2150,0.1000,0.9650,1.3650,2,6.9000
25,140000_replicate_3_t2_ec,2.1300,2.2400,0.1100,1.9650,2.4050,2,6.9000
26,140000_replicate_3_t2_tds,1.0650,1.1200,0.0550,0.9825,1.2025,2,6.9000
27,140000_air_temp_col_55,59.7000,62.7000,3.0000,55.2000,67.2000,5,17.2400

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — nutrients_date (POST-CLEANING)

**Missing Values:**

      missing_count  missing_pct           dtype
date              1      50.0000  datetime64[us]

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 2 column(s) with ≤1 unique value: `experiment`, `date`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,2,50.0000,['Experiment 2']
date,1,2,50.0000,[Timestamp('2024-05-02 00:00:00')]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — nutrients_nutrient_solution_addition_(a+b)_ml (POST-CLEANING)

**Missing Values:** ✅ None detected.

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct     sample_values
experiment                 1           3     33.3300  ['Experiment 2']
replicate_1_t1             3           3    100.0000      [22, 15, 37]
replicate_2_t1             3           3    100.0000      [22, 10, 32]
replicate_3_t1             3           3    100.0000      [22, 10, 32]
replicate_1_t2             3           3    100.0000      [22, 10, 32]
replicate_2_t2             3           3    100.0000      [22, 10, 32]
replicate_3_t2             3           3    100.0000      [22, 25, 47]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — nutrients_water_consumption_l (POST-CLEANING)

**Missing Values:** ✅ None detected.

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 7 column(s) with ≤1 unique value: `experiment`, `replicate_1_t1`, `replicate_2_t1`, `replicate_3_t1`, `replicate_1_t2`, `replicate_2_t2`, `replicate_3_t2`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct     sample_values
experiment                 1           1    100.0000  ['Experiment 2']
replicate_1_t1             1           1    100.0000              [40]
replicate_2_t1             1           1    100.0000              [40]
replicate_3_t1             1           1    100.0000              [35]
replicate_1_t2             1           1    100.0000              [40]
replicate_2_t2             1           1    100.0000              [40]
replicate_3_t2             1           1    100.0000              [30]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — harvest (POST-CLEANING)

**Missing Values:**

                                          missing_count  missing_pct    dtype
plant_no                                              6       7.6900  float64
plant_height_cm                                       6       7.6900  float64
shoot_length_cm                                       6       7.6900  float64
root_length_cm                                        6       7.6900  float64
head_diameter_cm                                      6       7.6900      str
stem_diameter_cm                                      6       7.6900  float64
shoot_weight_before_removing_wilted_l...              6       7.6900  float64
shoot_weight_after_removing_wilted_le...              6       7.6900  float64
root_weight_g                                         6       7.6900  float64
no_of_leaves                                          6       7.6900  float64

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,78,1.2800,['Experiment 2']
plant_no,12,78,15.3800,"[1.0, 2.0, 3.0, 4.0, 5.0]"
total_weight_g,65,78,83.3300,"[317.0, 270.0, 311.0, 360.0, 326.0]"
plant_height_cm,27,78,34.6200,"[55.0, 50.0, 52.0, 70.0, 67.0]"
shoot_length_cm,13,78,16.6700,"[15.0, 16.0, 14.0, 17.0, 19.0]"
root_length_cm,35,78,44.8700,"[40.0, 34.0, 38.0, 53.0, 48.0]"
head_diameter_cm,37,78,47.4400,"['25*26', '30*25', '29*30', '30*31',..."
stem_diameter_cm,5,78,6.4100,"[2.0, 2.5, 2.1, 1.8, 1.5]"
shoot_weight_before_removing_wilted_leaves_g,54,78,69.2300,"[272.0, 248.0, 292.0, 300.0, 227.0]"
shoot_weight_after_removing_wilted_leavesg,58,78,74.3600,"[264.0, 239.0, 283.0, 293.0, 300.0]"
root_weight_g,30,78,38.4600,"[45.0, 22.0, 19.0, 60.0, 26.0]"
no_of_leaves,20,78,25.6400,"[37.0, 29.0, 38.0, 34.0, 33.0]"
system,6,78,7.6900,"['R1-T1', 'R2-T1', 'R3-T1', 'R1-T2',..."

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,stem_diameter_cm,2.0000,2.0000,0.0000,2.0000,2.0000,7,8.9700
1,shoot_weight_before_removing_wilted_...,265.7500,318.5000,52.7500,186.6250,397.6250,1,1.2800
2,shoot_weight_after_removing_wilted_l...,264.0000,319.2500,55.2500,181.1250,402.1250,1,1.2800
3,root_weight_g,30.0000,43.0000,13.0000,10.5000,62.5000,1,1.2800
4,no_of_leaves,38.7500,44.2500,5.5000,30.5000,52.5000,1,1.2800

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — taste_test (POST-CLEANING)

**Missing Values:**

    missing_count  missing_pct    dtype
13              6      85.7100      str
7               3      42.8600  float64
4               3      42.8600  float64
15              3      42.8600  float64
11              3      42.8600  float64
23              3      42.8600  float64
5               2      28.5700  float64
20              2      28.5700  float64
17              2      28.5700  float64
16              2      28.5700  float64
6               2      28.5700  float64
1               2      28.5700  float64
9               2      28.5700  float64
10              2      28.5700  float64
0               1      14.2900      str
3               1      14.2900      str
2               1      14.2900      str
12              1      14.2900      str
8               1      14.2900      str
19              1      14.2900      str
18              1      14.2900      str
21              1      14.2900      str
22              1      14.2900      str

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 2 column(s) with ≤1 unique value: `experiment`, `13`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,7,14.2900,['Experiment 2']
0,6,7,85.7100,"['Timestamp', '2024-05-15 16:28:34.8..."
1,5,7,71.4300,"[22.0, 26.0, 31.0, 28.0, 30.0]"
2,3,7,42.8600,"['Gender', 'Male', 'Female']"
3,3,7,42.8600,"['Smell (الرائحة)', 'Fresh', 'Normal']"
4,3,7,42.8600,"[9.0, 6.0, 7.0]"
5,3,7,42.8600,"[8.0, 6.0, 9.0]"
6,4,7,57.1400,"[9.0, 8.0, 7.0, 5.0]"
7,2,7,28.5700,"[4.0, 3.0]"
8,5,7,71.4300,"['Bitter (المرارة)', '5 (Extremely B..."
9,3,7,42.8600,"[5.0, 4.0, 3.0]"
10,3,7,42.8600,"[9.0, 8.0, 5.0]"
11,3,7,42.8600,"[9.0, 8.0, 6.0]"
12,4,7,57.1400,"['Overall evaluation (The best)', '1..."
13,1,7,14.2900,['Comments']
14,4,7,57.1400,"['R2', 'Smell (الرائحة)', 'Fresh', '..."
15,3,7,42.8600,"[9.0, 7.0, 8.0]"
16,3,7,42.8600,"[9.0, 7.0, 8.0]"
17,2,7,28.5700,"[9.0, 7.0]"
18,4,7,57.1400,"['Sweetness (الحلاوة )', '5 (Extreme..."
19,4,7,57.1400,"['Bitter (المرارة)', '5 (Extremely B..."
20,2,7,28.5700,"[5.0, 4.0]"
21,4,7,57.1400,"['After taste (المذاق الأخير)', '10 ..."
22,5,7,71.4300,"['Acceptance', '10 (like extremely )..."
23,3,7,42.8600,"[9.0, 7.0, 8.0]"

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,6,7.0000,8.0000,1.0000,5.5000,9.5000,1,14.2900
1,7,3.7500,4.0000,0.2500,3.3750,4.3750,1,14.2900
2,10,8.0000,9.0000,1.0000,6.5000,10.5000,1,14.2900
3,11,7.5000,8.2500,0.7500,6.3750,9.3750,1,14.2900

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 2 — form_responses (POST-CLEANING)

**Missing Values:**

    missing_count  missing_pct    dtype
24              6      85.7100      str
13              6      85.7100      str
7               3      42.8600  float64
4               3      42.8600  float64
11              3      42.8600  float64
15              3      42.8600  float64
23              3      42.8600  float64
1               2      28.5700  float64
17              2      28.5700  float64
20              2      28.5700  float64
16              2      28.5700  float64
6               2      28.5700  float64
5               2      28.5700  float64
10              2      28.5700  float64
9               2      28.5700  float64
3               1      14.2900      str
2               1      14.2900      str
0               1      14.2900      str
12              1      14.2900      str
8               1      14.2900      str
19              1      14.2900      str
18              1      14.2900      str
22              1      14.2900      str
21              1      14.2900      str

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 3 column(s) with ≤1 unique value: `experiment`, `13`, `24`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,7,14.2900,['Experiment 2']
0,6,7,85.7100,"['Timestamp', '2024-05-15 16:28:34.8..."
1,5,7,71.4300,"[22.0, 26.0, 31.0, 28.0, 30.0]"
2,3,7,42.8600,"['Gender', 'Male', 'Female']"
3,3,7,42.8600,"['Smell (الرائحة)', 'Fresh', 'Normal']"
4,3,7,42.8600,"[9.0, 6.0, 7.0]"
5,3,7,42.8600,"[8.0, 6.0, 9.0]"
6,4,7,57.1400,"[9.0, 8.0, 7.0, 5.0]"
7,2,7,28.5700,"[4.0, 3.0]"
8,5,7,71.4300,"['Bitter (المرارة)', '5 (Extremely B..."
9,3,7,42.8600,"[5.0, 4.0, 3.0]"
10,3,7,42.8600,"[9.0, 8.0, 5.0]"
11,3,7,42.8600,"[9.0, 8.0, 6.0]"
12,4,7,57.1400,"['Overall evaluation (The best)', '1..."
13,1,7,14.2900,['Comments']
14,4,7,57.1400,"['R2', 'Smell (الرائحة)', 'Fresh', '..."
15,3,7,42.8600,"[9.0, 7.0, 8.0]"
16,3,7,42.8600,"[9.0, 7.0, 8.0]"
17,2,7,28.5700,"[9.0, 7.0]"
18,4,7,57.1400,"['Sweetness (الحلاوة )', '5 (Extreme..."
19,4,7,57.1400,"['Bitter (المرارة)', '5 (Extremely B..."
20,2,7,28.5700,"[5.0, 4.0]"
21,4,7,57.1400,"['After taste (المذاق الأخير)', '10 ..."
22,5,7,71.4300,"['Acceptance', '10 (like extremely )..."
23,3,7,42.8600,"[9.0, 7.0, 8.0]"
24,1,7,14.2900,['Comments']

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,6,7.0000,8.0000,1.0000,5.5000,9.5000,1,14.2900
1,7,3.7500,4.0000,0.2500,3.3750,4.3750,1,14.2900
2,10,8.0000,9.0000,1.0000,6.5000,10.5000,1,14.2900
3,11,7.5000,8.2500,0.7500,6.3750,9.3750,1,14.2900

──────────────────────────────────────────────────────────────────────

## ✅ Experiment 3 — Post-Cleaning Validation

---

### 🔍 Experiment 3 — seedlings (POST-CLEANING)

**Missing Values:** ✅ None detected.

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,10,10.0000,['Experiment 3']
plant_no,10,10,100.0000,"[1, 2, 3, 4, 5]"
plant_height_cm,7,10,70.0000,"[16.5, 15.0, 16.0, 12.5, 13.5]"
shoot_length_cm,4,10,40.0000,"[8.0, 7.0, 6.0, 5.5]"
root_length_cm,6,10,60.0000,"[8.5, 8.0, 6.5, 7.5, 9.0]"
head_diameter_cm,10,10,100.0000,"['9*5', '8*5', '10*9', '6.5*6', '6.5..."
stem_diameter_cm,2,10,20.0000,"[0.3, 0.4]"
total_weight_g,3,10,30.0000,"[6, 5, 4]"
shoot_weight_g,3,10,30.0000,"[4, 3, 2]"
root_weight_g,3,10,30.0000,"[2, 3, 1]"
no_of_leaves,4,10,40.0000,"[12, 10, 11, 13]"

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,shoot_weight_g,3.0000,3.0000,0.0000,3.0000,3.0000,4,40.0000

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — sensor_water_quality (POST-CLEANING)

**Missing Values:**

            missing_count  missing_pct          dtype
date                  712     100.0000  datetime64[s]
tme                   712     100.0000            str
ph                    712     100.0000            str
ec                    712     100.0000            str
tds                   712     100.0000            str
water_temp            712     100.0000            str

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 8 column(s) with ≤1 unique value: `experiment`, `replicate`, `date`, `tme`, `ph`, `ec`, `tds`, `water_temp`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,712,0.1400,['Experiment 3']
replicate,1,712,0.1400,['Replicate 1 T1']
date,0,712,0.0000,[]
tme,0,712,0.0000,[]
ph,0,712,0.0000,[]
ec,0,712,0.0000,[]
tds,0,712,0.0000,[]
water_temp,0,712,0.0000,[]
date_1,32,712,4.4900,"[Timestamp('2024-05-19 00:00:00'), T..."
tme_1,24,712,3.3700,"['17:00:00', '18:00:00', '19:00:00',..."
rh%,595,712,83.5700,"[51.62, 53.18, 54.38, 55.19, 57.2]"
air_temp,501,712,70.3700,"[24.81, 23.45, 24.87, 25.29, 25.28]"
co2,679,712,95.3700,"[415.25, 415.76, 424.68, 432.47, 435..."

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,rh%,57.4675,65.4700,8.0025,45.4638,77.4738,5,0.7000
1,air_temp,23.8675,27.0725,3.2050,19.0600,31.8800,14,1.9700
2,co2,434.2450,462.5200,28.2750,391.8325,504.9325,15,2.1100

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — portable_water_quality (POST-CLEANING)

**Missing Values:**

                                  missing_count  missing_pct           dtype
100000_rh%_col_28                            33     100.0000         float64
date                                         20      60.6100  datetime64[us]
140000_air_temp_col_54                       11      33.3300         float64
140000_rh%_col_55                            11      33.3300         float64
100000_air_temp_col_26                       11      33.3300         float64
100000_rh%_col_27                            11      33.3300         float64
100000_air_air_parameters                    11      33.3300         float64
140000_air_air_parameters                    11      33.3300         float64
100000_replicate_3_t2_water_temp              8      24.2400         float64
140000_replicate_2_t2_ec                      7      21.2100         float64
140000_replicate_2_t2_ph                      7      21.2100         float64
140000_replicate_3_t1_water_temp              7      21.2100         float64
140000_replicate_1_t2_water_temp              7      21.2100         float64
140000_replicate_1_t2_ph                      7      21.2100         float64
140000_replicate_1_t2_ec                      7      21.2100         float64
140000_replicate_1_t2_tds                     7      21.2100         float64
140000_replicate_2_t2_tds                     7      21.2100         float64
100000_replicate_3_t2_ph                      7      21.2100         float64
100000_replicate_2_t2_ph                      7      21.2100         float64
140000_replicate_3_t2_water_temp              7      21.2100         float64
140000_replicate_2_t2_water_temp              7      21.2100         float64
140000_replicate_3_t2_ph                      7      21.2100         float64
140000_replicate_3_t2_ec                      7      21.2100         float64
140000_replicate_3_t2_tds                     7      21.2100         float64
100000_replicate_1_t2_water_temp              6      18.1800         float64
100000_replicate_2_t1_ph                      6      18.1800         float64
100000_replicate_3_t1_ph                      6      18.1800         float64
100000_replicate_3_t2_ec                      6      18.1800         float64
100000_replicate_1_t1_ph                      6      18.1800         float64
140000_replicate_3_t1_tds                     6      18.1800         float64
140000_replicate_3_t1_ph                      6      18.1800         float64
140000_replicate_3_t1_ec                      6      18.1800         float64
140000_replicate_1_t1_tds                     6      18.1800         float64
140000_replicate_1_t1_ec                      6      18.1800         float64
140000_replicate_1_t1_ph                      6      18.1800         float64
140000_replicate_2_t1_water_temp              6      18.1800         float64
100000_replicate_2_t2_tds                     6      18.1800         float64
100000_replicate_2_t2_water_temp              6      18.1800         float64
100000_replicate_2_t2_ec                      6      18.1800         float64
100000_replicate_3_t2_tds                     6      18.1800         float64
140000_replicate_2_t1_tds                     6      18.1800         float64
140000_replicate_2_t1_ec                      6      18.1800         float64
140000_replicate_2_t1_ph                      6      18.1800         float64
140000_replicate_1_t1_water_temp              6      18.1800         float64
100000_replicate_3_t1_water_temp              5      15.1500         float64
100000_replicate_2_t1_water_temp              5      15.1500         float64
100000_replicate_3_t1_ec                      5      15.1500         float64
100000_replicate_3_t1_tds                     5      15.1500         float64
100000_replicate_1_t1_tds                     5      15.1500         float64
100000_replicate_1_t1_water_temp              5      15.1500         float64
100000_replicate_2_t1_ec                      5      15.1500         float64
100000_replicate_1_t1_ec                      5      15.1500         float64
100000_replicate_1_t2_ec                      5      15.1500         float64
100000_replicate_1_t2_ph                      5      15.1500         float64
100000_replicate_1_t2_tds                     5      15.1500         float64
100000_replicate_2_t1_tds                     5      15.1500         float64

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 2 column(s) with ≤1 unique value: `experiment`, `100000_rh%_col_28`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,33,3.0300,['Experiment 3']
date,13,33,39.3900,"[Timestamp('2024-05-19 00:00:00'), T..."
100000_replicate_1_t1_ph,18,33,54.5500,"[6.9, 7.0, 7.2, 7.1, 6.6]"
100000_replicate_1_t1_ec,28,33,84.8500,"[2.17, 2.6, 1.74, 1.94, 1.98]"
100000_replicate_1_t1_tds,28,33,84.8500,"[1.085, 1.3, 0.87, 0.97, 0.99]"
100000_replicate_1_t1_water_temp,21,33,63.6400,"[21.4, 21.7, 22.3, 19.6, 20.8]"
100000_replicate_2_t1_ph,15,33,45.4500,"[7.2, 6.9, 6.6, 6.7, 6.4]"
100000_replicate_2_t1_ec,25,33,75.7600,"[2.62, 2.63, 2.32, 2.52, 1.56]"
100000_replicate_2_t1_tds,25,33,75.7600,"[1.31, 1.315, 1.16, 1.26, 0.78]"
100000_replicate_2_t1_water_temp,20,33,60.6100,"[21.3, 21.7, 22.2, 20.8, 23.9]"
100000_replicate_3_t1_ph,15,33,45.4500,"[7.6, 7.1, 7.2, 7.4, 7.0]"
100000_replicate_3_t1_ec,21,33,63.6400,"[2.6, 2.55, 1.75, 1.98, 1.57]"
100000_replicate_3_t1_tds,21,33,63.6400,"[1.3, 1.275, 0.875, 0.99, 0.785]"
100000_replicate_3_t1_water_temp,22,33,66.6700,"[21.3, 21.5, 22.5, 20.9, 20.4]"
100000_replicate_1_t2_ph,11,33,33.3300,"[7.6, 7.5, 7.7, 7.4, 7.3]"
100000_replicate_1_t2_ec,25,33,75.7600,"[2.4, 2.8, 1.73, 1.91, 1.97]"
100000_replicate_1_t2_tds,25,33,75.7600,"[1.2, 1.4, 0.865, 0.955, 0.985]"
100000_replicate_1_t2_water_temp,20,33,60.6100,"[21.3, 22.1, 20.8, 20.4, 20.6]"
100000_replicate_2_t2_ph,11,33,33.3300,"[7.8, 7.7, 7.6, 7.5, 7.4]"
100000_replicate_2_t2_ec,26,33,78.7900,"[2.8, 2.5, 1.76, 2.3, 2.02]"
100000_replicate_2_t2_tds,26,33,78.7900,"[1.4, 1.25, 0.88, 1.15, 1.01]"
100000_replicate_2_t2_water_temp,20,33,60.6100,"[21.3, 21.2, 22.5, 26.9, 20.5]"
100000_replicate_3_t2_ph,12,33,36.3600,"[7.7, 7.6, 7.8, 7.5, 8.0]"
100000_replicate_3_t2_ec,22,33,66.6700,"[2.7, 2.8, 1.75, 2.0, 2.66]"
100000_replicate_3_t2_tds,22,33,66.6700,"[1.35, 1.4, 0.875, 1.0, 1.33]"
100000_replicate_3_t2_water_temp,20,33,60.6100,"[21.7, 22.0, 22.8, 21.3, 20.8]"
100000_air_air_parameters,21,33,63.6400,"[1944.0, 1664.0, 33970.0, 20880.0, 1..."
100000_air_temp_col_26,17,33,51.5200,"[22.5, 25.0, 27.4, 26.5, 25.9]"
100000_rh%_col_27,21,33,63.6400,"[74.6, 73.9, 56.9, 72.8, 72.9]"
100000_rh%_col_28,0,33,0.0000,[]
140000_replicate_1_t1_ph,15,33,45.4500,"[6.8, 7.0, 6.7, 6.6, 6.3]"
140000_replicate_1_t1_ec,22,33,66.6700,"[2.6, 1.97, 1.96, 2.54, 1.56]"
140000_replicate_1_t1_tds,22,33,66.6700,"[1.3, 0.985, 0.98, 1.27, 0.78]"
140000_replicate_1_t1_water_temp,24,33,72.7300,"[22.5, 23.9, 22.3, 20.5, 22.4]"
140000_replicate_2_t1_ph,16,33,48.4800,"[7.1, 7.0, 6.8, 6.7, 6.4]"
140000_replicate_2_t1_ec,26,33,78.7900,"[2.62, 2.54, 2.49, 2.02, 2.03]"
140000_replicate_2_t1_tds,26,33,78.7900,"[1.31, 1.27, 1.245, 1.01, 1.015]"
140000_replicate_2_t1_water_temp,21,33,63.6400,"[22.8, 23.9, 22.3, 22.5, 22.6]"
140000_replicate_3_t1_ph,15,33,45.4500,"[7.5, 7.3, 7.2, 7.0, 6.7]"
140000_replicate_3_t1_ec,24,33,72.7300,"[2.13, 2.0, 1.99, 1.65, 1.55]"
140000_replicate_3_t1_tds,24,33,72.7300,"[1.065, 1.0, 0.995, 0.825, 0.775]"
140000_replicate_3_t1_water_temp,22,33,66.6700,"[22.3, 23.8, 22.4, 22.2, 21.7]"
140000_replicate_1_t2_ph,9,33,27.2700,"[7.4, 7.6, 7.5, 7.3, 7.2]"
140000_replicate_1_t2_ec,22,33,66.6700,"[2.8, 1.79, 1.06, 1.55, 1.96]"
140000_replicate_1_t2_tds,22,33,66.6700,"[1.4, 0.895, 0.53, 0.775, 0.98]"
140000_replicate_1_t2_water_temp,20,33,60.6100,"[23.2, 24.0, 22.4, 22.2, 21.7]"
140000_replicate_2_t2_ph,8,33,24.2400,"[7.6, 7.7, 7.5, 7.4, 7.3]"
140000_replicate_2_t2_ec,22,33,66.6700,"[2.5, 2.2, 2.03, 1.6, 1.95]"
140000_replicate_2_t2_tds,22,33,66.6700,"[1.25, 1.1, 1.015, 0.8, 0.975]"
140000_replicate_2_t2_water_temp,20,33,60.6100,"[23.2, 24.1, 26.9, 22.4, 21.8]"
140000_replicate_3_t2_ph,11,33,33.3300,"[7.5, 7.6, 7.7, 7.4, 7.3]"
140000_replicate_3_t2_ec,23,33,69.7000,"[2.7, 2.73, 1.99, 1.58, 1.57]"
140000_replicate_3_t2_tds,23,33,69.7000,"[1.35, 1.365, 0.995, 0.79, 0.785]"
140000_replicate_3_t2_water_temp,16,33,48.4800,"[23.7, 24.5, 23.6, 22.9, 22.5]"
140000_air_air_parameters,20,33,60.6100,"[20190.0, 33360.0, 33800.0, 31580.0,..."
140000_air_temp_col_54,19,33,57.5800,"[25.3, 24.9, 26.5, 30.2, 26.9]"
140000_rh%_col_55,21,33,63.6400,"[67.9, 70.3, 57.5, 61.9, 65.5]"

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,100000_replicate_2_t1_ec,2.4950,3.0825,0.5875,1.6138,3.9638,1,3.0300
1,100000_replicate_2_t1_tds,1.2475,1.5412,0.2937,0.8069,1.9819,1,3.0300
2,100000_replicate_1_t2_ph,7.1000,7.4250,0.3250,6.6125,7.9125,1,3.0300
3,100000_replicate_2_t2_water_temp,20.8000,22.5500,1.7500,18.1750,25.1750,2,6.0600
4,100000_replicate_3_t2_ph,7.3000,7.5750,0.2750,6.8875,7.9875,2,6.0600
5,100000_air_temp_col_26,25.4750,26.8750,1.4000,23.3750,28.9750,2,6.0600
6,140000_replicate_1_t1_water_temp,22.5000,24.8500,2.3500,18.9750,28.3750,1,3.0300
7,140000_replicate_2_t1_water_temp,22.6000,24.3500,1.7500,19.9750,26.9750,1,3.0300
8,140000_replicate_3_t1_water_temp,22.2250,24.0000,1.7750,19.5625,26.6625,1,3.0300
9,140000_replicate_1_t2_ph,7.2000,7.4000,0.2000,6.9000,7.7000,2,6.0600
10,140000_replicate_1_t2_water_temp,22.2250,24.0000,1.7750,19.5625,26.6625,1,3.0300
11,140000_replicate_2_t2_water_temp,22.4250,24.1750,1.7500,19.8000,26.8000,2,6.0600
12,140000_replicate_3_t2_ph,7.3000,7.5750,0.2750,6.8875,7.9875,1,3.0300
13,140000_replicate_3_t2_water_temp,23.0750,24.5000,1.4250,20.9375,26.6375,1,3.0300
14,140000_air_air_parameters,21030.0000,32880.0000,11850.0000,3255.0000,50655.0000,1,3.0300

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — nutrients_date (POST-CLEANING)

**Missing Values:**

      missing_count  missing_pct           dtype
date              2      66.6700  datetime64[us]

**Duplicate Rows:** ⚠️ **1** exact duplicates found.

**Constant Columns:** ⚠️ 2 column(s) with ≤1 unique value: `experiment`, `date`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,3,33.3300,['Experiment 3']
date,1,3,33.3300,[Timestamp('2024-05-24 00:00:00')]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — nutrients_nutrient_solution_addition_(a+b)_ml (POST-CLEANING)

**Missing Values:** ✅ None detected.

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct     sample_values
experiment                 1           3     33.3300  ['Experiment 3']
replicate_1_t1             3           3    100.0000   [180, 197, 377]
replicate_2_t1             3           3    100.0000   [180, 173, 353]
replicate_3_t1             3           3    100.0000   [180, 187, 367]
replicate_1_t2             3           3    100.0000   [180, 188, 368]
replicate_2_t2             3           3    100.0000   [180, 187, 367]
replicate_3_t2             3           3    100.0000   [180, 190, 370]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — nutrients_water_consumption_l (POST-CLEANING)

**Missing Values:** ✅ None detected.

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct       sample_values
experiment                 1           4     25.0000    ['Experiment 3']
replicate_1_t1             4           4    100.0000  [100, 45, 50, 195]
replicate_2_t1             4           4    100.0000  [100, 40, 50, 190]
replicate_3_t1             4           4    100.0000  [100, 30, 50, 180]
replicate_1_t2             4           4    100.0000  [100, 30, 50, 180]
replicate_2_t2             4           4    100.0000  [100, 35, 50, 185]
replicate_3_t2             4           4    100.0000  [100, 40, 50, 190]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — nutrients_acid_consumption_ml (POST-CLEANING)

**Missing Values:** ✅ None detected.

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

                unique_count  total_rows  unique_pct     sample_values
experiment                 1           2     50.0000  ['Experiment 3']
replicate_1_t1             2           2    100.0000          [15, 30]
replicate_2_t1             2           2    100.0000          [15, 30]
replicate_3_t1             2           2    100.0000          [15, 30]
replicate_1_t2             2           2    100.0000          [15, 30]
replicate_2_t2             2           2    100.0000          [15, 30]
replicate_3_t2             2           2    100.0000          [15, 30]

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR):** ✅ None detected.

──────────────────────────────────────────────────────────────────────

### 🔍 Experiment 3 — harvest (POST-CLEANING)

**Missing Values:**

                                          missing_count  missing_pct    dtype
plant_no                                              7       8.8600  float64
hd_cm                                                 6       7.5900      str
plant_height_cm                                       1       1.2700  float64
shoot_length_cm                                       1       1.2700  float64
root_length_cm                                        1       1.2700  float64
total_weight_g                                        1       1.2700  float64
stem_diameter_cm                                      1       1.2700  float64
shoot_weight_before_removing_wilted_l...              1       1.2700  float64
shoot_weight_after_removing_wilted_le...              1       1.2700  float64
root_weight_g                                         1       1.2700  float64
noof_leaves                                           1       1.2700  float64

**Duplicate Rows:** ✅ None detected.

**Constant Columns:** ⚠️ 1 column(s) with ≤1 unique value: `experiment`

**Unique Value Counts:**

,unique_count,total_rows,unique_pct,sample_values
experiment,1,79,1.2700,['Experiment 3']
system,7,79,8.8600,"['R1T1', 'System', 'R2T1', 'R3T1', '..."
plant_no,12,79,15.1900,"[1.0, 2.0, 3.0, 4.0, 5.0]"
plant_height_cm,33,79,41.7700,"[60.0, 75.0, 100.0, 72.0, 76.0]"
shoot_length_cm,14,79,17.7200,"[20.0, 19.0, 17.0, 15.0, 16.0]"
root_length_cm,35,79,44.3000,"[40.0, 41.0, 58.0, 83.0, 57.0]"
hd_cm,51,79,64.5600,"['30*31', '29*31', '28*30', '29*29',..."
total_weight_g,61,79,77.2200,"[328.0, 252.0, 294.0, 331.0, 357.0]"
stem_diameter_cm,9,79,11.3900,"[1.0, 1.5, 1.2, 1.141666667, 1.04166..."
shoot_weight_before_removing_wilted_leaves_g,64,79,81.0100,"[271.0, 244.0, 239.0, 295.0, 317.0]"
shoot_weight_after_removing_wilted_leaves_g,66,79,83.5400,"[269.0, 243.0, 237.0, 292.0, 317.0]"
root_weight_g,35,79,44.3000,"[57.0, 8.0, 55.0, 36.0, 40.0]"
noof_leaves,25,79,31.6500,"[42.0, 46.0, 43.0, 40.0, 36.0]"

**Invalid Numeric Values:** ✅ None detected.

**Negative Values:** ✅ None detected in numeric columns.

**Outliers (IQR Method, factor=1.5):**  \n> ⚠️ Flagged for review only — **not removed**.

,column,q1,q3,iqr,lower_bound,upper_bound,n_outliers,pct_outliers
0,plant_height_cm,60.0000,72.8125,12.8125,40.7812,92.0312,1,1.2700
1,shoot_length_cm,17.0000,19.0000,2.0000,14.0000,22.0000,1,1.2700
2,root_length_cm,42.0000,54.8125,12.8125,22.7812,74.0312,1,1.2700
3,stem_diameter_cm,1.0000,1.0000,0.0000,1.0000,1.0000,17,21.5200
4,root_weight_g,29.7500,39.0000,9.2500,15.8750,52.8750,5,6.3300

2026-07-15 19:51:08,089 | INFO | Post-cleaning validation complete.

──────────────────────────────────────────────────────────────────────

In [24]:
# ==========================================================================
# Compare pre- vs. post-cleaning metrics
# ==========================================================================

display(Markdown("### 📊 Before vs. After Cleaning Comparison"))

comparison_records = []
for exp_label in quality_reports:
    for tname in quality_reports[exp_label]:
        pre = quality_reports[exp_label].get(tname, {})
        post = validation_reports.get(exp_label, {}).get(tname, {})

        if not pre or not post:
            continue

        orig_table = parsed_data[exp_label].get(tname)
        clean_table = cleaned_data[exp_label].get(tname)

        orig_rows = orig_table.shape[0] if isinstance(orig_table, pd.DataFrame) else 0
        clean_rows = clean_table.shape[0] if isinstance(clean_table, pd.DataFrame) else 0

        pre_missing_df = pre.get("missing", pd.DataFrame())
        pre_missing = int(pre_missing_df["missing_count"].sum()) if not pre_missing_df.empty else 0
        post_missing_df = post.get("missing", pd.DataFrame())
        post_missing = int(post_missing_df["missing_count"].sum()) if not post_missing_df.empty else 0

        comparison_records.append({
            "Experiment": exp_label,
            "Table": tname,
            "Rows (Before)": orig_rows,
            "Rows (After)": clean_rows,
            "Rows Removed": orig_rows - clean_rows,
            "Duplicates (Before)": pre.get("duplicates", 0),
            "Duplicates (After)": post.get("duplicates", 0),
            "Total NaN (Before)": pre_missing,
            "Total NaN (After)": post_missing,
        })

if comparison_records:
    comparison_df = pd.DataFrame(comparison_records)
    display(comparison_df)
else:
    print("No comparison data available.")

### 📊 Before vs. After Cleaning Comparison

,Experiment,Table,Rows (Before),Rows (After),Rows Removed,Duplicates (Before),Duplicates (After),Total NaN (Before),Total NaN (After)
0,Experiment 1,seedlings,10,10,0,0,0,9,9
1,Experiment 1,sensor_water_quality,641,641,0,0,0,3850,4299
2,Experiment 1,portable_water_quality,33,32,1,0,0,607,788
3,Experiment 1,nutrients_date,24,5,19,18,2,19,3
4,Experiment 1,nutrients_nutrient_solution_addition...,24,5,19,18,0,114,0
5,Experiment 1,nutrients_acid_consumption_(ml),24,4,20,19,0,120,0
6,Experiment 1,nutrients_water_consumption_l,24,5,19,18,0,114,0
7,Experiment 1,head_diameter,300,204,96,96,0,240,48
8,Experiment 1,harvest,73,73,0,0,0,10,10
9,Experiment 2,seedlings,12,12,0,0,0,12,12
10,Experiment 2,sensor_water_quality,718,718,0,0,0,4307,4308
11,Experiment 2,portable_water_quality,29,29,0,0,0,32,180
12,Experiment 2,nutrients_date,24,2,22,21,0,22,1
13,Experiment 2,nutrients_nutrient_solution_addition...,24,3,21,20,0,126,0
14,Experiment 2,nutrients_water_consumption_l,24,1,23,22,0,132,0
15,Experiment 2,harvest,78,78,0,0,0,60,60
16,Experiment 2,taste_test,7,7,0,0,0,27,46
17,Experiment 2,form_responses,7,7,0,0,0,33,52
18,Experiment 3,seedlings,10,10,0,0,0,0,0
19,Experiment 3,sensor_water_quality,712,712,0,0,0,4271,4272
20,Experiment 3,portable_water_quality,33,33,0,0,0,134,412
21,Experiment 3,nutrients_date,11,3,8,7,1,8,2
22,Experiment 3,nutrients_nutrient_solution_addition...,11,3,8,7,0,48,0
23,Experiment 3,nutrients_water_consumption_l,11,4,7,6,0,42,0
24,Experiment 3,nutrients_acid_consumption_ml,11,2,9,8,0,48,0
25,Experiment 3,harvest,83,79,4,4,0,12,22

---

## Section 9 - Data Dictionary

Automatically generated professional data dictionaries for every cleaned dataset from each experiment. Each dictionary includes metadata about columns, data types, null counts/percentages, unique value counts, sample values, and descriptions.

In [25]:
KNOWN_DESCRIPTIONS = {
    "experiment": "Experiment identifier (Experiment 1, 2, or 3)",
    "replicate": "Replicate/treatment system identifier",
    "system": "Replicate-Treatment system code (e.g., R1T1)",
    "date": "Date of measurement",
    "date_": "Date of measurement",
    "plant_no": "Plant identification number within replicate",
    "plant_no_": "Plant identification number within replicate",
    "plant_height__cm": "Total plant height in centimeters",
    "plant_height_cm": "Total plant height in centimeters",
    "shoot_length_cm": "Shoot (above-root) length in centimeters",
    "root_length_cm": "Root length in centimeters",
    "head_diameter_cm": "Head diameter in centimeters (often W*H format)",
    "hd_cm": "Head diameter in centimeters (often W*H format)",
    "stem_diameter__cm": "Stem diameter in centimeters",
    "stem_diameter_cm": "Stem diameter in centimeters",
    "total_weight_g": "Total plant weight in grams",
    "shoot_weight_g": "Shoot weight in grams",
    "root_weight_g": "Root weight in grams",
    "root_weight_g_": "Root weight in grams",
    "no_of_leaves": "Number of leaves counted",
    "no_of_leaves_": "Number of leaves counted",
    "noof_leaves_": "Number of leaves counted",
    "ph": "pH level of nutrient solution",
    "ph_": "pH level of nutrient solution",
    "ec": "Electrical conductivity (mS/cm)",
    "ec_": "Electrical conductivity (mS/cm)",
    "tds": "Total dissolved solids (ppm)",
    "tds_": "Total dissolved solids (ppm)",
    "water_temp": "Water temperature (°C)",
    "water_temp_": "Water temperature (°C)",
    "air_temp": "Air temperature (°C)",
    "air_temp_": "Air temperature (°C)",
    "air_temp_c": "Air temperature (°C)",
    "rh%": "Relative humidity percentage",
    "rh_": "Relative humidity percentage",
    "rh_%": "Relative humidity percentage",
    "co2": "CO₂ concentration",
    "co2_": "CO₂ concentration",
    "co2_ppm": "CO₂ concentration in parts per million",
    "tme": "Time of measurement",
    "tme_": "Time of measurement",
    "day": "Day of measurement relative to transplant",
    "head_diameter": "Head diameter (often W*H format)",
    "shoot_weight_before_removing_wilted_leaves_g": "Shoot weight before removing wilted leaves (g)",
    "shoot_weight_after_removing_wilted_leavesg": "Shoot weight after removing wilted leaves (g)",
    "shoot_weight_before_removing_wilted_leaves_g_": "Shoot weight before removing wilted leaves (g)",
    "shoot_weight_after_removing_wilted_leaves_g_": "Shoot weight after removing wilted leaves (g)",
}

def generate_data_dictionary(df: pd.DataFrame) -> pd.DataFrame:
    """Generate a professional data dictionary for a DataFrame."""
    records = []
    for col in df.columns:
        col_lower = col.lower().replace(" ", "_")
        description = KNOWN_DESCRIPTIONS.get(col_lower, KNOWN_DESCRIPTIONS.get(col, ""))
        
        records.append({
            "Column Name": col,
            "Data Type": str(df[col].dtype),
            "Missing Count": int(df[col].isna().sum()),
            "Missing Percentage": round(df[col].isna().mean() * 100, 2),
            "Unique Values": int(df[col].nunique()),
            "Sample Values": str(df[col].dropna().unique()[:5].tolist()),
            "Description": description if description else ""
        })
    return pd.DataFrame(records)

# Create reports/data_dictionary/ directory
dict_dir = PROJECT_ROOT / "reports" / "data_dictionary"
dict_dir.mkdir(parents=True, exist_ok=True)

# Generate, display, and save data dictionaries
for exp_label, tables in cleaned_data.items():
    exp_idx = exp_label.split()[-1]
    display(Markdown(f"### 📂 {exp_label} — Data Dictionaries"))
    
    for tname, tdata in tables.items():
        if isinstance(tdata, pd.DataFrame) and not tdata.empty:
            dd_df = generate_data_dictionary(tdata)
            
            # Display
            display(Markdown(f"#### {exp_label} — {tname}"))
            display(dd_df)
            print()
            
            # Save
            csv_path = dict_dir / f"exp{exp_idx}_{tname}_dict.csv"
            dd_df.to_csv(csv_path, index=False)
            logger.info(f"Saved data dictionary to: {csv_path}")

print("\n✅ All data dictionaries generated and saved.")

### 📂 Experiment 1 — Data Dictionaries

#### Experiment 1 — seedlings

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 1'],"Experiment identifier (Experiment 1,..."
1,date,datetime64[us],9,90.0000,1,[Timestamp('2024-03-09 00:00:00')],Date of measurement
2,plant_no,int64,0,0.0000,10,"[1, 2, 3, 4, 5]",Plant identification number within r...
3,plant_height_cm,float64,0,0.0000,4,"[9.0, 10.0, 9.5, 12.0]",Total plant height in centimeters
4,shoot_length_cm,float64,0,0.0000,3,"[2.0, 3.0, 2.5]",Shoot (above-root) length in centime...
5,root_length_cm,float64,0,0.0000,3,"[7.0, 6.5, 9.0]",Root length in centimeters
6,head_diameter_cm,str,0,0.0000,7,"['4*2', '3.5*3', '3.5*2.5', '3*3', '...",Head diameter in centimeters (often ...
7,stem_diameter_cm,float64,0,0.0000,1,[0.1],Stem diameter in centimeters
8,total_weight_g,float64,0,0.0000,7,"[1.3, 1.2, 1.1, 1.14, 1.0]",Total plant weight in grams
9,shoot_weight_g,float64,0,0.0000,9,"[0.5, 0.55, 0.53, 0.45, 0.4]",Shoot weight in grams
10,root_weight_g,float64,0,0.0000,9,"[0.8, 0.6499999999999999, 0.57000000...",Root weight in grams
11,no_of_leaves,int64,0,0.0000,2,"[5, 4]",Number of leaves counted

2026-07-15 19:51:58,570 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp1_seedlings_dict.csv

#### Experiment 1 — sensor_water_quality

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 1'],"Experiment identifier (Experiment 1,..."
1,replicate,str,0,0.0000,1,['Replicate 1 T1'],Replicate/treatment system identifier
2,date,datetime64[s],641,100.0000,0,[],Date of measurement
3,tme,str,641,100.0000,0,[],Time of measurement
4,ph,str,641,100.0000,0,[],pH level of nutrient solution
5,ec,str,641,100.0000,0,[],Electrical conductivity (mS/cm)
6,tds,str,641,100.0000,0,[],Total dissolved solids (ppm)
7,water_temp,str,641,100.0000,0,[],Water temperature (°C)
8,date_1,datetime64[us],449,70.0500,10,"[Timestamp('2024-10-03 00:00:00'), T...",
9,tme_1,str,1,0.1600,24,"['10:00:00', '11:00:00', '12:00:00',...",
10,rh_%,float64,1,0.1600,554,"[49.08, 47.51, 46.8, 47.12, 47.64]",Relative humidity percentage
11,air_temp_c,float64,1,0.1600,512,"[24.18, 23.55, 23.81, 24.48, 24.74]",Air temperature (°C)
12,co2_ppm,float64,1,0.1600,620,"[406.96, 406.55, 413.38, 412.5, 408.94]",CO₂ concentration in parts per million

2026-07-15 19:51:58,588 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp1_sensor_water_quality_dict.csv

#### Experiment 1 — portable_water_quality

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 1'],"Experiment identifier (Experiment 1,..."
1,date,datetime64[us],21,65.6200,11,"[Timestamp('2024-03-10 00:00:00'), T...",Date of measurement
2,100000_replicate_1_t1_ph,float64,12,37.5000,12,"[5.3, 5.7, 5.9, 6.0, 5.8]",
3,100000_replicate_1_t1_ec,float64,12,37.5000,18,"[2.0, 1.95, 1.97, 1.92, 1.94]",
4,100000_replicate_1_t1_tds,float64,11,34.3800,19,"[1.0, 0.975, 0.985, 0.96, 0.97]",
5,100000_replicate_1_t1_water_temp,float64,12,37.5000,17,"[19.3, 22.0, 26.6, 24.3, 23.0]",
6,100000_replicate_2_t1_ph,float64,12,37.5000,9,"[5.8, 6.0, 5.9, 5.7, 5.5]",
7,100000_replicate_2_t1_ec,float64,12,37.5000,17,"[2.02, 2.0, 2.03, 2.01, 1.94]",
8,100000_replicate_2_t1_tds,float64,11,34.3800,18,"[1.01, 1.0, 1.015, 1.005, 0.97]",
9,100000_replicate_2_t1_water_temp,float64,12,37.5000,15,"[19.1, 21.2, 22.0, 25.1, 24.9]",
10,100000_replicate_3_t1_ph,float64,12,37.5000,12,"[5.6, 5.7, 5.8, 5.4, 5.5]",
11,100000_replicate_3_t1_ec,float64,12,37.5000,16,"[2.02, 2.01, 1.99, 2.03, 1.96]",
12,100000_replicate_3_t1_tds,float64,11,34.3800,17,"[1.01, 1.005, 0.995, 1.015, 0.98]",
13,100000_replicate_3_t1_water_temp,float64,12,37.5000,19,"[18.9, 20.6, 22.0, 24.0, 24.8]",
14,100000_replicate_1_t2_ph,float64,12,37.5000,12,"[5.6, 5.4, 5.5, 5.1, 5.2]",
15,100000_replicate_1_t2_ec,float64,12,37.5000,15,"[1.94, 1.98, 1.96, 1.95, 1.89]",
16,100000_replicate_1_t2_tds,float64,11,34.3800,16,"[0.97, 0.99, 0.98, 0.975, 0.945]",
17,100000_replicate_1_t2_water_temp,float64,12,37.5000,17,"[18.6, 21.4, 22.0, 25.0, 26.2]",
18,100000_replicate_2_t2_ph,float64,12,37.5000,11,"[5.8, 5.9, 5.5, 5.7, 5.4]",
19,100000_replicate_2_t2_ec,float64,12,37.5000,17,"[2.01, 2.02, 2.03, 2.0, 2.1]",
20,100000_replicate_2_t2_tds,float64,11,34.3800,18,"[1.005, 1.01, 1.015, 1.0, 1.05]",
21,100000_replicate_2_t2_water_temp,float64,12,37.5000,17,"[19.7, 22.0, 22.4, 22.9, 23.4]",
22,100000_replicate_3_t2_ph,float64,12,37.5000,11,"[5.6, 6.9, 6.5, 6.4, 6.0]",
23,100000_replicate_3_t2_ec,float64,12,37.5000,14,"[2.16, 1.54, 1.87, 1.82, 1.88]",
24,100000_replicate_3_t2_tds,float64,11,34.3800,15,"[1.08, 0.77, 0.935, 0.91, 0.94]",
25,100000_replicate_3_t2_water_temp,float64,12,37.5000,18,"[22.9, 22.6, 23.0, 26.2, 28.5]",
26,100000_air_air_parameters,float64,18,56.2500,14,"[50330.0, 60540.0, 22050.0, 38880.0,...",
27,100000_rh%_col_26,float64,18,56.2500,14,"[64.0, 45.0, 60.0, 68.1, 65.3]",
28,100000_air_temp_col_27,float64,18,56.2500,14,"[20.4, 29.5, 23.5, 22.3, 21.8]",
29,100000_air_temp_col_28,float64,32,100.0000,0,[],
30,140000_replicate_1_t1_ph,float64,14,43.7500,12,"[6.9, 5.2, 5.7, 6.0, 5.6]",
31,140000_replicate_1_t1_ec,float64,14,43.7500,15,"[1.61, 2.0, 1.94, 2.02, 1.93]",
32,140000_replicate_1_t1_tds,float64,12,37.5000,14,"[0.8, 1.0, 0.97, 1.01, 0.965]",
33,140000_replicate_1_t1_water_temp,float64,14,43.7500,15,"[22.5, 23.9, 25.7, 22.0, 26.0]",
34,140000_replicate_2_t1_ph,float64,14,43.7500,7,"[6.9, 5.8, 6.0, 6.1, 5.7]",
35,140000_replicate_2_t1_ec,float64,14,43.7500,13,"[1.57, 2.02, 2.01, 1.89, 1.9]",
36,140000_replicate_2_t1_tds,float64,12,37.5000,13,"[0.78, 1.01, 1.005, 0.945, 0.95]",
37,140000_replicate_2_t1_water_temp,float64,14,43.7500,17,"[22.5, 22.1, 25.7, 25.4, 24.8]",
38,140000_replicate_3_t1_ph,float64,14,43.7500,8,"[6.9, 5.7, 5.9, 5.8, 6.4]",
39,140000_replicate_3_t1_ec,float64,14,43.7500,16,"[1.56, 2.01, 2.0, 1.98, 2.02]",
40,140000_replicate_3_t1_tds,float64,12,37.5000,15,"[0.78, 1.005, 1.0, 0.99, 1.01]",
41,140000_replicate_3_t1_water_temp,float64,14,43.7500,15,"[22.3, 26.0, 25.0, 24.1, 24.9]",
42,140000_replicate_1_t2_ph,float64,14,43.7500,10,"[6.8, 5.4, 5.5, 5.6, 5.7]",
43,140000_replicate_1_t2_ec,float64,14,43.7500,15,"[1.57, 1.94, 1.98, 1.95, 1.75]",
44,140000_replicate_1_t2_tds,float64,12,37.5000,14,"[0.78, 0.97, 0.99, 0.975, 0.875]",
45,140000_replicate_1_t2_water_temp,float64,14,43.7500,16,"[22.7, 22.5, 25.4, 25.3, 26.0]",
46,140000_replicate_2_t2_ph,float64,14,43.7500,9,"[7.0, 5.8, 5.9, 6.0, 6.1]",
47,140000_replicate_2_t2_ec,float64,14,43.7500,14,"[1.56, 2.02, 2.01, 1.78, 1.79]",
48,140000_replicate_2_t2_tds,float64,12,37.5000,13,"[0.77, 1.01, 1.005, 0.89, 0.895]",
49,140000_replicate_2_t2_water_temp,float64,14,43.7500,16,"[22.9, 22.3, 25.5, 25.4, 25.6]",
50,140000_replicate_3_t2_ph,float64,14,43.7500,12,"[6.9, 5.6, 6.3, 6.5, 6.4]",
51,140000_replicate_3_t2_ec,float64,14,43.7500,15,"[1.56, 2.16, 1.86, 1.87, 1.82]",
52,140000_replicate_3_t2_tds,float64,12,37.5000,14,"[0.76, 1.08, 0.93, 0.935, 0.91]",
53,140000_replicate_3_t2_water_temp,float64,14,43.7500,16,"[23.0, 22.9, 26.0, 28.0, 24.7]",
54,140000_air_air_parameters,float64,25,78.1200,7,"[48300.0, 61270.0, 45190.0, 36530.0,...",
55,140000_rh%_col_54,float64,25,78.1200,7,"[60.8, 59.5, 55.0, 54.8, 61.7]",
56,140000_air_temp_col_55,float64,25,78.1200,7,"[22.1, 21.8, 26.7, 25.1, 26.3]",

2026-07-15 19:51:58,638 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp1_portable_water_quality_dict.csv

#### Experiment 1 — nutrients_date

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 1'],"Experiment identifier (Experiment 1,..."
1,date,datetime64[us],3,60.0000,2,"[Timestamp('2024-03-11 00:00:00'), T...",Date of measurement

2026-07-15 19:51:58,650 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp1_nutrients_date_dict.csv

#### Experiment 1 — nutrients_nutrient_solution_addition_(a+b)_ml

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 1'],"Experiment identifier (Experiment 1,..."
1,replicate_1_t1,int64,0,0.0000,5,"[115, 30, 0, 12, 157]",
2,replicate_2_t1,int64,0,0.0000,5,"[136, 30, 0, 9, 175]",
3,replicate_3_t1,int64,0,0.0000,5,"[136, 30, 0, 9, 175]",
4,replicate_1_t2,int64,0,0.0000,5,"[136, 30, 0, 21, 187]",
5,replicate_2_t2,int64,0,0.0000,5,"[136, 30, 0, 21, 187]",
6,replicate_3_t2,int64,0,0.0000,4,"[136, 30, 27, 329]",

2026-07-15 19:51:58,663 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp1_nutrients_nutrient_solution_addition_(a+b)_ml_dict.csv

#### Experiment 1 — nutrients_acid_consumption_(ml)

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 1'],"Experiment identifier (Experiment 1,..."
1,replicate_1_t1,int64,0,0.0000,4,"[20, 14, 5, 39]",
2,replicate_2_t1,int64,0,0.0000,4,"[20, 10, 5, 35]",
3,replicate_3_t1,int64,0,0.0000,4,"[20, 10, 5, 35]",
4,replicate_1_t2,int64,0,0.0000,4,"[20, 10, 5, 35]",
5,replicate_2_t2,int64,0,0.0000,4,"[20, 10, 5, 35]",
6,replicate_3_t2,int64,0,0.0000,4,"[20, 10, 5, 35]",

2026-07-15 19:51:58,675 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp1_nutrients_acid_consumption_(ml)_dict.csv

#### Experiment 1 — nutrients_water_consumption_l

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 1'],"Experiment identifier (Experiment 1,..."
1,replicate_1_t1,int64,0,0.0000,4,"[10, 0, 15, 35]",
2,replicate_2_t1,int64,0,0.0000,4,"[0, 10, 15, 25]",
3,replicate_3_t1,int64,0,0.0000,4,"[0, 10, 15, 25]",
4,replicate_1_t2,int64,0,0.0000,4,"[0, 10, 15, 25]",
5,replicate_2_t2,int64,0,0.0000,3,"[0, 15, 30]",
6,replicate_3_t2,int64,0,0.0000,5,"[100, 10, 16, 15, 141]",

2026-07-15 19:51:58,691 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp1_nutrients_water_consumption_l_dict.csv

#### Experiment 1 — head_diameter

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 1'],"Experiment identifier (Experiment 1,..."
1,replicate,str,0,0.0000,6,"['Replicate 1', 'Replicate 2', 'Repl...",Replicate/treatment system identifier
2,day,str,0,0.0000,5,"['day 3', 'day 6', 'Day 9', 'Day 12'...",Day of measurement relative to trans...
3,plant_no,float64,24,11.7600,10,"[1.0, 2.0, 3.0, 4.0, 5.0]",Plant identification number within r...
4,head_diameter,str,24,11.7600,86,"['4*4', '5*5', '9*12', '11*12', '16*...",Head diameter (often W*H format)

2026-07-15 19:51:58,707 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp1_head_diameter_dict.csv

#### Experiment 1 — harvest

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 1'],"Experiment identifier (Experiment 1,..."
1,plant_no,float64,1,1.3700,12,"[1.0, 2.0, 3.0, 4.0, 5.0]",Plant identification number within r...
2,total_weight_g,float64,1,1.3700,54,"[243.0, 241.0, 251.0, 200.0, 209.0]",Total plant weight in grams
3,plant_height_cm,float64,1,1.3700,26,"[42.0, 54.0, 62.0, 55.0, 66.0]",Total plant height in centimeters
4,shoot_length_cm,float64,1,1.3700,13,"[13.5, 10.5, 14.0, 13.0, 16.0]",Shoot (above-root) length in centime...
5,root_length_cm,float64,1,1.3700,33,"[28.5, 43.5, 48.5, 41.5, 52.0]",Root length in centimeters
6,head_diameter_cm,str,1,1.3700,35,"['24*27', '27*27', '26*26.5', '26*26...",Head diameter in centimeters (often ...
7,stem_diameter_cm,float64,1,1.3700,6,"[1.7, 2.0, 1.5, 1.4, 1.8]",Stem diameter in centimeters
8,shoot_weight_before_removing_wilted_...,float64,1,1.3700,50,"[210.0, 200.0, 212.0, 185.0, 178.0]",Shoot weight before removing wilted ...
9,shoot_weight_after_removing_wilted_l...,int64,0,0.0000,50,"[208, 189, 183, 174, 171]",Shoot weight after removing wilted l...
10,root_weight_g,float64,1,1.3700,39,"[33.0, 41.0, 39.0, 15.0, 22.0]",Root weight in grams
11,no_of_leaves,float64,1,1.3700,21,"[30.0, 34.0, 26.0, 25.0, 27.0]",Number of leaves counted
12,system,str,0,0.0000,6,"['R1-T1', 'R1-T2', 'R1-T3', 'R2-T1',...",Replicate-Treatment system code (e.g...

2026-07-15 19:51:58,726 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp1_harvest_dict.csv

### 📂 Experiment 2 — Data Dictionaries

#### Experiment 2 — seedlings

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 2'],"Experiment identifier (Experiment 1,..."
1,date,datetime64[s],12,100.0000,0,[],Date of measurement
2,plant_no,int64,0,0.0000,12,"[1, 2, 3, 4, 5]",Plant identification number within r...
3,plant_height_cm,float64,0,0.0000,5,"[11.0, 13.0, 12.5, 12.0, 14.0]",Total plant height in centimeters
4,shoot_length_cm,int64,0,0.0000,4,"[5, 7, 6, 8]",Shoot (above-root) length in centime...
5,root_length_cm,float64,0,0.0000,4,"[6.0, 7.5, 8.0, 7.0]",Root length in centimeters
6,head_diameter_cm,str,0,0.0000,11,"['7*8', '6*7', '5*6', '6*4', '6*4.5']",Head diameter in centimeters (often ...
7,stem_diameter_cm,float64,0,0.0000,2,"[0.3, 0.2]",Stem diameter in centimeters
8,total_weight_g,float64,0,0.0000,12,"[5.13, 5.0, 5.25, 4.85, 5.36]",Total plant weight in grams
9,shoot_weight_g,float64,0,0.0000,12,"[2.41, 2.14, 1.58, 2.45, 1.93]",Shoot weight in grams
10,root_weight_g,float64,0,0.0000,12,"[2.72, 2.86, 3.67, 2.399999999999999...",Root weight in grams
11,no_of_leaves,int64,0,0.0000,4,"[7, 5, 6, 8]",Number of leaves counted

2026-07-15 19:51:58,740 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp2_seedlings_dict.csv

#### Experiment 2 — sensor_water_quality

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 2'],"Experiment identifier (Experiment 1,..."
1,replicate,str,0,0.0000,1,['Replicate 1 T1'],Replicate/treatment system identifier
2,date,datetime64[s],718,100.0000,0,[],Date of measurement
3,tme,str,718,100.0000,0,[],Time of measurement
4,ph,str,718,100.0000,0,[],pH level of nutrient solution
5,ec,str,718,100.0000,0,[],Electrical conductivity (mS/cm)
6,tds,str,718,100.0000,0,[],Total dissolved solids (ppm)
7,water_temp,str,718,100.0000,0,[],Water temperature (°C)
8,date_1,datetime64[us],0,0.0000,32,"[Timestamp('2024-04-16 00:00:00'), T...",
9,tme_1,str,0,0.0000,24,"['10:00:00', '11:00:00', '12:00:00',...",
10,rh%,float64,0,0.0000,591,"[57.77, 54.0, 52.89, 52.01, 52.46]",Relative humidity percentage
11,air_temp,float64,0,0.0000,544,"[28.28, 28.57, 27.68, 28.29, 27.32]",Air temperature (°C)
12,co2,float64,0,0.0000,681,"[485.7, 463.92, 450.51, 444.88, 440.13]",CO₂ concentration

2026-07-15 19:51:58,757 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp2_sensor_water_quality_dict.csv

#### Experiment 2 — portable_water_quality

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 2'],"Experiment identifier (Experiment 1,..."
1,date,datetime64[us],12,41.3800,17,"[Timestamp('2024-04-16 00:00:00'), T...",Date of measurement
2,100000_replicate_1_t1_ph,float64,0,0.0000,14,"[6.8, 6.3, 6.6, 5.9, 6.0]",
3,100000_replicate_1_t1_ec,float64,0,0.0000,18,"[1.44, 1.48, 1.72, 1.78, 1.79]",
4,100000_replicate_1_t1_tds,float64,0,0.0000,18,"[0.72, 0.74, 0.86, 0.89, 0.895]",
5,100000_replicate_1_t1_water_temp,float64,0,0.0000,23,"[25.0, 28.3, 25.3, 24.7, 22.8]",
6,100000_replicate_2_t1_ph,float64,0,0.0000,10,"[7.0, 6.7, 6.2, 5.8, 5.7]",
7,100000_replicate_2_t1_ec,float64,0,0.0000,20,"[1.33, 1.37, 1.71, 1.79, 1.75]",
8,100000_replicate_2_t1_tds,float64,0,0.0000,20,"[0.665, 0.685, 0.855, 0.895, 0.875]",
9,100000_replicate_2_t1_water_temp,float64,0,0.0000,22,"[25.2, 27.4, 25.8, 25.0, 24.0]",
10,100000_replicate_3_t1_ph,float64,0,0.0000,14,"[7.0, 6.3, 6.8, 5.6, 5.7]",
11,100000_replicate_3_t1_ec,float64,0,0.0000,21,"[1.33, 1.37, 1.73, 1.75, 1.78]",
12,100000_replicate_3_t1_tds,float64,0,0.0000,21,"[0.665, 0.685, 0.865, 0.875, 0.89]",
13,100000_replicate_3_t1_water_temp,float64,0,0.0000,19,"[24.3, 26.4, 24.8, 24.6, 23.6]",
14,100000_replicate_1_t2_ph,float64,0,0.0000,14,"[6.9, 6.2, 6.7, 6.1, 5.8]",
15,100000_replicate_1_t2_ec,float64,0,0.0000,22,"[1.89, 1.91, 2.17, 2.22, 2.2]",
16,100000_replicate_1_t2_tds,float64,0,0.0000,22,"[0.945, 0.955, 1.085, 1.11, 1.1]",
17,100000_replicate_1_t2_water_temp,float64,0,0.0000,23,"[25.0, 26.9, 24.6, 25.2, 23.2]",
18,100000_replicate_2_t2_ph,float64,0,0.0000,15,"[7.0, 6.0, 6.5, 5.9, 5.6]",
19,100000_replicate_2_t2_ec,float64,0,0.0000,19,"[1.95, 1.91, 2.27, 2.3, 2.24]",
20,100000_replicate_2_t2_tds,float64,0,0.0000,19,"[0.975, 0.955, 1.135, 1.15, 1.12]",
21,100000_replicate_2_t2_water_temp,float64,0,0.0000,27,"[26.0, 26.9, 24.9, 24.0, 25.4]",
22,100000_replicate_3_t2_ph,float64,0,0.0000,13,"[6.9, 6.1, 6.3, 5.8, 6.7]",
23,100000_replicate_3_t2_ec,float64,0,0.0000,18,"[1.8, 1.9, 2.22, 2.27, 2.25]",
24,100000_replicate_3_t2_tds,float64,0,0.0000,18,"[0.9, 0.95, 1.11, 1.135, 1.125]",
25,100000_replicate_3_t2_water_temp,float64,0,0.0000,27,"[25.3, 28.4, 25.6, 25.8, 24.7]",
26,100000_air_air_parameters,float64,5,17.2400,23,"[7750.0, 77040.0, 70360.0, 7254.0, 3...",
27,100000_air_temp_col_26,float64,5,17.2400,23,"[26.9, 24.2, 28.5, 23.9, 27.4]",
28,100000_rh_%_col_27,float64,5,17.2400,24,"[63.5, 55.3, 53.6, 44.2, 70.2]",
29,100000_rh_%_col_28,float64,29,100.0000,0,[],
30,140000_replicate_1_t1_ph,float64,4,13.7900,12,"[6.8, 6.1, 6.0, 5.7, 5.9]",
31,140000_replicate_1_t1_ec,float64,4,13.7900,17,"[1.75, 1.8, 1.79, 1.78, 1.76]",
32,140000_replicate_1_t1_tds,float64,4,13.7900,17,"[0.875, 0.9, 0.895, 0.89, 0.88]",
33,140000_replicate_1_t1_water_temp,float64,4,13.7900,24,"[25.8, 27.8, 28.3, 23.9, 25.6]",
34,140000_replicate_2_t1_ph,float64,4,13.7900,12,"[6.7, 5.9, 6.2, 5.7, 5.8]",
35,140000_replicate_2_t1_ec,float64,4,13.7900,15,"[1.75, 1.76, 1.74, 1.73, 1.71]",
36,140000_replicate_2_t1_tds,float64,4,13.7900,15,"[0.875, 0.88, 0.87, 0.865, 0.855]",
37,140000_replicate_2_t1_water_temp,float64,4,13.7900,20,"[25.8, 27.6, 27.8, 25.6, 27.4]",
38,140000_replicate_3_t1_ph,float64,5,17.2400,12,"[6.8, 6.3, 5.8, 6.2, 6.0]",
39,140000_replicate_3_t1_ec,float64,5,17.2400,19,"[1.72, 1.75, 1.78, 1.73, 1.76]",
40,140000_replicate_3_t1_tds,float64,5,17.2400,19,"[0.86, 0.875, 0.89, 0.865, 0.88]",
41,140000_replicate_3_t1_water_temp,float64,5,17.2400,22,"[25.8, 28.2, 27.6, 26.0, 25.4]",
42,140000_replicate_1_t2_ph,float64,4,13.7900,14,"[6.7, 6.2, 5.7, 6.0, 6.1]",
43,140000_replicate_1_t2_ec,float64,4,13.7900,17,"[2.17, 2.21, 2.3, 2.26, 2.18]",
44,140000_replicate_1_t2_tds,float64,4,13.7900,17,"[1.085, 1.105, 1.15, 1.13, 1.09]",
45,140000_replicate_1_t2_water_temp,float64,4,13.7900,22,"[26.0, 28.3, 25.8, 26.2, 25.7]",
46,140000_replicate_2_t2_ph,float64,4,13.7900,11,"[6.5, 6.1, 6.0, 5.9, 5.7]",
47,140000_replicate_2_t2_ec,float64,4,13.7900,18,"[2.27, 2.23, 2.28, 2.3, 2.21]",
48,140000_replicate_2_t2_tds,float64,4,13.7900,18,"[1.135, 1.115, 1.14, 1.15, 1.105]",
49,140000_replicate_2_t2_water_temp,float64,4,13.7900,24,"[25.8, 28.6, 27.0, 21.3, 25.7]",
50,140000_replicate_3_t2_ph,float64,4,13.7900,13,"[6.3, 6.9, 5.7, 6.2, 5.8]",
51,140000_replicate_3_t2_ec,float64,4,13.7900,14,"[2.2, 2.25, 2.26, 2.24, 2.22]",
52,140000_replicate_3_t2_tds,float64,4,13.7900,14,"[1.1, 1.125, 1.13, 1.12, 1.11]",
53,140000_replicate_3_t2_water_temp,float64,4,13.7900,18,"[26.6, 27.6, 27.8, 27.1, 27.0]",
54,140000_air_air_parameters,float64,8,27.5900,21,"[79490.0, 6212.0, 5162.0, 49230.0, 4...",
55,140000_rh%_col_54,float64,8,27.5900,19,"[24.9, 28.1, 25.6, 31.4, 29.5]",
56,140000_air_temp_col_55,float64,8,27.5900,20,"[55.6, 55.3, 62.1, 59.8, 60.2]",

2026-07-15 19:51:58,794 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp2_portable_water_quality_dict.csv

#### Experiment 2 — nutrients_date

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 2'],"Experiment identifier (Experiment 1,..."
1,date,datetime64[us],1,50.0000,1,[Timestamp('2024-05-02 00:00:00')],Date of measurement

2026-07-15 19:51:58,809 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp2_nutrients_date_dict.csv

#### Experiment 2 — nutrients_nutrient_solution_addition_(a+b)_ml

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 2'],"Experiment identifier (Experiment 1,..."
1,replicate_1_t1,int64,0,0.0000,3,"[22, 15, 37]",
2,replicate_2_t1,int64,0,0.0000,3,"[22, 10, 32]",
3,replicate_3_t1,int64,0,0.0000,3,"[22, 10, 32]",
4,replicate_1_t2,int64,0,0.0000,3,"[22, 10, 32]",
5,replicate_2_t2,int64,0,0.0000,3,"[22, 10, 32]",
6,replicate_3_t2,int64,0,0.0000,3,"[22, 25, 47]",

2026-07-15 19:51:58,823 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp2_nutrients_nutrient_solution_addition_(a+b)_ml_dict.csv

#### Experiment 2 — nutrients_water_consumption_l

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 2'],"Experiment identifier (Experiment 1,..."
1,replicate_1_t1,int64,0,0.0000,1,[40],
2,replicate_2_t1,int64,0,0.0000,1,[40],
3,replicate_3_t1,int64,0,0.0000,1,[35],
4,replicate_1_t2,int64,0,0.0000,1,[40],
5,replicate_2_t2,int64,0,0.0000,1,[40],
6,replicate_3_t2,int64,0,0.0000,1,[30],

2026-07-15 19:51:58,839 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp2_nutrients_water_consumption_l_dict.csv

#### Experiment 2 — harvest

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 2'],"Experiment identifier (Experiment 1,..."
1,plant_no,float64,6,7.6900,12,"[1.0, 2.0, 3.0, 4.0, 5.0]",Plant identification number within r...
2,total_weight_g,float64,0,0.0000,65,"[317.0, 270.0, 311.0, 360.0, 326.0]",Total plant weight in grams
3,plant_height_cm,float64,6,7.6900,27,"[55.0, 50.0, 52.0, 70.0, 67.0]",Total plant height in centimeters
4,shoot_length_cm,float64,6,7.6900,13,"[15.0, 16.0, 14.0, 17.0, 19.0]",Shoot (above-root) length in centime...
5,root_length_cm,float64,6,7.6900,35,"[40.0, 34.0, 38.0, 53.0, 48.0]",Root length in centimeters
6,head_diameter_cm,str,6,7.6900,37,"['25*26', '30*25', '29*30', '30*31',...",Head diameter in centimeters (often ...
7,stem_diameter_cm,float64,6,7.6900,5,"[2.0, 2.5, 2.1, 1.8, 1.5]",Stem diameter in centimeters
8,shoot_weight_before_removing_wilted_...,float64,6,7.6900,54,"[272.0, 248.0, 292.0, 300.0, 227.0]",Shoot weight before removing wilted ...
9,shoot_weight_after_removing_wilted_l...,float64,6,7.6900,58,"[264.0, 239.0, 283.0, 293.0, 300.0]",Shoot weight after removing wilted l...
10,root_weight_g,float64,6,7.6900,30,"[45.0, 22.0, 19.0, 60.0, 26.0]",Root weight in grams
11,no_of_leaves,float64,6,7.6900,20,"[37.0, 29.0, 38.0, 34.0, 33.0]",Number of leaves counted
12,system,str,0,0.0000,6,"['R1-T1', 'R2-T1', 'R3-T1', 'R1-T2',...",Replicate-Treatment system code (e.g...

2026-07-15 19:51:58,857 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp2_harvest_dict.csv

#### Experiment 2 — taste_test

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 2'],"Experiment identifier (Experiment 1,..."
1,0,str,1,14.2900,6,"['Timestamp', '2024-05-15 16:28:34.8...",
2,1,float64,2,28.5700,5,"[22.0, 26.0, 31.0, 28.0, 30.0]",
3,2,str,1,14.2900,3,"['Gender', 'Male', 'Female']",
4,3,str,1,14.2900,3,"['Smell (الرائحة)', 'Fresh', 'Normal']",
5,4,float64,3,42.8600,3,"[9.0, 6.0, 7.0]",
6,5,float64,2,28.5700,3,"[8.0, 6.0, 9.0]",
7,6,float64,2,28.5700,4,"[9.0, 8.0, 7.0, 5.0]",
8,7,float64,3,42.8600,2,"[4.0, 3.0]",
9,8,str,1,14.2900,5,"['Bitter (المرارة)', '5 (Extremely B...",
10,9,float64,2,28.5700,3,"[5.0, 4.0, 3.0]",
11,10,float64,2,28.5700,3,"[9.0, 8.0, 5.0]",
12,11,float64,3,42.8600,3,"[9.0, 8.0, 6.0]",
13,12,str,1,14.2900,4,"['Overall evaluation (The best)', '1...",
14,13,str,6,85.7100,1,['Comments'],
15,14,str,0,0.0000,4,"['R2', 'Smell (الرائحة)', 'Fresh', '...",
16,15,float64,3,42.8600,3,"[9.0, 7.0, 8.0]",
17,16,float64,2,28.5700,3,"[9.0, 7.0, 8.0]",
18,17,float64,2,28.5700,2,"[9.0, 7.0]",
19,18,str,1,14.2900,4,"['Sweetness (الحلاوة )', '5 (Extreme...",
20,19,str,1,14.2900,4,"['Bitter (المرارة)', '5 (Extremely B...",
21,20,float64,2,28.5700,2,"[5.0, 4.0]",
22,21,str,1,14.2900,4,"['After taste (المذاق الأخير)', '10 ...",
23,22,str,1,14.2900,5,"['Acceptance', '10 (like extremely )...",
24,23,float64,3,42.8600,3,"[9.0, 7.0, 8.0]",

2026-07-15 19:51:58,877 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp2_taste_test_dict.csv

#### Experiment 2 — form_responses

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 2'],"Experiment identifier (Experiment 1,..."
1,0,str,1,14.2900,6,"['Timestamp', '2024-05-15 16:28:34.8...",
2,1,float64,2,28.5700,5,"[22.0, 26.0, 31.0, 28.0, 30.0]",
3,2,str,1,14.2900,3,"['Gender', 'Male', 'Female']",
4,3,str,1,14.2900,3,"['Smell (الرائحة)', 'Fresh', 'Normal']",
5,4,float64,3,42.8600,3,"[9.0, 6.0, 7.0]",
6,5,float64,2,28.5700,3,"[8.0, 6.0, 9.0]",
7,6,float64,2,28.5700,4,"[9.0, 8.0, 7.0, 5.0]",
8,7,float64,3,42.8600,2,"[4.0, 3.0]",
9,8,str,1,14.2900,5,"['Bitter (المرارة)', '5 (Extremely B...",
10,9,float64,2,28.5700,3,"[5.0, 4.0, 3.0]",
11,10,float64,2,28.5700,3,"[9.0, 8.0, 5.0]",
12,11,float64,3,42.8600,3,"[9.0, 8.0, 6.0]",
13,12,str,1,14.2900,4,"['Overall evaluation (The best)', '1...",
14,13,str,6,85.7100,1,['Comments'],
15,14,str,0,0.0000,4,"['R2', 'Smell (الرائحة)', 'Fresh', '...",
16,15,float64,3,42.8600,3,"[9.0, 7.0, 8.0]",
17,16,float64,2,28.5700,3,"[9.0, 7.0, 8.0]",
18,17,float64,2,28.5700,2,"[9.0, 7.0]",
19,18,str,1,14.2900,4,"['Sweetness (الحلاوة )', '5 (Extreme...",
20,19,str,1,14.2900,4,"['Bitter (المرارة)', '5 (Extremely B...",
21,20,float64,2,28.5700,2,"[5.0, 4.0]",
22,21,str,1,14.2900,4,"['After taste (المذاق الأخير)', '10 ...",
23,22,str,1,14.2900,5,"['Acceptance', '10 (like extremely )...",
24,23,float64,3,42.8600,3,"[9.0, 7.0, 8.0]",
25,24,str,6,85.7100,1,['Comments'],

2026-07-15 19:51:58,903 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp2_form_responses_dict.csv

### 📂 Experiment 3 — Data Dictionaries

#### Experiment 3 — seedlings

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 3'],"Experiment identifier (Experiment 1,..."
1,plant_no,int64,0,0.0000,10,"[1, 2, 3, 4, 5]",Plant identification number within r...
2,plant_height_cm,float64,0,0.0000,7,"[16.5, 15.0, 16.0, 12.5, 13.5]",Total plant height in centimeters
3,shoot_length_cm,float64,0,0.0000,4,"[8.0, 7.0, 6.0, 5.5]",Shoot (above-root) length in centime...
4,root_length_cm,float64,0,0.0000,6,"[8.5, 8.0, 6.5, 7.5, 9.0]",Root length in centimeters
5,head_diameter_cm,str,0,0.0000,10,"['9*5', '8*5', '10*9', '6.5*6', '6.5...",Head diameter in centimeters (often ...
6,stem_diameter_cm,float64,0,0.0000,2,"[0.3, 0.4]",Stem diameter in centimeters
7,total_weight_g,int64,0,0.0000,3,"[6, 5, 4]",Total plant weight in grams
8,shoot_weight_g,int64,0,0.0000,3,"[4, 3, 2]",Shoot weight in grams
9,root_weight_g,int64,0,0.0000,3,"[2, 3, 1]",Root weight in grams
10,no_of_leaves,int64,0,0.0000,4,"[12, 10, 11, 13]",Number of leaves counted

2026-07-15 19:51:58,917 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp3_seedlings_dict.csv

#### Experiment 3 — sensor_water_quality

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 3'],"Experiment identifier (Experiment 1,..."
1,replicate,str,0,0.0000,1,['Replicate 1 T1'],Replicate/treatment system identifier
2,date,datetime64[s],712,100.0000,0,[],Date of measurement
3,tme,str,712,100.0000,0,[],Time of measurement
4,ph,str,712,100.0000,0,[],pH level of nutrient solution
5,ec,str,712,100.0000,0,[],Electrical conductivity (mS/cm)
6,tds,str,712,100.0000,0,[],Total dissolved solids (ppm)
7,water_temp,str,712,100.0000,0,[],Water temperature (°C)
8,date_1,datetime64[us],0,0.0000,32,"[Timestamp('2024-05-19 00:00:00'), T...",
9,tme_1,str,0,0.0000,24,"['17:00:00', '18:00:00', '19:00:00',...",
10,rh%,float64,0,0.0000,595,"[51.62, 53.18, 54.38, 55.19, 57.2]",Relative humidity percentage
11,air_temp,float64,0,0.0000,501,"[24.81, 23.45, 24.87, 25.29, 25.28]",Air temperature (°C)
12,co2,float64,0,0.0000,679,"[415.25, 415.76, 424.68, 432.47, 435...",CO₂ concentration

2026-07-15 19:51:58,938 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp3_sensor_water_quality_dict.csv

#### Experiment 3 — portable_water_quality

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 3'],"Experiment identifier (Experiment 1,..."
1,date,datetime64[us],20,60.6100,13,"[Timestamp('2024-05-19 00:00:00'), T...",Date of measurement
2,100000_replicate_1_t1_ph,float64,6,18.1800,18,"[6.9, 7.0, 7.2, 7.1, 6.6]",
3,100000_replicate_1_t1_ec,float64,5,15.1500,28,"[2.17, 2.6, 1.74, 1.94, 1.98]",
4,100000_replicate_1_t1_tds,float64,5,15.1500,28,"[1.085, 1.3, 0.87, 0.97, 0.99]",
5,100000_replicate_1_t1_water_temp,float64,5,15.1500,21,"[21.4, 21.7, 22.3, 19.6, 20.8]",
6,100000_replicate_2_t1_ph,float64,6,18.1800,15,"[7.2, 6.9, 6.6, 6.7, 6.4]",
7,100000_replicate_2_t1_ec,float64,5,15.1500,25,"[2.62, 2.63, 2.32, 2.52, 1.56]",
8,100000_replicate_2_t1_tds,float64,5,15.1500,25,"[1.31, 1.315, 1.16, 1.26, 0.78]",
9,100000_replicate_2_t1_water_temp,float64,5,15.1500,20,"[21.3, 21.7, 22.2, 20.8, 23.9]",
10,100000_replicate_3_t1_ph,float64,6,18.1800,15,"[7.6, 7.1, 7.2, 7.4, 7.0]",
11,100000_replicate_3_t1_ec,float64,5,15.1500,21,"[2.6, 2.55, 1.75, 1.98, 1.57]",
12,100000_replicate_3_t1_tds,float64,5,15.1500,21,"[1.3, 1.275, 0.875, 0.99, 0.785]",
13,100000_replicate_3_t1_water_temp,float64,5,15.1500,22,"[21.3, 21.5, 22.5, 20.9, 20.4]",
14,100000_replicate_1_t2_ph,float64,5,15.1500,11,"[7.6, 7.5, 7.7, 7.4, 7.3]",
15,100000_replicate_1_t2_ec,float64,5,15.1500,25,"[2.4, 2.8, 1.73, 1.91, 1.97]",
16,100000_replicate_1_t2_tds,float64,5,15.1500,25,"[1.2, 1.4, 0.865, 0.955, 0.985]",
17,100000_replicate_1_t2_water_temp,float64,6,18.1800,20,"[21.3, 22.1, 20.8, 20.4, 20.6]",
18,100000_replicate_2_t2_ph,float64,7,21.2100,11,"[7.8, 7.7, 7.6, 7.5, 7.4]",
19,100000_replicate_2_t2_ec,float64,6,18.1800,26,"[2.8, 2.5, 1.76, 2.3, 2.02]",
20,100000_replicate_2_t2_tds,float64,6,18.1800,26,"[1.4, 1.25, 0.88, 1.15, 1.01]",
21,100000_replicate_2_t2_water_temp,float64,6,18.1800,20,"[21.3, 21.2, 22.5, 26.9, 20.5]",
22,100000_replicate_3_t2_ph,float64,7,21.2100,12,"[7.7, 7.6, 7.8, 7.5, 8.0]",
23,100000_replicate_3_t2_ec,float64,6,18.1800,22,"[2.7, 2.8, 1.75, 2.0, 2.66]",
24,100000_replicate_3_t2_tds,float64,6,18.1800,22,"[1.35, 1.4, 0.875, 1.0, 1.33]",
25,100000_replicate_3_t2_water_temp,float64,8,24.2400,20,"[21.7, 22.0, 22.8, 21.3, 20.8]",
26,100000_air_air_parameters,float64,11,33.3300,21,"[1944.0, 1664.0, 33970.0, 20880.0, 1...",
27,100000_air_temp_col_26,float64,11,33.3300,17,"[22.5, 25.0, 27.4, 26.5, 25.9]",
28,100000_rh%_col_27,float64,11,33.3300,21,"[74.6, 73.9, 56.9, 72.8, 72.9]",
29,100000_rh%_col_28,float64,33,100.0000,0,[],
30,140000_replicate_1_t1_ph,float64,6,18.1800,15,"[6.8, 7.0, 6.7, 6.6, 6.3]",
31,140000_replicate_1_t1_ec,float64,6,18.1800,22,"[2.6, 1.97, 1.96, 2.54, 1.56]",
32,140000_replicate_1_t1_tds,float64,6,18.1800,22,"[1.3, 0.985, 0.98, 1.27, 0.78]",
33,140000_replicate_1_t1_water_temp,float64,6,18.1800,24,"[22.5, 23.9, 22.3, 20.5, 22.4]",
34,140000_replicate_2_t1_ph,float64,6,18.1800,16,"[7.1, 7.0, 6.8, 6.7, 6.4]",
35,140000_replicate_2_t1_ec,float64,6,18.1800,26,"[2.62, 2.54, 2.49, 2.02, 2.03]",
36,140000_replicate_2_t1_tds,float64,6,18.1800,26,"[1.31, 1.27, 1.245, 1.01, 1.015]",
37,140000_replicate_2_t1_water_temp,float64,6,18.1800,21,"[22.8, 23.9, 22.3, 22.5, 22.6]",
38,140000_replicate_3_t1_ph,float64,6,18.1800,15,"[7.5, 7.3, 7.2, 7.0, 6.7]",
39,140000_replicate_3_t1_ec,float64,6,18.1800,24,"[2.13, 2.0, 1.99, 1.65, 1.55]",
40,140000_replicate_3_t1_tds,float64,6,18.1800,24,"[1.065, 1.0, 0.995, 0.825, 0.775]",
41,140000_replicate_3_t1_water_temp,float64,7,21.2100,22,"[22.3, 23.8, 22.4, 22.2, 21.7]",
42,140000_replicate_1_t2_ph,float64,7,21.2100,9,"[7.4, 7.6, 7.5, 7.3, 7.2]",
43,140000_replicate_1_t2_ec,float64,7,21.2100,22,"[2.8, 1.79, 1.06, 1.55, 1.96]",
44,140000_replicate_1_t2_tds,float64,7,21.2100,22,"[1.4, 0.895, 0.53, 0.775, 0.98]",
45,140000_replicate_1_t2_water_temp,float64,7,21.2100,20,"[23.2, 24.0, 22.4, 22.2, 21.7]",
46,140000_replicate_2_t2_ph,float64,7,21.2100,8,"[7.6, 7.7, 7.5, 7.4, 7.3]",
47,140000_replicate_2_t2_ec,float64,7,21.2100,22,"[2.5, 2.2, 2.03, 1.6, 1.95]",
48,140000_replicate_2_t2_tds,float64,7,21.2100,22,"[1.25, 1.1, 1.015, 0.8, 0.975]",
49,140000_replicate_2_t2_water_temp,float64,7,21.2100,20,"[23.2, 24.1, 26.9, 22.4, 21.8]",
50,140000_replicate_3_t2_ph,float64,7,21.2100,11,"[7.5, 7.6, 7.7, 7.4, 7.3]",
51,140000_replicate_3_t2_ec,float64,7,21.2100,23,"[2.7, 2.73, 1.99, 1.58, 1.57]",
52,140000_replicate_3_t2_tds,float64,7,21.2100,23,"[1.35, 1.365, 0.995, 0.79, 0.785]",
53,140000_replicate_3_t2_water_temp,float64,7,21.2100,16,"[23.7, 24.5, 23.6, 22.9, 22.5]",
54,140000_air_air_parameters,float64,11,33.3300,20,"[20190.0, 33360.0, 33800.0, 31580.0,...",
55,140000_air_temp_col_54,float64,11,33.3300,19,"[25.3, 24.9, 26.5, 30.2, 26.9]",
56,140000_rh%_col_55,float64,11,33.3300,21,"[67.9, 70.3, 57.5, 61.9, 65.5]",

2026-07-15 19:51:58,975 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp3_portable_water_quality_dict.csv

#### Experiment 3 — nutrients_date

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 3'],"Experiment identifier (Experiment 1,..."
1,date,datetime64[us],2,66.6700,1,[Timestamp('2024-05-24 00:00:00')],Date of measurement

2026-07-15 19:51:58,987 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp3_nutrients_date_dict.csv

#### Experiment 3 — nutrients_nutrient_solution_addition_(a+b)_ml

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 3'],"Experiment identifier (Experiment 1,..."
1,replicate_1_t1,int64,0,0.0000,3,"[180, 197, 377]",
2,replicate_2_t1,int64,0,0.0000,3,"[180, 173, 353]",
3,replicate_3_t1,int64,0,0.0000,3,"[180, 187, 367]",
4,replicate_1_t2,int64,0,0.0000,3,"[180, 188, 368]",
5,replicate_2_t2,int64,0,0.0000,3,"[180, 187, 367]",
6,replicate_3_t2,int64,0,0.0000,3,"[180, 190, 370]",

2026-07-15 19:51:59,004 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp3_nutrients_nutrient_solution_addition_(a+b)_ml_dict.csv

#### Experiment 3 — nutrients_water_consumption_l

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 3'],"Experiment identifier (Experiment 1,..."
1,replicate_1_t1,int64,0,0.0000,4,"[100, 45, 50, 195]",
2,replicate_2_t1,int64,0,0.0000,4,"[100, 40, 50, 190]",
3,replicate_3_t1,int64,0,0.0000,4,"[100, 30, 50, 180]",
4,replicate_1_t2,int64,0,0.0000,4,"[100, 30, 50, 180]",
5,replicate_2_t2,int64,0,0.0000,4,"[100, 35, 50, 185]",
6,replicate_3_t2,int64,0,0.0000,4,"[100, 40, 50, 190]",

2026-07-15 19:51:59,017 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp3_nutrients_water_consumption_l_dict.csv

#### Experiment 3 — nutrients_acid_consumption_ml

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 3'],"Experiment identifier (Experiment 1,..."
1,replicate_1_t1,int64,0,0.0000,2,"[15, 30]",
2,replicate_2_t1,int64,0,0.0000,2,"[15, 30]",
3,replicate_3_t1,int64,0,0.0000,2,"[15, 30]",
4,replicate_1_t2,int64,0,0.0000,2,"[15, 30]",
5,replicate_2_t2,int64,0,0.0000,2,"[15, 30]",
6,replicate_3_t2,int64,0,0.0000,2,"[15, 30]",

2026-07-15 19:51:59,029 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp3_nutrients_acid_consumption_ml_dict.csv

#### Experiment 3 — harvest

,Column Name,Data Type,Missing Count,Missing Percentage,Unique Values,Sample Values,Description
0,experiment,str,0,0.0000,1,['Experiment 3'],"Experiment identifier (Experiment 1,..."
1,system,str,0,0.0000,7,"['R1T1', 'System', 'R2T1', 'R3T1', '...",Replicate-Treatment system code (e.g...
2,plant_no,float64,7,8.8600,12,"[1.0, 2.0, 3.0, 4.0, 5.0]",Plant identification number within r...
3,plant_height_cm,float64,1,1.2700,33,"[60.0, 75.0, 100.0, 72.0, 76.0]",Total plant height in centimeters
4,shoot_length_cm,float64,1,1.2700,14,"[20.0, 19.0, 17.0, 15.0, 16.0]",Shoot (above-root) length in centime...
5,root_length_cm,float64,1,1.2700,35,"[40.0, 41.0, 58.0, 83.0, 57.0]",Root length in centimeters
6,hd_cm,str,6,7.5900,51,"['30*31', '29*31', '28*30', '29*29',...",Head diameter in centimeters (often ...
7,total_weight_g,float64,1,1.2700,61,"[328.0, 252.0, 294.0, 331.0, 357.0]",Total plant weight in grams
8,stem_diameter_cm,float64,1,1.2700,9,"[1.0, 1.5, 1.2, 1.141666667, 1.04166...",Stem diameter in centimeters
9,shoot_weight_before_removing_wilted_...,float64,1,1.2700,64,"[271.0, 244.0, 239.0, 295.0, 317.0]",Shoot weight before removing wilted ...
10,shoot_weight_after_removing_wilted_l...,float64,1,1.2700,66,"[269.0, 243.0, 237.0, 292.0, 317.0]",
11,root_weight_g,float64,1,1.2700,35,"[57.0, 8.0, 55.0, 36.0, 40.0]",Root weight in grams
12,noof_leaves,float64,1,1.2700,25,"[42.0, 46.0, 43.0, 40.0, 36.0]",

2026-07-15 19:51:59,051 | INFO | Saved data dictionary to: e:\HydroGrow-AI\reports\data_dictionary\exp3_harvest_dict.csv

✅ All data dictionaries generated and saved.